# Generated by scripts/generate_from_openapi.py from zedge_app_profile_service.swagger.json
# Do not edit by hand — re-run: uv run python scripts/generate_from_openapi.py

from __future__ import annotations
from enum import Enum
from pydantic import Base64Str, BaseModel, Field, confloat, constr
from typing import Any


class AppCategory(Enum):
    app_category_unspecified = "APP_CATEGORY_UNSPECIFIED"
    app_category_operating_system = "APP_CATEGORY_OPERATING_SYSTEM"
    app_category_industrial = "APP_CATEGORY_INDUSTRIAL"
    app_category_edge_application = "APP_CATEGORY_EDGE_APPLICATION"
    app_category_networking = "APP_CATEGORY_NETWORKING"
    app_category_security = "APP_CATEGORY_SECURITY"
    app_category_data_analytics = "APP_CATEGORY_DATA_ANALYTICS"
    app_category_cloud_application = "APP_CATEGORY_CLOUD_APPLICATION"
    app_category_devops = "APP_CATEGORY_DEVOPS"
    app_category_others = "APP_CATEGORY_OTHERS"


class AppInstanceLogs(BaseModel):
    access: bool = Field(
        ...,
        description="Flags to enable / disable sending of logs generated by app instance to zedcloud",
    )


class AppProfileFilter(BaseModel):
    name_pattern: str | None = Field(
        default=None, alias="namePattern", description="app profile name pattern"
    )
    id: str | None = Field(default=None, description="app profile id")


class AppProfileInfo(BaseModel):
    app_profile_id: (
        constr(
            pattern=r"[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
        )
        | None
    ) = Field(
        default=None, alias="appProfileId", description="Unique ID of the asset group."
    )
    version: int | None = None


class AppProfileStatusType(Enum):
    app_profile_status_type_inactive = "APP_PROFILE_STATUS_TYPE_INACTIVE"
    app_profile_status_type_active = "APP_PROFILE_STATUS_TYPE_ACTIVE"


class AppType(Enum):
    app_type_unspecified = "APP_TYPE_UNSPECIFIED"
    app_type_vm = "APP_TYPE_VM"
    app_type_vm_runtime = "APP_TYPE_VM_RUNTIME"
    app_type_container = "APP_TYPE_CONTAINER"
    app_type_module = "APP_TYPE_MODULE"
    app_type_docker_compose = "APP_TYPE_DOCKER_COMPOSE"


class AssetIDs(BaseModel):
    ids: list[str] | None = None


class AssetTag(BaseModel):
    tag: dict[str, str] | None = Field(
        default=None,
        description="Tags are name/value pairs that enable you to categorize resources. Tag names are case insensitive with max_length 512 and min_length 3. Tag values are case sensitive with max_length 256 and min_length 3.",
    )


class AssetTags(BaseModel):
    asset_tag: list[AssetTag] | None = Field(default=None, alias="assetTag")


class Author(BaseModel):
    user: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DeveloperPane:Name_Field, AppDetailsPage:DeveloperPane:Name_Field",
        title="Name of the developer",
    )
    group: str | None = Field(default=None, title="Not used by ZedUI")
    company: str | None = Field(
        default=None,
        description="UI map: AppEditPage:IdentityPane:Category_Field, AppDetailsPage:IdentityPane:Category_Field",
        title="Company of the developer",
    )
    website: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DeveloperPane:Website_Field, AppDetailsPage:DeveloperPane:Website_Field",
        title="Website of the developer company",
    )
    email: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DeveloperPane:Email_Field, AppDetailsPage:DeveloperPane:Email_Field",
        title="Contact email of the developer company",
    )


class ContainerDetail(BaseModel):
    container_create_option: str | None = Field(
        default=None,
        alias="containerCreateOption",
        description="Create options direct the creation of the Docker container",
        title="Base64 encoded container specific details",
    )


class Cursor(BaseModel):
    page_token: str | None = Field(
        default=None, alias="pageToken", description="Page Token"
    )
    order_by: list[str] | None = Field(
        default=None,
        alias="orderBy",
        description="OrderBy helps in sorting the list response",
    )
    page_num: float | None = Field(
        default=None, alias="pageNum", description="Page Number"
    )
    page_size: float | None = Field(
        default=None, alias="pageSize", description="Defines the page size"
    )
    total_pages: float | None = Field(
        default=None,
        alias="totalPages",
        description="Total number of pages to be fetched.",
    )


class DeploymentType(Enum):
    deployment_type_unspecified = "DEPLOYMENT_TYPE_UNSPECIFIED"
    deployment_type_stand_alone = "DEPLOYMENT_TYPE_STAND_ALONE"
    deployment_type_azure = "DEPLOYMENT_TYPE_AZURE"
    deployment_type_k3_s = "DEPLOYMENT_TYPE_K3S"
    deployment_type_aws = "DEPLOYMENT_TYPE_AWS"
    deployment_type_k3_s_azure = "DEPLOYMENT_TYPE_K3S_AZURE"
    deployment_type_k3_s_aws = "DEPLOYMENT_TYPE_K3S_AWS"
    deployment_type_vmware_vce = "DEPLOYMENT_TYPE_VMWARE_VCE"
    deployment_type_vmware_tkg_attach = "DEPLOYMENT_TYPE_VMWARE_TKG_ATTACH"
    deployment_type_docker_runtime = "DEPLOYMENT_TYPE_DOCKER_RUNTIME"


class Details(BaseModel):
    category: str | None = Field(
        default="All",
        description="UI map: AppMarketplacePage:AppCard:DescriptionField, AppEditPage:IdentityPane:CategoryField, AppDetailsPage:IdentityPane:CategoryField",
        title="Type of the Edge application",
    )
    os: str | None = Field(default=None, title="Edge application's Operating System")
    app_category: AppCategory = Field(..., alias="appCategory")
    logo: dict[str, str] | None = Field(
        default=None,
        description="UI map: AppEditPage:IdentityPane:Logo, AppDetailsPage:IdentityPane:Logo",
        title="App Logo",
    )
    screenshot_list: dict[str, str] | None = Field(
        default=None,
        alias="screenshotList",
        description="UI map: AppEditPage:IdentityPane:Screenshot_Fields, AppDetailsPage:IdentityPane:Screenshot_Fields",
        title="App Screenshots",
    )
    license_list: dict[str, str] | None = Field(
        default=None,
        alias="licenseList",
        description="UI map: AppMarketplacePage:AppCard:License, AppEditPage:IdentityPane:License, AppDetailsPage:IdentityPane:License",
        title="App Licenses",
    )
    support: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DeveloperPane:Support_Description_Field, AppDetailsPage:DeveloperPane:Support_Description_Field",
        title="Support Description",
    )
    agreement_list: dict[str, str] | None = Field(
        default=None,
        alias="agreementList",
        description="UI map: AppEditPage:DeveloperPane:Developer_Agreement_Field, AppDetailsPage:DeveloperPane:Developer_Agreement_Field",
        title="Developer Agreements",
    )


class DockerRuntimeProtocolVersion(Enum):
    runtime_protocol_version_unknown = "RuntimeProtocolVersion_Unknown"
    runtime_protocol_version_v1 = "RuntimeProtocolVersion_V1"


class DockerRuntimeVersion(Enum):
    runtime_version_unknown = "RuntimeVersion_Unknown"
    runtime_version_v1 = "RuntimeVersion_V1"


class ImageDatastore(BaseModel):
    id: str | None = Field(default=None, description="Datastore ID")
    name: str | None = Field(default=None, description="Datastore Name")


class IoType(Enum):
    io_type_unspecified = "IO_TYPE_UNSPECIFIED"
    io_type_eth = "IO_TYPE_ETH"
    io_type_usb = "IO_TYPE_USB"
    io_type_com = "IO_TYPE_COM"
    io_type_audio = "IO_TYPE_AUDIO"
    io_type_wlan = "IO_TYPE_WLAN"
    io_type_wwan = "IO_TYPE_WWAN"
    io_type_hdmi = "IO_TYPE_HDMI"
    io_type_lte = "IO_TYPE_LTE"
    io_type_storage_nvme_device = "IO_TYPE_STORAGE_NVME_DEVICE"
    io_type_storage_sata_device = "IO_TYPE_STORAGE_SATA_DEVICE"
    io_type_eth_pf = "IO_TYPE_ETH_PF"
    io_type_eth_vf = "IO_TYPE_ETH_VF"
    io_type_usb_controller = "IO_TYPE_USB_CONTROLLER"
    io_type_usb_device = "IO_TYPE_USB_DEVICE"
    io_type_can = "IO_TYPE_CAN"
    io_type_vcan = "IO_TYPE_VCAN"
    io_type_lcan = "IO_TYPE_LCAN"
    io_type_vlan = "IO_TYPE_VLAN"
    io_type_other = "IO_TYPE_OTHER"


class LimitParams(BaseModel):
    limitrate: int | None = Field(
        default=None,
        description="UI map: AppDetailsPage:EnvironmentsPane, AppDetailsPage:EnvironmentsPane",
        title="Rate limit in ACL rule",
    )
    limitunit: str | None = Field(
        default=None,
        description="UI map: AppDetailsPage:EnvironmentsPane, AppDetailsPage:EnvironmentsPane",
        title="Rate limit unit in ACL rule",
    )
    limitburst: int | None = Field(
        default=None,
        description="UI map: AppDetailsPage:EnvironmentsPane, AppDetailsPage:EnvironmentsPane",
        title="Rate limit burst in ACL rule",
    )


class LispServer(BaseModel):
    name_or_ip: str = Field(..., alias="nameOrIp", description="name/IP")
    credential: str = Field(..., description="lisp credential")


class MapParams(BaseModel):
    app_port: int | None = Field(
        default=None, alias="appPort", description="Application Port value"
    )


class Match(BaseModel):
    type: str | None = Field(
        default=None,
        description="Type of Match (Required)",
        title="enum: host, protocol, adapter\nAt the device level it will pick right interface to apply this match",
    )
    value: str | None = Field(default=None, description="Value of match (Required)")


class ModuleType(Enum):
    module_type_unspecified = "MODULE_TYPE_UNSPECIFIED"
    module_type_system_defined = "MODULE_TYPE_SYSTEM_DEFINED"
    module_type_custom = "MODULE_TYPE_CUSTOM"
    module_type_azure_edge_agent = "MODULE_TYPE_AZURE_EDGE_AGENT"
    module_type_azure_edge_hub = "MODULE_TYPE_AZURE_EDGE_HUB"


class NetworkInstanceDhcpType(Enum):
    network_instance_dhcp_type_unspecified = "NETWORK_INSTANCE_DHCP_TYPE_UNSPECIFIED"
    network_instance_dhcp_type_v4 = "NETWORK_INSTANCE_DHCP_TYPE_V4"
    network_instance_dhcp_type_v6 = "NETWORK_INSTANCE_DHCP_TYPE_V6"
    network_instance_dhcp_type_cryptoeid = "NETWORK_INSTANCE_DHCP_TYPE_CRYPTOEID"
    network_instance_dhcp_type_cryptov4 = "NETWORK_INSTANCE_DHCP_TYPE_CRYPTOV4"
    network_instance_dhcp_type_cryptov6 = "NETWORK_INSTANCE_DHCP_TYPE_CRYPTOV6"


class NetworkInstanceKind(Enum):
    network_instance_kind_unspecified = "NETWORK_INSTANCE_KIND_UNSPECIFIED"
    network_instance_kind_transparent = "NETWORK_INSTANCE_KIND_TRANSPARENT"
    network_instance_kind_switch = "NETWORK_INSTANCE_KIND_SWITCH"
    network_instance_kind_local = "NETWORK_INSTANCE_KIND_LOCAL"
    network_instance_kind_cloud = "NETWORK_INSTANCE_KIND_CLOUD"
    network_instance_kind_mesh = "NETWORK_INSTANCE_KIND_MESH"
    network_instance_kind_honeypot = "NETWORK_INSTANCE_KIND_HONEYPOT"


class NtpServer(BaseModel):
    server: str | None = Field(default=None, description="NTP Server IP or FQDN")


class ObjectType(Enum):
    object_type_unspecified = "OBJECT_TYPE_UNSPECIFIED"
    object_type_user = "OBJECT_TYPE_USER"
    object_type_edge_node = "OBJECT_TYPE_EDGE_NODE"
    object_type_edge_app = "OBJECT_TYPE_EDGE_APP"
    object_type_image = "OBJECT_TYPE_IMAGE"
    object_type_edge_app_instance = "OBJECT_TYPE_EDGE_APP_INSTANCE"
    object_type_project = "OBJECT_TYPE_PROJECT"
    object_type_network = "OBJECT_TYPE_NETWORK"
    object_type_datastore = "OBJECT_TYPE_DATASTORE"
    object_type_service = "OBJECT_TYPE_SERVICE"
    object_type_service_instance = "OBJECT_TYPE_SERVICE_INSTANCE"
    object_type_enterprise = "OBJECT_TYPE_ENTERPRISE"
    object_type_role = "OBJECT_TYPE_ROLE"
    object_type_credential = "OBJECT_TYPE_CREDENTIAL"
    object_type_network_instance = "OBJECT_TYPE_NETWORK_INSTANCE"
    object_type_volume_instance = "OBJECT_TYPE_VOLUME_INSTANCE"
    object_type_realm = "OBJECT_TYPE_REALM"
    object_type_authprofile = "OBJECT_TYPE_AUTHPROFILE"
    object_type_policy = "OBJECT_TYPE_POLICY"
    object_type_app_policy = "OBJECT_TYPE_APP_POLICY"
    object_type_cluster_instance = "OBJECT_TYPE_CLUSTER_INSTANCE"
    object_type_plugin = "OBJECT_TYPE_PLUGIN"
    object_type_doc_policy = "OBJECT_TYPE_DOC_POLICY"
    object_type_orchestrator_cluster = "OBJECT_TYPE_ORCHESTRATOR_CLUSTER"
    object_type_tags = "OBJECT_TYPE_TAGS"
    object_type_edge_node_interface = "OBJECT_TYPE_EDGE_NODE_INTERFACE"
    object_type_deployment = "OBJECT_TYPE_DEPLOYMENT"
    object_type_entitlements = "OBJECT_TYPE_ENTITLEMENTS"
    object_type_data_stream = "OBJECT_TYPE_DATA_STREAM"
    object_type_api_usage = "OBJECT_TYPE_API_USAGE"
    object_type_app_instance_snapshot = "OBJECT_TYPE_APP_INSTANCE_SNAPSHOT"
    object_type_patch_envelope = "OBJECT_TYPE_PATCH_ENVELOPE"
    object_type_resource_usage_track = "OBJECT_TYPE_RESOURCE_USAGE_TRACK"
    object_type_patch_envelope_reference = "OBJECT_TYPE_PATCH_ENVELOPE_REFERENCE"
    object_type_dev_passthrough = "OBJECT_TYPE_DEV_PASSTHROUGH"
    object_type_edge_node_cluster = "OBJECT_TYPE_EDGE_NODE_CLUSTER"
    object_type_asset_group = "OBJECT_TYPE_ASSET_GROUP"
    object_type_app_profile = "OBJECT_TYPE_APP_PROFILE"
    object_type_profile_deployment = "OBJECT_TYPE_PROFILE_DEPLOYMENT"
    object_type_zks_instance = "OBJECT_TYPE_ZKS_INSTANCE"
    object_type_cluster_group = "OBJECT_TYPE_CLUSTER_GROUP"


class OpaqueConfigType(Enum):
    opaque_config_type_unspecified = "OPAQUE_CONFIG_TYPE_UNSPECIFIED"
    opaque_config_type_vpn = "OPAQUE_CONFIG_TYPE_VPN"
    opaque_config_type_lisp = "OPAQUE_CONFIG_TYPE_LISP"


class Param(BaseModel):
    name: str | None = Field(
        default=None, description="Name of the Parameter (Required)"
    )
    value: str | None = Field(
        default=None, description="Value of the parameter (Required)"
    )


class Permission(BaseModel):
    pass


class ProfileDeploymentFilter(BaseModel):
    profile_deployment_id: (
        constr(pattern=r"[a-zA-Z0-9][a-zA-Z0-9_.-]+", min_length=3, max_length=256)
        | None
    ) = Field(
        default=None,
        alias="profileDeploymentId",
        description="Unique id of the asset, unique across the enterprise.",
    )
    name_pattern: str | None = Field(
        default=None, alias="namePattern", description="deployment name pattern"
    )


class ProfilePolicyCommon(BaseModel):
    id: str | None = Field(default=None, description="unique id for an policy")
    name: str | None = Field(default=None, description="user defined policy name")
    title: str | None = Field(default=None, description="user defined policy title")
    tags: dict[str, str] | None = Field(
        default=None, description="user defined key-value pairs of a policy"
    )


class Resource(BaseModel):
    name: str | None = Field(
        default=None, description="Name of the Resource (Required)"
    )
    value: str | None = Field(default=None, description="Value of Resource (Required)")


class RunState(Enum):
    run_state_unspecified = "RUN_STATE_UNSPECIFIED"
    run_state_online = "RUN_STATE_ONLINE"
    run_state_halted = "RUN_STATE_HALTED"
    run_state_init = "RUN_STATE_INIT"
    run_state_rebooting = "RUN_STATE_REBOOTING"
    run_state_offline = "RUN_STATE_OFFLINE"
    run_state_unknown = "RUN_STATE_UNKNOWN"
    run_state_unprovisioned = "RUN_STATE_UNPROVISIONED"
    run_state_provisioned = "RUN_STATE_PROVISIONED"
    run_state_suspect = "RUN_STATE_SUSPECT"
    run_state_downloading = "RUN_STATE_DOWNLOADING"
    run_state_restarting = "RUN_STATE_RESTARTING"
    run_state_purging = "RUN_STATE_PURGING"
    run_state_halting = "RUN_STATE_HALTING"
    run_state_error = "RUN_STATE_ERROR"
    run_state_verifying = "RUN_STATE_VERIFYING"
    run_state_loading = "RUN_STATE_LOADING"
    run_state_creating_volume = "RUN_STATE_CREATING_VOLUME"
    run_state_booting = "RUN_STATE_BOOTING"
    run_state_maintenance_mode = "RUN_STATE_MAINTENANCE_MODE"
    run_state_start_delayed = "RUN_STATE_START_DELAYED"
    run_state_baseos_updating = "RUN_STATE_BASEOS_UPDATING"
    run_state_preparing_poweroff = "RUN_STATE_PREPARING_POWEROFF"
    run_state_powering_off = "RUN_STATE_POWERING_OFF"
    run_state_prepared_poweroff = "RUN_STATE_PREPARED_POWEROFF"


class StaticDNSList(BaseModel):
    hostname: str | None = Field(default=None, description="Host name")
    addrs: list[str] | None = Field(default=None, description="Addresses")


class Summary(BaseModel):
    description: str | None = Field(default=None, description="Summary description")
    total: float | None = Field(default=None, description="Total")
    values: dict[str, int] | None = Field(
        default=None, description="Values: Map for storing <string, uint32>"
    )


class TargetAssetGroup(BaseModel):
    group_id: (
        constr(
            pattern=r"[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
        )
        | None
    ) = Field(
        default=None, alias="groupId", description="unique Id of the asset group."
    )


class VariableFileEncoding(Enum):
    file_encoding_unspecified = "FILE_ENCODING_UNSPECIFIED"
    file_encoding_base64 = "FILE_ENCODING_BASE64"


class VariableGroupConditionOperator(Enum):
    condition_operator_unspecified = "CONDITION_OPERATOR_UNSPECIFIED"
    condition_operator_equalto = "CONDITION_OPERATOR_EQUALTO"
    condition_operator_notequalto = "CONDITION_OPERATOR_NOTEQUALTO"


class VariableOptionVal(BaseModel):
    label: str | None = Field(
        default=None, description="Display label of the key in User-Agent"
    )
    value: str | None = Field(default=None, description="Value of the key to be used")


class VariableVariableFormat(Enum):
    variable_format_unspecified = "VARIABLE_FORMAT_UNSPECIFIED"
    variable_format_text = "VARIABLE_FORMAT_TEXT"
    variable_format_number = "VARIABLE_FORMAT_NUMBER"
    variable_format_file = "VARIABLE_FORMAT_FILE"
    variable_format_dropdown = "VARIABLE_FORMAT_DROPDOWN"
    variable_format_boolean = "VARIABLE_FORMAT_BOOLEAN"
    variable_format_password = "VARIABLE_FORMAT_PASSWORD"


class VmBootloaderMode(Enum):
    vm_bootloader_mode_unspecified = "VM_BOOTLOADER_MODE_UNSPECIFIED"
    vm_bootloader_mode_legacy = "VM_BOOTLOADER_MODE_LEGACY"
    vm_bootloader_mode_uefi = "VM_BOOTLOADER_MODE_UEFI"


class VolumeInstanceAccessMode(Enum):
    volume_instance_access_mode_invalid = "VOLUME_INSTANCE_ACCESS_MODE_INVALID"
    volume_instance_access_mode_readwrite = "VOLUME_INSTANCE_ACCESS_MODE_READWRITE"
    volume_instance_access_mode_readonly = "VOLUME_INSTANCE_ACCESS_MODE_READONLY"
    volume_instance_access_mode_multiread_singlewrite = (
        "VOLUME_INSTANCE_ACCESS_MODE_MULTIREAD_SINGLEWRITE"
    )


class VolumeInstanceType(Enum):
    volume_instance_type_unspecified = "VOLUME_INSTANCE_TYPE_UNSPECIFIED"
    volume_instance_type_emptydir = "VOLUME_INSTANCE_TYPE_EMPTYDIR"
    volume_instance_type_blockstorage = "VOLUME_INSTANCE_TYPE_BLOCKSTORAGE"
    volume_instance_type_hostfs = "VOLUME_INSTANCE_TYPE_HOSTFS"
    volume_instance_type_tmpfs = "VOLUME_INSTANCE_TYPE_TMPFS"
    volume_instance_type_secret = "VOLUME_INSTANCE_TYPE_SECRET"
    volume_instance_type_nfs = "VOLUME_INSTANCE_TYPE_NFS"
    volume_instance_type_aws_block_storage = "VOLUME_INSTANCE_TYPE_AWS_BLOCK_STORAGE"
    volume_instance_type_content_tree = "VOLUME_INSTANCE_TYPE_CONTENT_TREE"


class ZcOpsStatus(Enum):
    ops_status_unspecified = "OPS_STATUS_UNSPECIFIED"
    ops_status_pending = "OPS_STATUS_PENDING"
    ops_status_ongoing = "OPS_STATUS_ONGOING"
    ops_status_complete = "OPS_STATUS_COMPLETE"


class ZcOpsType(Enum):
    ops_type_unspecified = "OPS_TYPE_UNSPECIFIED"
    ops_type_read = "OPS_TYPE_READ"
    ops_type_delete = "OPS_TYPE_DELETE"
    ops_type_create = "OPS_TYPE_CREATE"
    ops_type_update = "OPS_TYPE_UPDATE"
    ops_type_list = "OPS_TYPE_LIST"


class ZedCloudOpsCmd(BaseModel):
    counter: float | None = Field(default=None, description="counter")
    ops_time: dict[str, Any] | None = Field(
        default=None, alias="opsTime", description="Timestamp: Operational time"
    )


class ZsrvErrorCode(Enum):
    z_msg_error_none = "zMsgErrorNone"
    z_msg_sucess = "zMsgSucess"
    not_found = "NotFound"
    already_exists = "AlreadyExists"
    version_mismatch = "VersionMismatch"
    range_error = "RangeError"
    large_result = "LargeResult"
    incomplete_data = "IncompleteData"
    invalid_data = "InvalidData"
    function_unsupported = "FunctionUnsupported"
    no_memory = "NoMemory"
    send_failure = "SendFailure"
    timeout = "Timeout"
    bad_req_body = "BadReqBody"
    bad_req_param = "BadReqParam"
    invalid_field_format = "InvalidFieldFormat"
    url_not_found = "UrlNotFound"
    api_version_not_supported = "ApiVersionNotSupported"
    unauthorized = "Unauthorized"
    forbidden = "Forbidden"
    conflict = "Conflict"
    not_modified = "NotModified"
    dependency_conflict = "DependencyConflict"
    json_fmt_error = "JsonFmtError"
    proto_fmt_error = "ProtoFmtError"
    cert_error = "CertError"
    data_base_connection = "DataBaseConnection"
    db_error = "DBError"
    z_msg_accepted = "zMsgAccepted"
    z_msg_created = "zMsgCreated"
    pre_condition_failed = "PreConditionFailed"
    internal_server_error = "InternalServerError"


class AppACEMatch(BaseModel):
    type: str = Field(..., description="Type")
    value: str = Field(..., description="Value")


class AppMapParams(BaseModel):
    port: float = Field(..., description="Application port")


class CommonConnectivityProbeMethod(Enum):
    connectivity_probe_method_unspecified = "CONNECTIVITY_PROBE_METHOD_UNSPECIFIED"
    connectivity_probe_method_icmp = "CONNECTIVITY_PROBE_METHOD_ICMP"
    connectivity_probe_method_tcp = "CONNECTIVITY_PROBE_METHOD_TCP"


class CommonProbeEndpoint(BaseModel):
    host: str | None = Field(default=None, description="IP address or FQDN.")
    port: int | None = Field(
        default=None,
        description="TCP port required for CONNECTIVITY_PROBE_METHOD_TCP.\nLeave empty for CONNECTIVITY_PROBE_METHOD_ICMP.",
    )


class ConfigFormat(Enum):
    fmt_unknown = "FmtUnknown"
    raw = "RAW"
    qcow = "QCOW"
    qcow2 = "QCOW2"
    vhd = "VHD"
    vmdk = "VMDK"
    ova = "OVA"
    vhdx = "VHDX"
    container = "CONTAINER"
    iso = "ISO"
    pvc = "PVC"


class DhcpIpRange(BaseModel):
    start: str | None = Field(default=None, description="starting IP")
    end: str | None = Field(default=None, description="ending IP")


class HvMode(Enum):
    hv_pv = "HV_PV"
    hv_hvm = "HV_HVM"
    hv_fml = "HV_FML"
    hv_nohyper = "HV_NOHYPER"
    hv_legacy = "HV_LEGACY"


class PhyAdapter(BaseModel):
    type: IoType | None = "IO_TYPE_UNSPECIFIED"
    name: str | None = Field(default=None, description="Physical Adapter name")
    tags: dict[str, str] | None = Field(
        default=None,
        description="Tags are name/value pairs that enable you to categorize resources. Tag names are case insensitive with max_length 512 and min_length 3. Tag values are case sensitive with max_length 256 and min_length 3.",
    )


class ProtobufAny(BaseModel):
    type_url: str | None = Field(default=None, alias="typeUrl")
    value: Base64Str | None = None


class SpType(Enum):
    sptype_invalidsrv = "SPTYPE_INVALIDSRV"
    sptype_mapserver = "SPTYPE_MAPSERVER"
    sptype_supportserver = "SPTYPE_SUPPORTSERVER"


class Vm(BaseModel):
    cpus: float = Field(..., description="CPUs")
    memory: float = Field(..., description="Memory")
    mode: HvMode
    vnc: bool = Field(..., description="VNC")
    vnc_display: float | None = Field(
        default=None, alias="vncDisplay", description="VNC display"
    )
    cpu_pinning_enabled: bool | None = Field(
        default=None, alias="cpuPinningEnabled", description="Enable CpuPinning"
    )
    vmm_maxmem: int | None = Field(
        default=None,
        alias="vmmMaxmem",
        description="Maximum amount of memory in kbytes allowed for VM monitor to occupy",
    )
    bootloader_mode: VmBootloaderMode | None = Field(
        default="VM_BOOTLOADER_MODE_UNSPECIFIED", alias="bootloaderMode"
    )
    enable_oem_win_license_key: bool | None = Field(
        default=None,
        alias="enableOemWinLicenseKey",
        description="Enable device which has VM to receive the Windows license embedded in the ACPI tables",
    )
    disable_vtpm: bool | None = Field(
        default=None,
        alias="disableVTPM",
        description="Disable vTPM for virtual machines (VM)",
    )


class AclAction(BaseModel):
    drop: bool | None = Field(
        default=None, description="Drop the packet", title="Not used by ZedUI"
    )
    limit: bool | None = Field(
        default=None,
        description="UI map: AppDetailsPage:EnvironmentsPane, AppDetailsPage:EnvironmentsPane",
        title="Limit action on ACL rule",
    )
    limit_value: LimitParams | None = Field(default=None, alias="limitValue")
    limitrate: int | None = Field(
        default=None,
        description="UI map: AppDetailsPage:EnvironmentsPane, AppDetailsPage:EnvironmentsPane",
        title="Rate limit in ACL rule",
    )
    limitunit: str | None = Field(
        default=None,
        description="UI map: AppDetailsPage:EnvironmentsPane, AppDetailsPage:EnvironmentsPane",
        title="Rate limit unit in ACL rule",
    )
    limitburst: int | None = Field(
        default=None,
        description="UI map: AppDetailsPage:EnvironmentsPane, AppDetailsPage:EnvironmentsPane",
        title="Rate limit burst in ACL rule",
    )
    portmap: bool | None = Field(
        default=None,
        description="UI map: AppDetailsPage:EnvironmentsPane, AppDetailsPage:EnvironmentsPane",
        title="Enable device to app port mapping for incoming ACL rule, implicitly added by ZedUI code",
    )
    portmapto: MapParams | None = None


class AssetGroup(BaseModel):
    id: (
        constr(
            pattern=r"[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
        )
        | None
    ) = Field(default=None, description="unique Id of the asset group.")
    name: constr(
        pattern=r"[a-zA-Z0-9][a-zA-Z0-9_.-]+", min_length=3, max_length=256
    ) = Field(
        ...,
        description="User defined name of the asset group, unique across the enterprise. Once asset group is created, name can’t be changed.",
    )
    title: (
        constr(pattern=r"[a-zA-Z0-9]+[a-zA-Z0-9!-~ ]+", min_length=3, max_length=256)
        | None
    ) = Field(
        default=None,
        description="User defined title of the asset group. Title can be changed at any time.",
    )
    description: constr(max_length=256) | None = Field(
        default=None, description="Detailed description of the asset group."
    )
    project_id: str | None = Field(
        default=None, alias="projectId", description="project id"
    )
    asset_ids: AssetIDs | None = Field(default=None, alias="assetIds")
    asset_tags: AssetTags | None = Field(default=None, alias="assetTags")


class AssetGroupList(BaseModel):
    next: Cursor | None = None
    list_: list[AssetGroup] | None = Field(
        default=None, alias="list", description="asset group summary list"
    )
    total_count: int | None = Field(
        default=None, alias="totalCount", description="asset group total count"
    )


class AssetGroupRead(BaseModel):
    id: (
        constr(
            pattern=r"[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
        )
        | None
    ) = Field(default=None, description="unique Id of the asset group.")
    name: (
        constr(pattern=r"[a-zA-Z0-9][a-zA-Z0-9_.-]+", min_length=3, max_length=256)
        | None
    ) = Field(
        default=None,
        description="User defined name of the asset group, unique across the enterprise. Once asset group is created, name can’t be changed.",
    )
    title: (
        constr(pattern=r"[a-zA-Z0-9]+[a-zA-Z0-9!-~ ]+", min_length=3, max_length=256)
        | None
    ) = Field(
        default=None,
        description="User defined title of the asset group. Title can be changed at any time.",
    )
    description: constr(max_length=256) | None = Field(
        default=None, description="Detailed description of the asset group."
    )
    project_id: str | None = Field(
        default=None, alias="projectId", description="project id"
    )
    asset_ids: AssetIDs | None = Field(default=None, alias="assetIds")
    asset_tags: AssetTags | None = Field(default=None, alias="assetTags")
    asset_count: int | None = Field(default=None, alias="assetCount")


class DhcpServerConfig(BaseModel):
    subnet: str | None = Field(default=None, description="Subnet address")
    mask: str | None = Field(default=None, description="Subnet Mask")
    gateway: str | None = Field(
        default=None, description="IP Address of Network Gateway"
    )
    domain: str | None = Field(default=None, description="Network domain")
    ntp: str | None = Field(
        default=None,
        description="IP Address of NTP Server",
        title="ntp will be deprecated",
    )
    dns: list[str] | None = Field(
        default=None,
        description="IP Addresses of DNS servers",
        title="possible DNS ip address",
    )
    dhcp_range: DhcpIpRange | None = Field(default=None, alias="dhcpRange")
    ntp_servers: list[NtpServer] | None = Field(
        default=None, alias="ntpServers", description="NTP Servers"
    )


class EIDRegister(BaseModel):
    app_cert: Base64Str = Field(..., alias="AppCert", description="app certificate")
    app_public_key: Base64Str = Field(
        ..., alias="AppPublicKey", description="App public key"
    )
    app_private_key: Base64Str = Field(
        ..., alias="AppPrivateKey", description="App private key"
    )
    uuid: str = Field(..., alias="UUID", description="UUID")
    display_name: str = Field(..., alias="DisplayName", description="Display name")
    lisp_instance: float = Field(..., alias="LispInstance", description="Lisp Instance")
    eid: str = Field(..., alias="EID", description="EID")
    eid_hash_len: float = Field(..., alias="EIDHashLen", description="EID hash length")
    lisp_signature: str = Field(
        ..., alias="LispSignature", description="Lisp Signature"
    )
    lisp_map_servers: list[LispServer] = Field(
        ...,
        alias="LispMapServers",
        description="Lisp Map Server",
        title="time CreateTime     time.Time",
    )


class ModuleDetail(BaseModel):
    twin_detail: str | None = Field(
        default=None,
        alias="twinDetail",
        description="Base64 encoded module twin details, desired properties of the module will be updated to reflect these values",
    )
    routes: dict[str, str] | None = Field(
        default=None,
        description="Send messages between modules or send messages from modules to iot hub",
    )
    environment: dict[str, str] | None = Field(
        default=None,
        description="Extra information to module to make configuration easier",
    )
    module_type: ModuleType | None = Field(
        default="MODULE_TYPE_UNSPECIFIED", alias="moduleType"
    )


class ProfileDeployment(BaseModel):
    id: (
        constr(
            pattern=r"[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
        )
        | None
    ) = Field(default=None, description="unique Id of the deployment.")
    name: constr(
        pattern=r"[a-zA-Z0-9][a-zA-Z0-9_.-]+", min_length=3, max_length=256
    ) = Field(
        ...,
        description="User defined name of the deployment, unique across the enterprise. Once deployment is created, name can’t be changed.",
    )
    title: (
        constr(pattern=r"[a-zA-Z0-9]+[a-zA-Z0-9!-~ ]+", min_length=3, max_length=256)
        | None
    ) = Field(
        default=None,
        description="User defined title of the deployment. Title can be changed at any time.",
    )
    description: constr(max_length=256) | None = Field(
        default=None, description="Detailed description of the deployment."
    )
    project_id: str = Field(..., alias="projectId", description="project id")
    app_profile_info: AppProfileInfo = Field(..., alias="appProfileInfo")
    target_asset_group: TargetAssetGroup = Field(..., alias="targetAssetGroup")
    status: str | None = None


class ProfileDeploymentList(BaseModel):
    next: Cursor | None = None
    list_: list[ProfileDeployment] | None = Field(
        default=None, alias="list", description="deployment summary list"
    )


class ProfileDeploymentResourceObjectStatus(BaseModel):
    id: (
        constr(
            pattern=r"[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
        )
        | None
    ) = Field(default=None, description="Unique ID of the object.")
    object_type: ObjectType | None = Field(
        default="OBJECT_TYPE_UNSPECIFIED", alias="objectType"
    )
    object_run_state: RunState | None = Field(
        default="RUN_STATE_UNSPECIFIED", alias="objectRunState"
    )
    job_id: str | None = Field(
        default=None,
        alias="jobId",
        description="Job ID associated with the object creation. Only applicable for EdgeAppInstance objects.",
    )
    error_message: str | None = Field(
        default=None,
        alias="errorMessage",
        description="Error message if the object creation or operation failed.",
    )


class ProfileVolumeConfig(BaseModel):
    type: VolumeInstanceType | None = "VOLUME_INSTANCE_TYPE_UNSPECIFIED"
    multiattach: bool | None = Field(
        default=None,
        description="flag to enable the volume to be attached to multiple app instances",
    )
    cleartext: bool | None = Field(
        default=None,
        description="flag to keep the contents of the volume unencrypted (in clear text)",
    )
    accessmode: VolumeInstanceAccessMode | None = "VOLUME_INSTANCE_ACCESS_MODE_INVALID"
    size_bytes: int | None = Field(
        default=None, alias="sizeBytes", description="size of volume"
    )
    image: str | None = Field(default=None, description="name of the image")
    content_tree_id: str | None = Field(
        default=None, alias="contentTreeId", description="content tree ID"
    )
    label: str | None = Field(default=None, description="label")
    purge: ZedCloudOpsCmd | None = None
    content_tree_target_condition: dict[str, str] | None = Field(
        default=None,
        alias="contentTreeTargetCondition",
        description="user defined key-value pairs of a content tree that will be used for targeting by block storage",
    )
    block_storage_tags: dict[str, str] | None = Field(
        default=None,
        alias="blockStorageTags",
        description="user defined key-value pairs of a block storage, will be used for targeting content tree",
    )


class ProfileVolumePolicy(BaseModel):
    meta_data: ProfilePolicyCommon | None = Field(default=None, alias="metaData")
    volume_config: ProfileVolumeConfig | None = Field(
        default=None, alias="volumeConfig"
    )


class ServicePoint(BaseModel):
    type: SpType | None = "SPTYPE_INVALIDSRV"
    name_or_ip: str | None = Field(
        default=None, alias="NameOrIp", description="Service name/ service name"
    )
    credential: str | None = Field(
        default=None, alias="Credential", description="Service credentials"
    )


class VMManifestImage(BaseModel):
    imagename: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:Image_Name_Field, AppDetailsPage:DrivesPane:Image_Name_Field",
    )
    imageid: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:Image_ID_Field, AppDetailsPage:DrivesPane:Image_ID_Field",
    )
    imageformat: ConfigFormat | None = "FmtUnknown"
    maxsize: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:Max_Size_Field, AppDetailsPage:DrivesPane:Max_Size_Field",
    )
    preserve: bool | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:Preserve_Field, AppDetailsPage:DrivesPane:Preserve_Field",
    )
    target: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:Target_Field, AppDetailsPage:DrivesPane:Target_Field",
        title="enum: Disk, Kernel, Initrd, RamDisk",
    )
    drvtype: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:Drive_Type_Field, AppDetailsPage:DrivesPane:Drive_Type_Field",
        title="enum: CDROM, HDD, NET",
    )
    params: list[Param] | None = Field(default=None, title="Not used by ZedUI")
    readonly: bool | None = Field(default=None, title="Not used by ZedUI")
    volumelabel: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:Volume_Label, AppDetailsPage:DrivesPane:Volume_Label",
    )
    ignorepurge: bool | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:Ignorepurge, AppDetailsPage:DrivesPane:Ignorepurgee_Field",
    )
    cleartext: bool | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:Cleartext, AppDetailsPage:DrivesPane:ClearText_Field",
    )
    mountpath: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:Mountpath, AppDetailsPage:DrivesPane:Mountpath_Field",
    )
    imagestatus: str | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:Image_Status_Field, AppDetailsPage:DrivesPane:Image_Status_Field",
        title="enum: UNSPECIFIED, CREATED, PENDING, UPLOADING, READY, INUSE, ARCHIVED, MAX, FAILED, UPLINKING",
    )
    datastore: list[ImageDatastore] | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane:DataStore_Field, AppDetailsPage:DrivesPane:DataStore_Field",
    )


class VariableGroupCondition(BaseModel):
    name: str | None = None
    value: str | None = None
    operator: VariableGroupConditionOperator | None = "CONDITION_OPERATOR_UNSPECIFIED"


class VariableGroupVariable(BaseModel):
    type: str | None = None
    name: str = Field(..., description="Name of the Variable (Required)")
    label: str = Field(..., description="Label for the variable (Required)")
    max_length: str | None = Field(
        default=None,
        alias="maxLength",
        description="Max length of the value of the variable(Optional. Default: 1024)",
    )
    required: bool = Field(
        ...,
        description="This variable MUST be specified when creating an App Instance. (Optional. Default: False)",
    )
    default: str | None = Field(
        default=None,
        description="Default value of the variable. (Optional. Default: <Default value based on type>)",
    )
    process_input: str | None = Field(default=None, alias="processInput")
    value: str | None = Field(
        default=None,
        description="User-specified value of the variable.(Required if required is true. Optional otherwise)",
    )
    format: VariableVariableFormat
    encode: VariableFileEncoding | None = "FILE_ENCODING_UNSPECIFIED"
    options: list[VariableOptionVal] | None = Field(
        default=None,
        description="Key-Value pair of options. Applicable if format is VARIABLE_FORMAT_DROPDOWN",
    )


class ZsrvError(BaseModel):
    ec: ZsrvErrorCode | None = "zMsgErrorNone"
    location: str | None = Field(default=None, title="Ignore: Internal field only")
    details: str | None = Field(
        default=None, title="Field captures string description of details"
    )


class ZsrvResponse(BaseModel):
    operation_type: ZcOpsType | None = Field(
        default="OPS_TYPE_UNSPECIFIED", alias="operationType"
    )
    operation_status: ZcOpsStatus | None = Field(
        default="OPS_STATUS_UNSPECIFIED", alias="operationStatus"
    )
    object_kind: str | None = Field(
        default=None,
        alias="objectKind",
        title="zedcloud object kind on which the operation was performed",
    )
    object_id: str | None = Field(
        default=None,
        alias="objectId",
        title="Unique value identifies the object that was operated on",
    )
    object_name: str | None = Field(
        default=None, alias="objectName", title="name of the object"
    )
    object_revision: str | None = Field(
        default=None,
        alias="objectRevision",
        title="object revision post the operation, note Read operation\ndoesn't change the revision",
    )
    object_type: ObjectType | None = Field(
        default="OBJECT_TYPE_UNSPECIFIED", alias="objectType"
    )
    operation_time: str | None = Field(
        default=None, alias="operationTime", title="time of operation"
    )
    start_time: str | None = Field(
        default=None, alias="startTime", title="total time taken by operations"
    )
    end_time: str | None = Field(default=None, alias="endTime")
    user: str | None = Field(
        default=None, title="the operation is performed on behalf of this user"
    )
    http_status_code: int | None = Field(
        default=None, alias="httpStatusCode", title="http response"
    )
    http_status_msg: str | None = Field(
        default=None, alias="httpStatusMsg", title="summary of the error in text format"
    )
    job_id: str | None = Field(
        default=None, alias="jobId", title="for tracking asynchronous tasks"
    )
    error: list[ZsrvError] | None = Field(
        default=None,
        title="one or more errors will be set if the operation failed\ni.e. httpStatusCode != 2xx",
    )


class AppACEAction(BaseModel):
    drop: bool = Field(..., description="ACE drop flag")
    limit: bool = Field(..., description="ACE limit flag")
    limitrate: float = Field(..., description="ACE limit rate")
    limitunit: str = Field(..., description="ACE limit unit")
    limitburst: float = Field(..., description="ACE limit burst")
    portmap: bool = Field(..., description="application port map flag")
    mapparams: AppMapParams


class CommonConnectivityProbe(BaseModel):
    probe_method: CommonConnectivityProbeMethod | None = Field(
        default="CONNECTIVITY_PROBE_METHOD_UNSPECIFIED", alias="probeMethod"
    )
    probe_endpoint: CommonProbeEndpoint | None = Field(
        default=None, alias="probeEndpoint"
    )


class GooglerpcStatus(BaseModel):
    code: int | None = None
    message: str | None = None
    details: list[ProtobufAny] | None = None


class Acl(BaseModel):
    matches: list[Match] | None = Field(
        default=None,
        description="Network traffic matching criteria consistngs of one or more of source IP address, destination IP address, protocol, source port and destination port",
    )
    actions: list[AclAction] | None = Field(
        default=None,
        description="Chain of actions to be taken on matching network traffic",
    )
    name: str | None = Field(
        default=None, description="Name of the Access Control List"
    )


class CustomConfigVariableGroup(BaseModel):
    name: str | None = Field(
        default=None, description="Name of the Variable Group(Required)"
    )
    variables: list[VariableGroupVariable] | None = Field(
        default=None, description="List of variables(Required)"
    )
    required: bool | None = Field(
        default=None,
        description="Indicates if the variable group is required to be specified for the App Instance. (Optional. Default:False)",
    )
    condition: VariableGroupCondition | None = None


class Interface(BaseModel):
    name: str | None = Field(
        default=None, description="Interface name used by the edge application"
    )
    type: str | None = Field(
        default=None,
        description='Physical Adapter type for this interface. Applicable only when "direct attach" flag is true.',
    )
    optional: bool | None = Field(
        default=None,
        description="Indicates if the interface is optional for edge application.",
    )
    directattach: bool | None = Field(
        default=None,
        description="If true, a physical adapter is assigned to the edge application directly. If false, a network instance is assigned to the edge application.",
    )
    privateip: bool | None = Field(
        default=None,
        description="If true, DHCP network can't be assigned and user needs to provide a static IP address.",
    )
    acls: list[Acl] | None = Field(
        default=None,
        description='Traffic access control rules for this interface. Applicable only when "direct attach" flag is false.',
    )


class LispConfig(BaseModel):
    lispiid: float | None = Field(default=None, description="lisp id")
    allocate: bool | None = Field(default=None, description="Allocate flag")
    exportprivate: bool | None = Field(default=None, description="Export Private flag")
    allocationprefix: Base64Str | None = Field(
        default=None, description="Allocation Prefix"
    )
    allocationprefixlen: float | None = Field(
        default=None, description="Allocation Prefix Length"
    )
    sp: list[ServicePoint] | None = Field(
        default=None, description="Service Point List"
    )


class NetInstOpaqueConfig(BaseModel):
    type: OpaqueConfigType | None = "OPAQUE_CONFIG_TYPE_UNSPECIFIED"
    oconfig: str | None = Field(
        default=None, description="base64 encoded string of opaque config"
    )
    lisp: LispConfig | None = None


class ProbeConfig(BaseModel):
    enable_gateway_ping: bool | None = Field(
        default=None, alias="enableGatewayPing", description="Enable gateway ping"
    )
    ping_max_cost: float | None = Field(
        default=None, alias="pingMaxCost", description="Ping max cost"
    )
    prefer_lower_cost: bool | None = Field(
        default=None, alias="preferLowerCost", description="Prefer lower cost"
    )
    prefer_stronger_wwan_signal: bool | None = Field(
        default=None,
        alias="preferStrongerWwanSignal",
        description="Prefer stronger WWAN signal",
    )
    custom_probe_config: CommonConnectivityProbe | None = Field(
        default=None, alias="customProbeConfig"
    )


class ProfileDeploymentPerDeviceStatus(BaseModel):
    asset_id: (
        constr(
            pattern=r"[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
        )
        | None
    ) = Field(default=None, alias="assetId", description="Unique ID of the object.")
    object_status: list[ProfileDeploymentResourceObjectStatus] | None = Field(
        default=None,
        alias="objectStatus",
        description="list of status of objects created by deployment for the given asset id",
    )


class ProfileDeploymentResourceDetailedStatus(BaseModel):
    id: (
        constr(
            pattern=r"[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
        )
        | None
    ) = Field(default=None, description="unique Id of the deployment.")
    name: (
        constr(pattern=r"[a-zA-Z0-9][a-zA-Z0-9_.-]+", min_length=3, max_length=256)
        | None
    ) = Field(
        default=None,
        description="User defined name of the deployment, unique across the enterprise. Once deployment is created, name can’t be changed.",
    )
    title: (
        constr(pattern=r"[a-zA-Z0-9]+[a-zA-Z0-9!-~ ]+", min_length=3, max_length=256)
        | None
    ) = Field(
        default=None,
        description="User defined title of the deployment. Title can be changed at any time.",
    )
    description: constr(max_length=256) | None = Field(
        default=None, description="Detailed description of the deployment."
    )
    project_id: str | None = Field(
        default=None, alias="projectId", description="project id"
    )
    app_profile_info: AppProfileInfo | None = Field(
        default=None, alias="appProfileInfo"
    )
    target_asset_group: TargetAssetGroup | None = Field(
        default=None, alias="targetAssetGroup"
    )
    asset_resource_status: list[ProfileDeploymentPerDeviceStatus] | None = Field(
        default=None,
        alias="assetResourceStatus",
        description="list of status of objects created by deployment",
    )


class ProfileDeploymentResourceDetailedStatusResp(BaseModel):
    resource_status: ProfileDeploymentResourceDetailedStatus | None = Field(
        default=None, alias="resourceStatus"
    )
    next: Cursor | None = None


class StaticIPRoute(BaseModel):
    prefix: str | None = Field(default=None, description="IP Prefix")
    gateway: str | None = Field(default=None, description="Gateway IP")
    output_port: str | None = Field(
        default=None, alias="outputPort", description="Output Port"
    )
    probe_config: ProbeConfig | None = Field(default=None, alias="probeConfig")


class AppACE(BaseModel):
    matches: list[AppACEMatch] = Field(..., description="app ACE match")
    actions: list[AppACEAction] = Field(..., description="app ACE actions")
    id: float = Field(..., description="app ACE id")
    name: constr(
        pattern=r"[a-zA-Z0-9][a-zA-Z0-9_.-]+", min_length=3, max_length=256
    ) = Field(
        ...,
        description="User defined name of the app ACE, unique across the enterprise. Once object is created, name can’t be changed",
    )


class AppInterface(BaseModel):
    netname: str | None = Field(
        default=None,
        description="network name: will be deprecated in future, use netinstname",
    )
    io: PhyAdapter | None = None
    intforder: float | None = Field(default=None, description="intforder")
    intfname: str = Field(..., description="intf Name")
    directattach: bool | None = Field(
        default=None,
        description="direct attach flag",
        title="comes from manifest during app create",
    )
    privateip: bool | None = Field(default=None, description="Private IP flag")
    acls: list[AppACE] | None = Field(default=None, description="app Acls")
    ipaddr: str | None = Field(
        default=None,
        description="IP address",
        title="if netname points static DHCP then we need to take\nstatic /32 address here",
    )
    macaddr: str | None = Field(
        default=None,
        description="MAC address",
        title="in case of p2v we might want to provide a mac-address.\napplicable only in case of DHCP=passthrough",
    )
    access_vlan_id: confloat(ge=2.0, le=4093.0) | None = Field(
        default=None,
        alias="accessVlanId",
        description="access port VLAN ID, vlan id of zero will be treated as trunk port and vlan id 1 is implicitly used by linux bridges",
    )
    eidregister: EIDRegister | None = None
    netinstname: str | None = Field(
        default=None,
        description='Network Instance name to be matched for interface assignment. Applicable only when "direct attach" flag is false',
    )
    netinsttag: dict[str, str] | None = Field(
        default=None,
        description='Network Instance tag to be matched for interface assignment. Applicable only when "direct attach" flag is false',
    )
    netinstid: str | None = Field(
        default=None,
        description="Network Instance id to be matched for interface assignment.",
    )
    default_net_instance: bool | None = Field(
        default=None, alias="defaultNetInstance", description="default instance flag"
    )
    allow_to_discover: bool | None = Field(
        default=None,
        alias="allowToDiscover",
        description="flag tells if appInstance have permission to access the network mappings from the connected netInstance",
    )


class CustomConfig(BaseModel):
    name: str | None = Field(
        default=None, description="Name of CustomConfig (Required)"
    )
    add: bool | None = Field(
        default=None,
        description="Add the Custom Config to App Instance (Optional. Default: False)",
    )
    override: bool | None = Field(
        default=None,
        description="Override existing custom config from App Bundle Manifest (Optional. Default: False)",
    )
    allow_storage_resize: bool | None = Field(
        default=None,
        alias="allowStorageResize",
        description="Allow Appinstance storage to be resized after app instance is created. (Optional. Default: False)",
    )
    field_delimiter: str | None = Field(
        default=None,
        alias="fieldDelimiter",
        description="Field delimiter used in specifying variables in template. (Required)",
    )
    template: str | None = Field(
        default=None, description="base64 encrypted template string. (Optional)"
    )
    variable_groups: list[CustomConfigVariableGroup] | None = Field(
        default=None,
        alias="variableGroups",
        description="List of Variable groups. (Required)",
    )


class ProfileNetworkConfig(BaseModel):
    tags: dict[str, str] | None = Field(
        default=None,
        description="Tags are name/value pairs that enable you to categorize resources. Tag names are case insensitive with max_length 512 and min_length 3. Tag values are case sensitive with max_length 256 and min_length 3.",
    )
    port: str | None = Field(
        default=None,
        description="name of port mapping in the model",
        title="name of port mapping in the model",
    )
    port_tags: dict[str, str] | None = Field(
        default=None,
        alias="portTags",
        description="Tags are name/value pairs that enable you to categorize resources. Tag names are case insensitive with max_length 512 and min_length 3. Tag values are case sensitive with max_length 256 and min_length 3.",
    )
    kind: NetworkInstanceKind | None = "NETWORK_INSTANCE_KIND_UNSPECIFIED"
    type: NetworkInstanceDhcpType | None = "NETWORK_INSTANCE_DHCP_TYPE_UNSPECIFIED"
    ip: DhcpServerConfig | None = None
    dns_list: list[StaticDNSList] | None = Field(
        default=None, alias="dnsList", description="List of Static DNS entries"
    )
    opaque: NetInstOpaqueConfig | None = None
    device_default: bool | None = Field(
        default=None,
        alias="deviceDefault",
        description="flag to indicate if this is the default network instance for the device",
        title="flag to indicate if this is default network",
    )
    propagate_connected_routes: bool | None = Field(
        default=None,
        alias="propagateConnectedRoutes",
        description="Automatically propagate connected routes",
        title="flag to indicate automatically propagate connected routes",
    )
    static_routes: list[StaticIPRoute] | None = Field(
        default=None,
        alias="staticRoutes",
        description="List of Static IP routes",
        title="list of static IP routes",
    )


class ProfileNetworkPolicy(BaseModel):
    meta_data: ProfilePolicyCommon | None = Field(default=None, alias="metaData")
    network_config: ProfileNetworkConfig | None = Field(
        default=None, alias="networkConfig"
    )


class UserDataTemplate(BaseModel):
    custom_config: CustomConfig | None = Field(default=None, alias="customConfig")


class VMManifest(BaseModel):
    ac_kind: str | None = Field(
        default="VMManifest",
        alias="acKind",
        description="UI map: N/A - not exposed to users",
        title="Edge Application type",
    )
    ac_version: str | None = Field(
        default="1.2.0",
        alias="acVersion",
        description="UI map: N/A - not exposed to users",
        title="Manifest version",
    )
    name: str | None = Field(
        default=None,
        description="UI map: AppEditPage:IdentityPane:Name_Field, AppDetailsPage:IdentityPane:Name_Field",
        title="Unique id of app manifest, should match object name",
    )
    display_name: str | None = Field(
        default=None,
        alias="displayName",
        description="UI map: AppEditPage:IdentityPane:Title_Field, AppDetailsPage:IdentityPane:Title_Field",
        title="Display name or title of app manifest",
    )
    description: constr(pattern=r"[0-9A-Za-z-]+") | None = Field(
        default=None,
        description="UI map: AppDetailsPage:IdentityPane:DescriptionField, AppMarketplacePage:AppCard:DescriptionField",
        title="Description of the Edge application",
    )
    owner: Author | None = None
    desc: Details | None = None
    images: list[VMManifestImage] | None = Field(
        default=None,
        description="UI map: AppEditPage:DrivesPane, AppDetailsPage:DrivesPane",
        title="Images used by the app",
    )
    interfaces: list[Interface] | None = Field(
        default=None,
        description="UI map: AppEditPage:EnvironmentsPane, AppDetailsPage:EnvironmentsPane",
        title="I/O adapter settings",
    )
    permissions: list[Permission] | None = None
    vmmode: str | None = Field(
        default="HV_HVM",
        description="UI map: AppEditPage:IdentityPane:VM_Mode_Field, AppDetailsPage:IdentityPane:VM_Mode_Field",
        title="VM mode for VM-based app",
    )
    enablevnc: bool | None = Field(
        default=None,
        description="UI map: AppEditPage:IdentityPane:VNC_Field, AppDetailsPage:IdentityPane:VNC_Field",
        title="Enable VNC for the app",
    )
    resources: list[Resource] | None = Field(
        default=None,
        description="UI map: AppEditPage:ResourcesPane, AppDetailsPage:ResourcesPane",
        title="Hardware resource requirement (CPU, Memory, Storage) for the app",
    )
    configuration: UserDataTemplate | None = None
    container_detail: ContainerDetail | None = Field(
        default=None, alias="containerDetail"
    )
    module: ModuleDetail | None = None
    app_type: AppType | None = Field(default="APP_TYPE_UNSPECIFIED", alias="appType")
    deployment_type: DeploymentType | None = Field(
        default="DEPLOYMENT_TYPE_UNSPECIFIED", alias="deploymentType"
    )
    cpu_pinning_enabled: bool | None = Field(
        default=None, alias="cpuPinningEnabled", description="Enable CpuPinning"
    )
    runtime_version: DockerRuntimeVersion | None = Field(
        default="RuntimeVersion_Unknown", alias="runtimeVersion"
    )
    runtime_protocol_version: DockerRuntimeProtocolVersion | None = Field(
        default="RuntimeProtocolVersion_Unknown", alias="runtimeProtocolVersion"
    )
    persistent_runtime_size_bytes: str | None = Field(
        default=None,
        alias="PersistentRuntimeSizeBytes",
        description="Size of persistent blank storage for runtime in bytes",
    )
    docker_compose_yaml_text: str | None = Field(
        default=None,
        alias="dockerComposeYamlText",
        description="Docker compose base64 encoded plain text",
    )
    docker_compose_tar_image_name: str | None = Field(
        default=None,
        alias="dockerComposeTarImageName",
        description="Docker compose tar image name",
    )
    enable_oem_win_license_key: bool | None = Field(
        default=None,
        alias="enableOemWinLicenseKey",
        description="UI map: AppEditPage:IdentityPane:ENABLEVMCONFIG_Field, AppDetailsPage:IdentityPane:ENABLEVMCONFIG_Field",
        title="Enable device to read the license info from APCI tables",
    )
    disable_vtpm: bool | None = Field(
        default=None,
        alias="disableVTPM",
        description="UI map: AppEditPage:IdentityPane:DISABLEVTPM_Field, AppDetailsPage:IdentityPane:DISABLEVTPM_Field",
        title="Disable vTPM for a virtual machine (VM)",
    )


class ProfileAppConfig(BaseModel):
    networks: int | None = Field(
        default=None, description="user defined network options"
    )
    drives: int | None = Field(default=None, description="user defined drives")
    cpus: int | None = Field(default=None, description="user defined cpus for bundle")
    memory: int | None = Field(
        default=None, description="user defined memory for bundle"
    )
    manifest_json: VMManifest | None = Field(default=None, alias="manifestJSON")
    storage: int | None = Field(
        default=None, description="user defined storage for bundle"
    )
    name_project_part: str | None = Field(
        default=None,
        alias="nameProjectPart",
        description="User provided name part  for the auto deployed app",
    )
    name_app_part: str | None = Field(
        default=None,
        alias="nameAppPart",
        description="User provided name part  for the auto deployed app",
    )
    interfaces: list[AppInterface] | None = Field(
        default=None, description="application interfaces"
    )
    start_delay_in_seconds: int | None = Field(
        default=None,
        alias="startDelayInSeconds",
        description="start delay is the time in seconds EVE should wait after boot before starting the application instance",
    )
    tags: dict[str, str] | None = Field(
        default=None,
        description="Tags are name/value pairs that enable you to categorize resources. Tag names are case insensitive with max_length 512 and min_length 3. Tag values are case sensitive with max_length 256 and min_length 3.",
    )
    logs: AppInstanceLogs | None = None
    vminfo: Vm | None = None
    remote_console: bool | None = Field(
        default=None, alias="remoteConsole", description="Remote console flag"
    )
    new_bundle_version_available: bool | None = Field(
        default=None,
        alias="newBundleVersionAvailable",
        description="this flag denotes whether there is latest bundle available in the marketplace or not",
    )
    bundle_version: int | None = Field(
        default=None, alias="bundleVersion", description="current bundle version"
    )
    net_inst_tags: dict[str, str] | None = Field(
        default=None,
        alias="netInstTags",
        description="Tags are name/value pairs that enable you to categorize resources. Tag names are case insensitive with max_length 512 and min_length 3. Tag values are case sensitive with max_length 256 and min_length 3.",
    )
    net_inst_name: str | None = Field(
        default=None, alias="netInstName", description="network instance name"
    )


class ProfileAppPolicy(BaseModel):
    meta_data: ProfilePolicyCommon | None = Field(default=None, alias="metaData")
    app_config: ProfileAppConfig | None = Field(default=None, alias="appConfig")


class AppProfile(BaseModel):
    id: str | None = Field(default=None, description="unique id for an App profile")
    name: str | None = Field(
        default=None, description="user defined name for the App profile"
    )
    title: str | None = Field(
        default=None, description="user defined title for the app profile"
    )
    app_policies: list[ProfileAppPolicy] | None = Field(
        default=None, alias="appPolicies", description="list of app instance policies"
    )
    network_policies: list[ProfileNetworkPolicy] | None = Field(
        default=None,
        alias="networkPolicies",
        description="list of network instance policies",
    )
    volume_policies: list[ProfileVolumePolicy] | None = Field(
        default=None,
        alias="volumePolicies",
        description="list of volume instance policies",
    )
    latest_version: int | None = Field(
        default=None,
        alias="latestVersion",
        description="latest version of app profile. Server-derived; value supplied in a create or update request is ignored",
    )
    status: AppProfileStatusType | None = "APP_PROFILE_STATUS_TYPE_INACTIVE"


class AppProfileConfigSummary(BaseModel):
    id: str | None = Field(default=None, description="unique id for app profile")
    name: str | None = Field(default=None, description="user defined app profile name")
    title: str | None = Field(
        default=None, description="user defined app profile title"
    )
    description: constr(max_length=256) | None = Field(
        default=None, description="Detailed description of the app profile."
    )
    app_policies: list[ProfileAppPolicy] | None = Field(
        default=None, alias="appPolicies", description="list of app instance policies"
    )
    network_policies: list[ProfileNetworkPolicy] | None = Field(
        default=None,
        alias="networkPolicies",
        description="list of network instance policies",
    )
    volume_policies: list[ProfileVolumePolicy] | None = Field(
        default=None,
        alias="volumePolicies",
        description="list of volume instance policies",
    )


class AppProfileRead(BaseModel):
    id: str | None = Field(default=None, description="unique id for an App profile")
    name: str | None = Field(
        default=None, description="user defined name for the App profile"
    )
    title: str | None = Field(
        default=None, description="user defined title for the app profile"
    )
    app_policies: list[ProfileAppPolicy] | None = Field(
        default=None, alias="appPolicies", description="list of app instance policies"
    )
    network_policies: list[ProfileNetworkPolicy] | None = Field(
        default=None,
        alias="networkPolicies",
        description="list of network instance policies",
    )
    volume_policies: list[ProfileVolumePolicy] | None = Field(
        default=None,
        alias="volumePolicies",
        description="list of volume instance policies",
    )
    latest_version: int | None = Field(
        default=None, alias="latestVersion", description="latest version of app profile"
    )
    status: AppProfileStatusType | None = "APP_PROFILE_STATUS_TYPE_INACTIVE"


class AppProfileVersion(BaseModel):
    id: str | None = Field(default=None, description="unique id for an App profile")
    name: str | None = Field(
        default=None, description="user defined name for the App profile"
    )
    title: str | None = Field(
        default=None, description="user defined title for the app profile"
    )
    app_policies: list[ProfileAppPolicy] | None = Field(
        default=None, alias="appPolicies", description="list of app instance policies"
    )
    network_policies: list[ProfileNetworkPolicy] | None = Field(
        default=None,
        alias="networkPolicies",
        description="list of network instance policies",
    )
    volume_policies: list[ProfileVolumePolicy] | None = Field(
        default=None,
        alias="volumePolicies",
        description="list of volume instance policies",
    )
    version: int | None = Field(
        default=None, description="latest version of app profile"
    )


class AppProfileVersionListResp(BaseModel):
    version_list: list[AppProfileVersion] | None = Field(
        default=None,
        alias="versionList",
        description="App profile version list response",
    )
    next: Cursor | None = None


class AppProfiles(BaseModel):
    summary_by_state: Summary | None = Field(default=None, alias="summaryByState")
    list_: list[AppProfileConfigSummary] | None = Field(
        default=None, alias="list", description="App profile summary list response"
    )
    next: Cursor | None = None
