# Generated by scripts/generate_from_openapi.py from zedge_kubernetes_service.swagger.json
# Do not edit by hand — re-run: uv run python scripts/generate_from_openapi.py

from __future__ import annotations
from enum import Enum
from pydantic import AwareDatetime, Base64Str, BaseModel, Field, constr
from typing import Any


class AdminState(Enum):
    admin_state_unspecified = "ADMIN_STATE_UNSPECIFIED"
    admin_state_created = "ADMIN_STATE_CREATED"
    admin_state_deleted = "ADMIN_STATE_DELETED"
    admin_state_active = "ADMIN_STATE_ACTIVE"
    admin_state_inactive = "ADMIN_STATE_INACTIVE"
    admin_state_registered = "ADMIN_STATE_REGISTERED"
    admin_state_archived = "ADMIN_STATE_ARCHIVED"
    admin_state_deletion_pending = "ADMIN_STATE_DELETION_PENDING"


class BaseOSImage(BaseModel):
    uuid: str = Field(..., description="system generated unique id for an image")
    version: str = Field(..., description="image version")
    image_name: str = Field(..., alias="imageName", description="image name")
    activate: bool = Field(..., description="activation flag")
    imvol_id: str | None = Field(
        default=None,
        alias="imvolId",
        description="immutable Volume for this base image",
    )


class BasicAuthCredentials(BaseModel):
    username: str | None = Field(
        default=None, description="Username for basic authentication"
    )
    password: str | None = Field(
        default=None, description="Password for basic authentication"
    )


class Chart(BaseModel):
    name: str = Field(..., description="Name of the Helm chart. Example: 'nginx'")
    version: str = Field(
        ..., description="Version of the Helm chart. Example: '15.4.0'"
    )
    custom_values: dict[str, Any] | None = Field(
        default=None,
        alias="customValues",
        description="Custom values for the Helm chart. Example: {'replicaCount': 3, 'service': {'type': 'LoadBalancer', 'port': 80}}",
    )
    repo_identifier: str | None = Field(
        default=None,
        alias="repoIdentifier",
        description="Repository identifier for the Helm chart. Example: 'bitnami'",
    )


class ClusterGroupManifest(BaseModel):
    yaml_content: str = Field(
        ..., alias="yamlContent", description="The content of an yaml manifest"
    )


class ClusterGroupManifestJaml(BaseModel):
    yaml_content: str | None = Field(
        default=None, alias="yamlContent", description="The content of an jaml manifest"
    )


class ClusterGroupManifestOutput(BaseModel):
    manifest: ClusterGroupManifestJaml | None = None


class ClusterGroupResourceSummary(BaseModel):
    missing: int | None = Field(
        default=None,
        description="Number of resources in the cluster group that are missing",
    )
    modified: int | None = Field(
        default=None,
        description="Number of resources in the cluster group that are modified",
    )
    not_ready: int | None = Field(
        default=None,
        alias="notReady",
        description="Number of resources in the cluster group that are not ready",
    )
    orphaned: int | None = Field(
        default=None,
        description="Number of resources in the cluster group that are orphaned",
    )
    ready: int | None = Field(
        default=None,
        description="Number of resources in the cluster group that are ready",
    )
    unknown: int | None = Field(
        default=None,
        description="Number of resources in the cluster group that are in unknown state",
    )
    wait_applied: int | None = Field(
        default=None,
        alias="waitApplied",
        description="Number of resources in the cluster group that are waiting for applied state",
    )


class ClusterGroupResources(BaseModel):
    amount: int | None = Field(
        default=None, description="Total resources of clusters in the cluster group"
    )
    summary: ClusterGroupResourceSummary | None = None


class ClusterMetadata(BaseModel):
    cluster_id: str = Field(
        ...,
        alias="clusterId",
        description="ID of the target cluster. Example: 'cluster-abc123'",
    )
    orchestrator_cluster_id: str = Field(
        ...,
        alias="orchestratorClusterId",
        description="Orchestrator cluster ID. Example: 'rancher-cluster-123'",
    )
    cluster_name: str | None = Field(
        default=None,
        alias="clusterName",
        description="Name of the target cluster. Example: 'production-k8s'",
    )
    kube_version: str | None = Field(
        default=None,
        alias="kubeVersion",
        description="Kubernetes version of the target cluster. Example: 'v1.28.0'",
    )


class ClusterReadiness(BaseModel):
    total: int | None = Field(
        default=None, description="Total number of clusters in the cluster group"
    )
    ready: int | None = Field(
        default=None,
        description="Number of clusters in the cluster group that are ready",
    )


class Cursor(BaseModel):
    page_token: str | None = Field(
        default=None, alias="pageToken", description="Page Token"
    )
    order_by: list[str] | None = Field(
        default=None,
        alias="orderBy",
        description="OrderBy helps in sorting the list response",
    )
    page_num: float | None = Field(
        default=None, alias="pageNum", description="Page Number"
    )
    page_size: float | None = Field(
        default=None, alias="pageSize", description="Defines the page size"
    )
    total_pages: float | None = Field(
        default=None,
        alias="totalPages",
        description="Total number of pages to be fetched.",
    )


class GitRepoCondition(BaseModel):
    type: str | None = Field(default=None, description="Type of the condition")
    status: str | None = Field(
        default=None, description="Status of the condition (True, False, Unknown)"
    )
    error: bool | None = Field(
        default=None, description="Whether the condition represents an error state"
    )
    transitioning: bool | None = Field(
        default=None, description="Whether the condition is in a transitioning state"
    )
    message: str | None = Field(
        default=None,
        description="Human readable message indicating details about the condition",
    )
    last_update_time: str | None = Field(
        default=None,
        alias="lastUpdateTime",
        description="Last time the condition was updated",
    )


class GitRepoEvents(BaseModel):
    reason: str | None = Field(default=None, description="Reason for the event")
    type: str | None = Field(default=None, description="Type of the event")
    message: str | None = Field(
        default=None, description="Detailed message about the event"
    )
    last_update_time: AwareDatetime | None = Field(
        default=None,
        alias="lastUpdateTime",
        description="Last time the event was updated",
    )


class GitRepoListStatusSummary(BaseModel):
    description: str | None = Field(
        default=None, description="Description of the status summary"
    )
    total: int | None = Field(default=None, description="Total number of GitRepos")
    values: dict[str, int] | None = Field(
        default=None, description="Map of status values and their counts"
    )


class GitRepoMetadata(BaseModel):
    name: str = Field(..., description="Name of the GitRepo configuration (required)")
    title: str | None = Field(
        default=None, description="Display title of the GitRepo configuration"
    )
    description: str | None = Field(
        default=None, description="Description of the GitRepo configuration"
    )


class GitRepoRepositoryDetails(BaseModel):
    url: str = Field(..., description="Git repository URL (required)")
    branch: str | None = Field(default=None, description="Git branch to track")
    commit: str | None = Field(default=None, description="Specific git commit hash")
    path_list: list[str] | None = Field(
        default=None,
        alias="pathList",
        description="List of paths within the repository to monitor",
    )


class GitRepoResourceCounts(BaseModel):
    desired_ready: int | None = Field(
        default=None, alias="desiredReady", description="Desired ready count"
    )
    missing: int | None = Field(default=None, description="Missing resources count")
    modified: int | None = Field(default=None, description="Modified resources count")
    not_ready: int | None = Field(
        default=None, alias="notReady", description="Not ready resources count"
    )
    orphaned: int | None = Field(default=None, description="Orphaned resources count")
    ready: int | None = Field(default=None, description="Ready resources count")
    unknown: int | None = Field(default=None, description="Unknown resources count")
    wait_applied: int | None = Field(
        default=None, alias="waitApplied", description="Wait applied resources count"
    )


class GitRepoResourceStatusMap(BaseModel):
    api_version: str | None = Field(
        default=None, alias="apiVersion", description="API version of the resource"
    )
    kind: str | None = Field(default=None, description="Kind of Kubernetes resource")
    name: str | None = Field(default=None, description="Name of the resource")
    namespace: str | None = Field(default=None, description="Namespace of the resource")
    state: str | None = Field(default=None, description="State of the resource")


class GitRepoState(BaseModel):
    error: bool | None = Field(
        default=None, description="Indicates if the GitRepo is in an error state"
    )
    message: str | None = Field(
        default=None,
        description="Status message providing additional details about the GitRepo state",
    )
    name: str | None = Field(default=None, description="current state name")
    transitioning: bool | None = Field(
        default=None,
        description="Indicates if the GitRepo is currently undergoing state transition",
    )


class GitRepoStatusDisplay(BaseModel):
    ready_bundle_deployments: str | None = Field(
        default=None,
        alias="readyBundleDeployments",
        description="Ready bundle deployments count",
    )
    state: str | None = Field(default=None, description="Current state of the GitRepo")


class GitRepoTargetType(Enum):
    git_repo_target_type_unknown = "GIT_REPO_TARGET_TYPE_UNKNOWN"
    git_repo_target_type_all_cluster = "GIT_REPO_TARGET_TYPE_ALL_CLUSTER"
    git_repo_target_type_cluster = "GIT_REPO_TARGET_TYPE_CLUSTER"
    git_repo_target_type_cluster_group = "GIT_REPO_TARGET_TYPE_CLUSTER_GROUP"


class HelmChartDependency(BaseModel):
    name: constr(pattern=r"^[a-z0-9]([-a-z0-9]*[a-z0-9])?$") | None = Field(
        default=None, description="Name of the dependency chart. Example: 'postgresql'"
    )
    repository: str | None = Field(
        default=None,
        description="Repository URL for the dependency. Example: 'https://charts.bitnami.com/bitnami'",
    )
    tags: list[str] | None = Field(
        default=None,
        description="Tags associated with the dependency. Example: ['database', 'postgresql']",
    )
    version: str | None = Field(
        default=None,
        description="Version constraint for the dependency. Example: '^12.0.0'",
    )


class HelmChartListResponse(BaseModel):
    api_version: str | None = Field(
        default=None, alias="apiVersion", description="API version of the chart index"
    )
    generated: str | None = Field(
        default=None, description="Timestamp when the chart index was generated"
    )
    repo_identifier: str | None = Field(
        default=None,
        alias="repoIdentifier",
        description="Identifier for the Helm chart repository",
    )
    repo_name: str | None = Field(
        default=None, alias="repoName", description="Name of the Helm chart repository"
    )
    entries: dict[str, list[dict[str, Any]]] | None = Field(
        default=None, description="Map of chart names to list of chart version details"
    )


class HelmChartMaintainer(BaseModel):
    name: str | None = Field(
        default=None, description="Name of the maintainer. Example: 'Zededa Team'"
    )
    url: str | None = Field(
        default=None,
        description="URL or contact information for the maintainer. Example: 'https://github.com/bitnami/charts'",
    )


class K8sDeploymentType(Enum):
    k8s_deployment_type_unspecified = "K8sDeploymentType_UNSPECIFIED"
    helmchart = "HELMCHART"


class Metadata(BaseModel):
    name: str = Field(
        ..., description="Name of the deployment. Example: 'nginx-deployment'"
    )
    title: str | None = Field(
        default=None,
        description="Human-readable title of the deployment. Example: 'NGINX Web Server'",
    )
    description: str | None = Field(
        default=None,
        description="Description of the deployment. Example: 'Production NGINX deployment with custom configuration'",
    )
    project_id: str = Field(
        ..., alias="projectId", description="Project ID associated with the deployment"
    )


class NodeAction(Enum):
    node_action_unspecified = "NODE_ACTION_UNSPECIFIED"
    node_action_add_nodes = "NODE_ACTION_ADD_NODES"
    node_action_remove_nodes = "NODE_ACTION_REMOVE_NODES"


class ObjectType(Enum):
    object_type_unspecified = "OBJECT_TYPE_UNSPECIFIED"
    object_type_user = "OBJECT_TYPE_USER"
    object_type_edge_node = "OBJECT_TYPE_EDGE_NODE"
    object_type_edge_app = "OBJECT_TYPE_EDGE_APP"
    object_type_image = "OBJECT_TYPE_IMAGE"
    object_type_edge_app_instance = "OBJECT_TYPE_EDGE_APP_INSTANCE"
    object_type_project = "OBJECT_TYPE_PROJECT"
    object_type_network = "OBJECT_TYPE_NETWORK"
    object_type_datastore = "OBJECT_TYPE_DATASTORE"
    object_type_service = "OBJECT_TYPE_SERVICE"
    object_type_service_instance = "OBJECT_TYPE_SERVICE_INSTANCE"
    object_type_enterprise = "OBJECT_TYPE_ENTERPRISE"
    object_type_role = "OBJECT_TYPE_ROLE"
    object_type_credential = "OBJECT_TYPE_CREDENTIAL"
    object_type_network_instance = "OBJECT_TYPE_NETWORK_INSTANCE"
    object_type_volume_instance = "OBJECT_TYPE_VOLUME_INSTANCE"
    object_type_realm = "OBJECT_TYPE_REALM"
    object_type_authprofile = "OBJECT_TYPE_AUTHPROFILE"
    object_type_policy = "OBJECT_TYPE_POLICY"
    object_type_app_policy = "OBJECT_TYPE_APP_POLICY"
    object_type_cluster_instance = "OBJECT_TYPE_CLUSTER_INSTANCE"
    object_type_plugin = "OBJECT_TYPE_PLUGIN"
    object_type_doc_policy = "OBJECT_TYPE_DOC_POLICY"
    object_type_orchestrator_cluster = "OBJECT_TYPE_ORCHESTRATOR_CLUSTER"
    object_type_tags = "OBJECT_TYPE_TAGS"
    object_type_edge_node_interface = "OBJECT_TYPE_EDGE_NODE_INTERFACE"
    object_type_deployment = "OBJECT_TYPE_DEPLOYMENT"
    object_type_entitlements = "OBJECT_TYPE_ENTITLEMENTS"
    object_type_data_stream = "OBJECT_TYPE_DATA_STREAM"
    object_type_api_usage = "OBJECT_TYPE_API_USAGE"
    object_type_app_instance_snapshot = "OBJECT_TYPE_APP_INSTANCE_SNAPSHOT"
    object_type_patch_envelope = "OBJECT_TYPE_PATCH_ENVELOPE"
    object_type_resource_usage_track = "OBJECT_TYPE_RESOURCE_USAGE_TRACK"
    object_type_patch_envelope_reference = "OBJECT_TYPE_PATCH_ENVELOPE_REFERENCE"
    object_type_dev_passthrough = "OBJECT_TYPE_DEV_PASSTHROUGH"
    object_type_edge_node_cluster = "OBJECT_TYPE_EDGE_NODE_CLUSTER"
    object_type_asset_group = "OBJECT_TYPE_ASSET_GROUP"
    object_type_app_profile = "OBJECT_TYPE_APP_PROFILE"
    object_type_profile_deployment = "OBJECT_TYPE_PROFILE_DEPLOYMENT"
    object_type_zks_instance = "OBJECT_TYPE_ZKS_INSTANCE"
    object_type_cluster_group = "OBJECT_TYPE_CLUSTER_GROUP"


class PodsCapacity(BaseModel):
    used: int | None = Field(default=None, description="Used pods capacity")
    total: int | None = Field(default=None, description="Total pods capacity")


class PrivateRepoMetadata(BaseModel):
    name: str = Field(
        ..., description="Name of the private repository configuration (required)"
    )
    title: str | None = Field(
        default=None,
        description="Display title of the private repository configuration",
    )
    description: str | None = Field(
        default=None, description="Description of the private repository configuration"
    )
    tags: dict[str, str] | None = Field(
        default=None, description="Tags associated with the private repository"
    )


class PrivateRepoStatus(BaseModel):
    error: bool | None = Field(
        default=None, description="Indicates if the repository is in an error state"
    )
    message: str | None = Field(
        default=None,
        description="Status message providing additional details about the repository state",
    )
    name: str | None = Field(
        default=None, description="Name of the repository in its current state"
    )
    transitioning: bool | None = Field(
        default=None,
        description="Indicates if the repository is currently undergoing state transition",
    )


class PrivateRepoType(Enum):
    private_repo_type_unspecified = "PRIVATE_REPO_TYPE_UNSPECIFIED"
    private_repo_type_git = "PRIVATE_REPO_TYPE_GIT"
    private_repo_type_helm_index = "PRIVATE_REPO_TYPE_HELM_INDEX"


class ResourceUsage(BaseModel):
    current: float | None = Field(default=None, description="Current resource usage")
    total: float | None = Field(default=None, description="Total resource usage")


class RunState(Enum):
    run_state_unspecified = "RUN_STATE_UNSPECIFIED"
    run_state_online = "RUN_STATE_ONLINE"
    run_state_halted = "RUN_STATE_HALTED"
    run_state_init = "RUN_STATE_INIT"
    run_state_rebooting = "RUN_STATE_REBOOTING"
    run_state_offline = "RUN_STATE_OFFLINE"
    run_state_unknown = "RUN_STATE_UNKNOWN"
    run_state_unprovisioned = "RUN_STATE_UNPROVISIONED"
    run_state_provisioned = "RUN_STATE_PROVISIONED"
    run_state_suspect = "RUN_STATE_SUSPECT"
    run_state_downloading = "RUN_STATE_DOWNLOADING"
    run_state_restarting = "RUN_STATE_RESTARTING"
    run_state_purging = "RUN_STATE_PURGING"
    run_state_halting = "RUN_STATE_HALTING"
    run_state_error = "RUN_STATE_ERROR"
    run_state_verifying = "RUN_STATE_VERIFYING"
    run_state_loading = "RUN_STATE_LOADING"
    run_state_creating_volume = "RUN_STATE_CREATING_VOLUME"
    run_state_booting = "RUN_STATE_BOOTING"
    run_state_maintenance_mode = "RUN_STATE_MAINTENANCE_MODE"
    run_state_start_delayed = "RUN_STATE_START_DELAYED"
    run_state_baseos_updating = "RUN_STATE_BASEOS_UPDATING"
    run_state_preparing_poweroff = "RUN_STATE_PREPARING_POWEROFF"
    run_state_powering_off = "RUN_STATE_POWERING_OFF"
    run_state_prepared_poweroff = "RUN_STATE_PREPARED_POWEROFF"


class SSHCredentials(BaseModel):
    ssh_private_key: str | None = Field(
        default=None,
        alias="sshPrivateKey",
        description="Base64 encoded SSH private key for authentication, Required if Secret type is SECRET_TYPE_SSH",
    )
    ssh_public_key: str | None = Field(
        default=None,
        alias="sshPublicKey",
        description="Base64 encoded SSH public key for authentication, Required if Secret type is SECRET_TYPE_SSH",
    )


class SecretData(BaseModel):
    encoded_username: str | None = Field(
        default=None,
        alias="encodedUsername",
        description="Base64 encoded username for basic authentication, Required if Secret type is SECRET_TYPE_BASIC_AUTH",
    )
    encoded_password: str | None = Field(
        default=None,
        alias="encodedPassword",
        description="Base64 encoded password for basic authentication, Required if Secret type is SECRET_TYPE_BASIC_AUTH",
    )
    ssh_public_key: str | None = Field(
        default=None,
        alias="sshPublicKey",
        description="Base64 encoded SSH public key for SSH authentication, Required if Secret type is SECRET_TYPE_SSH",
    )
    ssh_private_key: str | None = Field(
        default=None,
        alias="sshPrivateKey",
        description="Base64 encoded SSH private key for SSH authentication, Required if Secret type is SECRET_TYPE_SSH",
    )


class SecretState(BaseModel):
    error: bool | None = Field(
        default=None, description="Indicates if the secret is in an error state"
    )
    message: str | None = Field(
        default=None,
        description="Status message providing additional details about the secret state",
    )
    name: str | None = Field(
        default=None, description="Name of the secret in its current state"
    )
    transitioning: bool | None = Field(
        default=None,
        description="Indicates if the secret is currently undergoing state transition",
    )


class SecretType(Enum):
    secret_type_unspecified = "SECRET_TYPE_UNSPECIFIED"
    secret_type_ssh = "SECRET_TYPE_SSH"
    secret_type_basic_auth = "SECRET_TYPE_BASIC_AUTH"
    secret_type_none = "SECRET_TYPE_NONE"


class SnapshotOperationStatus(Enum):
    snapshot_operation_status_unspecified = "SNAPSHOT_OPERATION_STATUS_UNSPECIFIED"
    snapshot_operation_status_in_progress = "SNAPSHOT_OPERATION_STATUS_IN_PROGRESS"
    snapshot_operation_status_completed = "SNAPSHOT_OPERATION_STATUS_COMPLETED"
    snapshot_operation_status_failed = "SNAPSHOT_OPERATION_STATUS_FAILED"
    snapshot_operation_status_timed_out = "SNAPSHOT_OPERATION_STATUS_TIMED_OUT"


class SnapshotOperationType(Enum):
    snapshot_operation_type_unspecified = "SNAPSHOT_OPERATION_TYPE_UNSPECIFIED"
    snapshot_operation_type_create = "SNAPSHOT_OPERATION_TYPE_CREATE"
    snapshot_operation_type_restore = "SNAPSHOT_OPERATION_TYPE_RESTORE"
    snapshot_operation_type_delete = "SNAPSHOT_OPERATION_TYPE_DELETE"


class SnapshotStatusInfo(BaseModel):
    state: str | None = Field(
        default=None,
        description="Current state of the snapshot (e.g., ready, creating, error)",
    )
    message: str | None = Field(
        default=None, description="Status message with additional details"
    )


class Summary(BaseModel):
    description: str | None = Field(default=None, description="Summary description")
    total: float | None = Field(default=None, description="Total")
    values: dict[str, int] | None = Field(
        default=None, description="Values: Map for storing <string, uint32>"
    )


class TargetClusters(BaseModel):
    is_multi_cluster: bool = Field(
        ...,
        alias="isMultiCluster",
        description="Indicates if the deployment is for multiple clusters. Example: false",
    )
    cluster_tags: dict[str, str] | None = Field(
        default=None,
        alias="clusterTags",
        description="Tags for the clusters where the deployment will be applied. Example: {'environment': 'production', 'region': 'us-west-2'}. This field is reserved for future use and not currently implemented.",
    )
    cluster_metadata: ClusterMetadata = Field(..., alias="clusterMetadata")


class ZcOpsStatus(Enum):
    ops_status_unspecified = "OPS_STATUS_UNSPECIFIED"
    ops_status_pending = "OPS_STATUS_PENDING"
    ops_status_ongoing = "OPS_STATUS_ONGOING"
    ops_status_complete = "OPS_STATUS_COMPLETE"


class ZcOpsType(Enum):
    ops_type_unspecified = "OPS_TYPE_UNSPECIFIED"
    ops_type_read = "OPS_TYPE_READ"
    ops_type_delete = "OPS_TYPE_DELETE"
    ops_type_create = "OPS_TYPE_CREATE"
    ops_type_update = "OPS_TYPE_UPDATE"
    ops_type_list = "OPS_TYPE_LIST"


class ZksInstanceBulkUpdateData(BaseModel):
    tags: dict[str, str] | None = Field(
        default=None, description="New tags for the ZKS instance"
    )


class ZksInstanceK3sBulkUpgradeData(BaseModel):
    version: str | None = Field(default=None, description="K3s version to upgrade to")


class ZksInstanceNode(BaseModel):
    id: constr(pattern=r"[0-9A-Za-z-]+") = Field(
        ..., description="System defined universally unique Id of the node"
    )
    cluster_interface: str = Field(
        ..., alias="clusterInterface", description="Cluster interface of the node"
    )


class ZksInstanceRegistrationCommands(BaseModel):
    command: str | None = Field(
        default=None, description="Command to register a node with the ZKS instance"
    )
    insecure_command: str | None = Field(
        default=None,
        alias="insecureCommand",
        description="Insecure command to register a node with the ZKS instance",
    )
    node_command: str | None = Field(
        default=None,
        alias="nodeCommand",
        description="Node command to register a node with the ZKS instance",
    )
    windows_node_command: str | None = Field(
        default=None,
        alias="windowsNodeCommand",
        description="Windows node command to register a node with the ZKS instance",
    )


class ZksInstanceRegistrationInfo(BaseModel):
    created: str | None = Field(
        default=None,
        description="Timestamp when the registration commands were created",
    )
    manifest_url: str | None = Field(
        default=None,
        alias="manifestUrl",
        description="URL to fetch the registration manifest",
    )
    commands: ZksInstanceRegistrationCommands | None = None


class ZksInstanceStatusSummary(BaseModel):
    online: int | None = Field(
        default=None, description="Number of online nodes in the zks instance"
    )
    init: int | None = Field(
        default=None, description="Number of nodes in init state in the zks instance"
    )
    suspect: int | None = Field(
        default=None, description="Number of suspect nodes in the zks instance"
    )
    error: int | None = Field(
        default=None, description="Number of error nodes in the zks instance"
    )
    unspecified: int | None = Field(
        default=None,
        description="Number of nodes in unspecified state in the zks instance",
    )
    unknown: int | None = Field(
        default=None, description="Number of nodes in unknown state in the zks instance"
    )
    offline: int | None = Field(
        default=None, description="Number of offline nodes in the zks instance"
    )
    pending: int | None = Field(
        default=None, description="Number of pending nodes in the zks instance"
    )


class ZksInstanceSummary(BaseModel):
    id: str | None = Field(
        default=None,
        description="System defined universally unique Id of the zks instance",
    )
    project_id: str | None = Field(
        default=None, alias="projectId", description="Foreign key to the project"
    )
    name: str | None = Field(
        default=None,
        description="User defined name of the zks instance, unique across the enterprise. Once zks instance is created, name can’t be changed",
    )
    title: str | None = Field(
        default=None,
        description="User defined title of the zks instance. Title can be changed at any time",
    )
    description: str | None = Field(
        default=None, description="Detailed description of the zks instance"
    )
    tags: dict[str, str] | None = Field(
        default=None,
        description="Tags are name/value pairs that enable you to categorize resources.",
    )
    n_of_nodes: int | None = Field(
        default=None,
        alias="nOfNodes",
        description="Number of nodes in the zks instance",
    )


class ZksInstancesList(BaseModel):
    list_: list[ZksInstanceSummary] | None = Field(
        default=None, alias="list", description="List of ZKS instances"
    )
    next: Cursor | None = None


class ZksK3sVersion(BaseModel):
    id: str | None = Field(
        default=None, description="Unique identifier for the K3s version"
    )
    version: str | None = Field(default=None, description="K3s version string")
    type: str | None = Field(
        default=None, description="Type of the K3s version (e.g., release, beta)"
    )


class ZksK3sVersionList(BaseModel):
    list_: list[ZksK3sVersion] | None = Field(
        default=None, alias="list", description="List of available K3s versions"
    )


class ZsrvErrorCode(Enum):
    z_msg_error_none = "zMsgErrorNone"
    z_msg_sucess = "zMsgSucess"
    not_found = "NotFound"
    already_exists = "AlreadyExists"
    version_mismatch = "VersionMismatch"
    range_error = "RangeError"
    large_result = "LargeResult"
    incomplete_data = "IncompleteData"
    invalid_data = "InvalidData"
    function_unsupported = "FunctionUnsupported"
    no_memory = "NoMemory"
    send_failure = "SendFailure"
    timeout = "Timeout"
    bad_req_body = "BadReqBody"
    bad_req_param = "BadReqParam"
    invalid_field_format = "InvalidFieldFormat"
    url_not_found = "UrlNotFound"
    api_version_not_supported = "ApiVersionNotSupported"
    unauthorized = "Unauthorized"
    forbidden = "Forbidden"
    conflict = "Conflict"
    not_modified = "NotModified"
    dependency_conflict = "DependencyConflict"
    json_fmt_error = "JsonFmtError"
    proto_fmt_error = "ProtoFmtError"
    cert_error = "CertError"
    data_base_connection = "DataBaseConnection"
    db_error = "DBError"
    z_msg_accepted = "zMsgAccepted"
    z_msg_created = "zMsgCreated"
    pre_condition_failed = "PreConditionFailed"
    internal_server_error = "InternalServerError"


class ProtobufAny(BaseModel):
    type_url: str | None = Field(default=None, alias="typeUrl")
    value: Base64Str | None = None


class ProtobufNullValue(Enum):
    null_value = "NULL_VALUE"


class ClusterGroup(BaseModel):
    id: constr(pattern=r"[0-9A-Za-z-]+") | None = Field(
        default=None,
        description="System defined universally unique Id of the cluster group",
    )
    project_id: constr(pattern=r"[0-9A-Za-z-]+") = Field(
        ..., alias="projectId", description="Foreign key to the project"
    )
    name: str = Field(
        ...,
        description="User defined name of the cluster group, unique across the enterprise. Once cluster group is created, name can’t be changed",
    )
    title: str | None = Field(
        default=None,
        description="User defined title of the cluster group. Title can be changed at any time",
    )
    description: str | None = Field(
        default=None, description="Detailed description of the cluster group"
    )
    tags: dict[str, str] | None = Field(
        default=None,
        description="Tags are name/value pairs that enable you to categorize resources. Tag names are case insensitive with max_length 512 and min_length 3. Tag values are case sensitive with max_length 256 and min_length 3.",
    )
    manifest: ClusterGroupManifest | None = None


class ClusterGroupCluster(BaseModel):
    name: str | None = Field(
        default=None, description="Name of the cluster in the cluster group"
    )
    state: RunState | None = "RUN_STATE_UNSPECIFIED"
    bundle_ready: str | None = Field(
        default=None,
        alias="bundleReady",
        description="Bundle readiness of the cluster in the cluster group",
    )
    repos_ready: str | None = Field(
        default=None,
        alias="reposReady",
        description="Repository readiness of the cluster in the cluster group",
    )
    resources: int | None = Field(
        default=None,
        description="Number of resources in the cluster in the cluster group",
    )
    last_seen: AwareDatetime | None = Field(
        default=None,
        alias="lastSeen",
        description="Last seen timestamp of the cluster in the cluster group",
    )
    age: AwareDatetime | None = Field(
        default=None, description="Age of the cluster in the cluster group"
    )


class ClusterGroupStatus(BaseModel):
    id: constr(pattern=r"[0-9A-Za-z-]+") | None = Field(
        default=None,
        description="System defined universally unique Id of the cluster group",
    )
    project_id: constr(pattern=r"[0-9A-Za-z-]+") | None = Field(
        default=None, alias="projectId", description="Foreign key to the project"
    )
    project_name: str | None = Field(
        default=None,
        alias="projectName",
        description="Name of the project to which this cluster group belongs",
    )
    name: str | None = Field(
        default=None,
        description="User defined name of the cluster group, unique across the enterprise. Once cluster group is created, name can’t be changed",
    )
    title: str | None = Field(
        default=None,
        description="User defined title of the cluster group. Title can be changed at any time",
    )
    description: str | None = Field(
        default=None, description="Detailed description of the cluster group"
    )
    tags: dict[str, str] | None = Field(
        default=None,
        description="Tags are name/value pairs that enable you to categorize resources. Tag names are case insensitive with max_length 512 and min_length 3. Tag values are case sensitive with max_length 256 and min_length 3.",
    )
    state: RunState | None = "RUN_STATE_UNSPECIFIED"
    cluster_readiness: ClusterReadiness | None = Field(
        default=None, alias="clusterReadiness"
    )
    resources: ClusterGroupResources | None = None
    clusters: list[ClusterGroupCluster] | None = Field(
        default=None, description="List of clusters in the cluster group"
    )
    namespace: str | None = Field(
        default=None, description="Namespace of the cluster group"
    )
    age: AwareDatetime | None = Field(
        default=None, description="Age of the cluster group"
    )
    cluster_tags: dict[str, str] | None = Field(
        default=None,
        alias="clusterTags",
        description="Cluster tags are name/value pairs that enable you to categorize clusters",
    )


class GitRepoGetStatus(BaseModel):
    display: GitRepoStatusDisplay | None = None
    conditions: list[GitRepoCondition] | None = Field(
        default=None, description="List of conditions describing the current state"
    )
    resource_counts: GitRepoResourceCounts | None = Field(
        default=None, alias="resourceCounts"
    )
    resource_status_map: list[GitRepoResourceStatusMap] | None = Field(
        default=None,
        alias="resourceStatusMap",
        description="Detailed status map of individual resources managed by this GitRepo",
    )
    state: GitRepoState | None = None
    summary: dict[str, Any] | None = Field(
        default=None, description="Summary information for the GitRepo"
    )


class GitRepoSecretConfig(BaseModel):
    type: SecretType | None = "SECRET_TYPE_UNSPECIFIED"
    name: str | None = Field(default=None, description="Name of the secret")


class GitRepoTargetConfig(BaseModel):
    type: GitRepoTargetType
    value: str | None = Field(
        default=None,
        description="Target value (cluster ID, cluster group ID, etc.). Required when type is CLUSTER or CLUSTER_GROUP, not required for ALL_CLUSTER",
    )


class HelmAuthConfig(BaseModel):
    secret: GitRepoSecretConfig | None = None
    helm_repo_url_regex: str | None = Field(
        default=None,
        alias="helmRepoUrlRegex",
        description="Regular expression pattern to match Helm repository URLs",
    )


class HelmChartData(BaseModel):
    chart: Chart
    target_clusters: TargetClusters = Field(..., alias="targetClusters")


class HelmChartDetail(BaseModel):
    annotations: dict[str, str] | None = Field(
        default=None,
        description="Chart annotations including category, images, and licenses",
    )
    api_version: str | None = Field(
        default=None, alias="apiVersion", description="Helm chart API version"
    )
    app_version: str | None = Field(
        default=None,
        alias="appVersion",
        description="Version of the application packaged in the chart",
    )
    dependencies: list[HelmChartDependency] | None = Field(
        default=None, description="List of chart dependencies"
    )
    description: str | None = Field(
        default=None, description="Description of the Helm chart"
    )
    home: str | None = Field(default=None, description="Home page URL for the chart")
    icon: str | None = Field(default=None, description="Icon URL for the chart")
    keywords: list[str] | None = Field(
        default=None, description="Keywords associated with the chart"
    )
    maintainers: list[HelmChartMaintainer] | None = Field(
        default=None, description="List of chart maintainers"
    )
    name: str | None = Field(default=None, description="Name of the Helm chart")
    sources: list[str] | None = Field(
        default=None, description="List of source code URLs for the chart"
    )
    version: str | None = Field(default=None, description="Version of the Helm chart")


class HelmChartInfoResponse(BaseModel):
    readme: str | None = Field(
        default=None, description="README content for the Helm chart"
    )
    app_readme: str | None = Field(
        default=None,
        alias="appReadme",
        description="Application-specific README content",
    )
    questions: dict[str, Any] | None = Field(
        default=None, description="Configuration questions for the Helm chart"
    )
    values: dict[str, Any] | None = Field(
        default=None, description="Default values for the Helm chart"
    )
    chart: HelmChartDetail | None = None
    repo_identifier: str | None = Field(
        default=None,
        alias="repoIdentifier",
        description="Identifier for the Helm chart repository",
    )


class PrivateRepoRepositoryDetails(BaseModel):
    type: PrivateRepoType
    url: str = Field(..., description="Private repository URL (required)")
    branch: str | None = Field(default=None, description="Git branch to track")


class PrivateRepoSecretConfig(BaseModel):
    type: SecretType | None = "SECRET_TYPE_UNSPECIFIED"
    name: str | None = Field(default=None, description="Name of the secret resource")


class PrivateRepoSecretInfo(BaseModel):
    id: str | None = Field(default=None, description="Unique identifier of the secret")
    type: SecretType | None = "SECRET_TYPE_UNSPECIFIED"
    name: str | None = Field(default=None, description="Name of the secret resource")
    data: SecretData | None = None


class ResourceCapacityUsage(BaseModel):
    reserved: ResourceUsage | None = None
    used: ResourceUsage | None = None


class SecretMetadata(BaseModel):
    name: constr(
        pattern=r"^[a-z0-9]([-a-z0-9]*[a-z0-9])?$", min_length=1, max_length=253
    ) = Field(
        ...,
        description="Name of the Kubernetes secret. This field is required and must be a valid Kubernetes secret name.",
    )
    type: SecretType
    creation_timestamp: str | None = Field(
        default=None,
        alias="creationTimestamp",
        description="Timestamp when the secret was created",
    )
    project_id: str | None = Field(
        default=None,
        alias="projectId",
        description="Project identifier that owns this secret",
    )
    state: SecretState | None = None


class SnapshotGetResponse(BaseModel):
    name: str | None = Field(default=None, description="Name of the snapshot")
    cluster_id: str | None = Field(
        default=None, alias="clusterId", description="ID of the cluster"
    )
    node_name: str | None = Field(
        default=None,
        alias="nodeName",
        description="Name of the node where the snapshot was taken",
    )
    size: str | None = Field(default=None, description="Size of the snapshot in bytes")
    status: SnapshotStatusInfo | None = None
    location: str | None = Field(
        default=None, description="Snapshot Location in ZKS server"
    )
    k3s_version: str | None = Field(
        default=None, alias="k3sVersion", description="k3s Version"
    )
    created_at: str | None = Field(
        default=None,
        alias="createdAt",
        description="When the snapshot record was created",
    )


class SnapshotListResponse(BaseModel):
    total_count: int | None = Field(
        default=None, alias="totalCount", description="Total count of snapshots"
    )
    snapshots: list[SnapshotGetResponse] | None = Field(
        default=None, description="List of snapshot entries"
    )


class SnapshotOperationResponse(BaseModel):
    operation_id: str | None = Field(
        default=None,
        alias="operationId",
        description="Unique identifier for the async operation",
    )
    operation_type: SnapshotOperationType | None = Field(
        default="SNAPSHOT_OPERATION_TYPE_UNSPECIFIED", alias="operationType"
    )
    status: SnapshotOperationStatus | None = "SNAPSHOT_OPERATION_STATUS_UNSPECIFIED"
    phase: str | None = Field(
        default=None, description="Current phase of the operation"
    )
    cluster_id: str | None = Field(
        default=None,
        alias="clusterId",
        description="Cluster ID associated with the operation",
    )
    snapshot_id: str | None = Field(
        default=None,
        alias="snapshotId",
        description="Snapshot id generated for the operation",
    )
    snapshot_name: str | None = Field(
        default=None, alias="snapshotName", description="Snapshot Name"
    )
    message: str | None = Field(default=None, description="Status message")
    created_at: AwareDatetime | None = Field(
        default=None, alias="createdAt", description="When the operation was created"
    )
    updated_at: AwareDatetime | None = Field(
        default=None,
        alias="updatedAt",
        description="When the operation was last updated",
    )


class ZksInstance(BaseModel):
    id: constr(pattern=r"[0-9A-Za-z-]+") | None = Field(
        default=None,
        description="System defined universally unique Id of the zks instance",
    )
    project_id: constr(pattern=r"[0-9A-Za-z-]+") = Field(
        ..., alias="projectId", description="Foreign key to the project"
    )
    name: str = Field(
        ...,
        description="User defined name of the zks instance, unique across the enterprise. Once zks instance is created, name can’t be changed",
    )
    title: str | None = Field(
        default=None,
        description="User defined title of the zks instance. Title can be changed at any time",
    )
    description: str | None = Field(
        default=None, description="Detailed description of the zks instance"
    )
    tags: dict[str, str] | None = Field(
        default=None,
        description="Tags are name/value pairs that enable you to categorize resources. Tag names are case insensitive with max_length 512 and min_length 3. Tag values are case sensitive with max_length 256 and min_length 3.",
    )
    nodes: list[ZksInstanceNode] = Field(
        ..., description="A list of nodes in the zks instance"
    )
    is_imported: bool | None = Field(
        default=None,
        alias="isImported",
        description="Indicates if the ZKS instance is imported from an external source",
    )
    cluster_prefix: str | None = Field(
        default=None,
        alias="clusterPrefix",
        description="Cluster prefix for the ZKS instance",
    )


class ZksInstanceBulkUpdate(BaseModel):
    ids: list[str] | None = Field(
        default=None, description="List of ZKS instance IDs to be updated"
    )
    data: ZksInstanceBulkUpdateData | None = None


class ZksInstanceK3sBulkUpgrade(BaseModel):
    ids: list[str] | None = Field(
        default=None, description="List of ZKS instance IDs to be upgraded"
    )
    data: ZksInstanceK3sBulkUpgradeData | None = None


class ZksInstanceStatusSummaries(BaseModel):
    statuses: ZksInstanceStatusSummary | None = None


class ZsrvError(BaseModel):
    ec: ZsrvErrorCode | None = "zMsgErrorNone"
    location: str | None = Field(default=None, title="Ignore: Internal field only")
    details: str | None = Field(
        default=None, title="Field captures string description of details"
    )


class ZsrvResponse(BaseModel):
    operation_type: ZcOpsType | None = Field(
        default="OPS_TYPE_UNSPECIFIED", alias="operationType"
    )
    operation_status: ZcOpsStatus | None = Field(
        default="OPS_STATUS_UNSPECIFIED", alias="operationStatus"
    )
    object_kind: str | None = Field(
        default=None,
        alias="objectKind",
        title="zedcloud object kind on which the operation was performed",
    )
    object_id: str | None = Field(
        default=None,
        alias="objectId",
        title="Unique value identifies the object that was operated on",
    )
    object_name: str | None = Field(
        default=None, alias="objectName", title="name of the object"
    )
    object_revision: str | None = Field(
        default=None,
        alias="objectRevision",
        title="object revision post the operation, note Read operation\ndoesn't change the revision",
    )
    object_type: ObjectType | None = Field(
        default="OBJECT_TYPE_UNSPECIFIED", alias="objectType"
    )
    operation_time: str | None = Field(
        default=None, alias="operationTime", title="time of operation"
    )
    start_time: str | None = Field(
        default=None, alias="startTime", title="total time taken by operations"
    )
    end_time: str | None = Field(default=None, alias="endTime")
    user: str | None = Field(
        default=None, title="the operation is performed on behalf of this user"
    )
    http_status_code: int | None = Field(
        default=None, alias="httpStatusCode", title="http response"
    )
    http_status_msg: str | None = Field(
        default=None, alias="httpStatusMsg", title="summary of the error in text format"
    )
    job_id: str | None = Field(
        default=None, alias="jobId", title="for tracking asynchronous tasks"
    )
    error: list[ZsrvError] | None = Field(
        default=None,
        title="one or more errors will be set if the operation failed\ni.e. httpStatusCode != 2xx",
    )


class GooglerpcStatus(BaseModel):
    code: int | None = None
    message: str | None = None
    details: list[ProtobufAny] | None = None


class ClusterCapacity(BaseModel):
    pods: PodsCapacity | None = None
    cpus: ResourceCapacityUsage | None = None
    memory: ResourceCapacityUsage | None = None


class ClusterGroupStatusListResp(BaseModel):
    list_: list[ClusterGroupStatus] | None = Field(
        default=None,
        alias="list",
        description="Detailed statuses of the cluster groups",
    )
    result: ZsrvResponse | None = None
    total_count: int | None = Field(
        default=None,
        alias="totalCount",
        description="Total number of cluster groups satisfying the filter criteria",
    )
    next: Cursor | None = None


class DeploymentData(BaseModel):
    helm_chart_data: HelmChartData = Field(..., alias="helmChartData")


class DeploymentGetResponse(BaseModel):
    id: str | None = Field(default=None, description="Deployment ID")
    name: str | None = Field(default=None, description="Release name")
    title: str | None = Field(default=None, description="Title of the deployment")
    description: str | None = Field(
        default=None, description="Description of the deployment"
    )
    project_id: str | None = Field(
        default=None,
        alias="projectId",
        description="Project ID associated with the deployment",
    )
    type: K8sDeploymentType | None = "K8sDeploymentType_UNSPECIFIED"
    spec: DeploymentData | None = None
    deployment_status: str | None = Field(
        default=None, alias="deploymentStatus", description="Deployment status"
    )
    resource_status_map: list[dict[str, Any]] | None = Field(
        default=None,
        alias="resourceStatusMap",
        description="Map of resource status details",
    )
    created_at: AwareDatetime | None = Field(
        default=None, alias="createdAt", description="Creation timestamp"
    )
    updated_at: AwareDatetime | None = Field(
        default=None, alias="updatedAt", description="Last update timestamp"
    )
    created_by: str | None = Field(
        default=None, alias="createdBy", description="User who created the deployment"
    )
    updated_by: str | None = Field(
        default=None,
        alias="updatedBy",
        description="User who last updated the deployment",
    )


class DeploymentListResponse(BaseModel):
    total_count: int | None = Field(
        default=None, alias="totalCount", description="Total number of deployments"
    )
    state_summary: Summary | None = Field(default=None, alias="stateSummary")
    deployments: list[DeploymentGetResponse] | None = Field(
        default=None, description="List of deployments"
    )


class DeploymentRequest(BaseModel):
    type: K8sDeploymentType
    metadata: Metadata
    data: DeploymentData


class GitAuthConfig(BaseModel):
    secret: GitRepoSecretConfig | None = None


class GitRepoAuthConfig(BaseModel):
    encoded_certificates: str | None = Field(
        default=None,
        alias="encodedCertificates",
        description="Base64 encoded certificates for TLS authentication",
    )
    insecure_skip_tls_verify: bool | None = Field(
        default=None,
        alias="insecureSkipTlsVerify",
        description="Skip TLS certificate verification",
    )
    git: GitAuthConfig | None = None
    helm: HelmAuthConfig | None = None


class GitRepoData(BaseModel):
    project_id: str = Field(
        ...,
        alias="projectId",
        description="Project ID where the GitRepo belongs (required)",
    )
    repo_details: GitRepoRepositoryDetails = Field(..., alias="repoDetails")
    auth: GitRepoAuthConfig | None = None
    target: GitRepoTargetConfig


class GitRepoGetResponse(BaseModel):
    id: str | None = Field(default=None, description="Unique identifier of the GitRepo")
    name: str | None = Field(
        default=None, description="Name of the GitRepo configuration"
    )
    title: str | None = Field(
        default=None, description="Display title of the GitRepo configuration"
    )
    description: str | None = Field(
        default=None, description="Description of the GitRepo configuration"
    )
    workspace: str | None = Field(
        default=None, description="Workspace where the GitRepo is deployed"
    )
    data: GitRepoData | None = None
    status: GitRepoGetStatus | None = None
    events: list[GitRepoEvents] | None = Field(
        default=None, description="List of events related to the GitRepo"
    )
    created_at: AwareDatetime | None = Field(
        default=None,
        alias="createdAt",
        description="Timestamp when the GitRepo was created",
    )
    updated_at: AwareDatetime | None = Field(
        default=None,
        alias="updatedAt",
        description="Timestamp when the GitRepo was last updated",
    )
    created_by: str | None = Field(
        default=None, alias="createdBy", description="User who created the GitRepo"
    )
    updated_by: str | None = Field(
        default=None, alias="updatedBy", description="User who last updated the GitRepo"
    )


class GitRepoListResponse(BaseModel):
    total_count: int | None = Field(
        default=None, alias="totalCount", description="Total count of GitRepos"
    )
    state_summary: GitRepoListStatusSummary | None = Field(
        default=None, alias="stateSummary"
    )
    gitrepos: list[GitRepoGetResponse] | None = Field(
        default=None, description="List of GitRepo entries"
    )


class PrivateRepoAuthConfig(BaseModel):
    secret: PrivateRepoSecretConfig | None = None


class PrivateRepoAuthInfo(BaseModel):
    secret: PrivateRepoSecretInfo | None = None


class PrivateRepoSpec(BaseModel):
    repo_details: PrivateRepoRepositoryDetails = Field(..., alias="repoDetails")
    auth: PrivateRepoAuthConfig | None = None


class PrivateRepoSpecInfo(BaseModel):
    repo_details: PrivateRepoRepositoryDetails | None = Field(
        default=None, alias="repoDetails"
    )
    auth: PrivateRepoAuthInfo | None = None


class SecretCreateRequest(BaseModel):
    metadata: SecretMetadata
    data: SecretData


class SecretInfoResponse(BaseModel):
    id: str | None = Field(default=None, description="Unique identifier of the secret")
    field_type: str | None = Field(
        default=None, alias="_type", description="Type of the secret"
    )
    kind: str | None = Field(default=None, description="Kubernetes resource kind")
    metadata: SecretMetadata | None = None
    data: SSHCredentials | None = None


class SecretListResponse(BaseModel):
    secrets: list[SecretInfoResponse] | None = Field(
        default=None, description="List of secrets with their detailed information"
    )
    total_count: int | None = Field(
        default=None,
        alias="totalCount",
        description="Total number of secrets available",
    )


class ZksInstanceMetrics(BaseModel):
    id: str | None = Field(
        default=None, description="ZKS instance ID for which metrics are provided"
    )
    name: str | None = Field(
        default=None, description="ZKS instance name for which metrics are provided"
    )
    provider: str | None = Field(
        default=None, description="Provider of the zks instance"
    )
    kube_version: str | None = Field(
        default=None,
        alias="kubeVersion",
        description="Kubernetes version of the zks instance",
    )
    architecture: str | None = Field(
        default=None, description="Architecture of the zks instance"
    )
    created: AwareDatetime | None = Field(
        default=None, description="Creation time of the zks instance"
    )
    total_resources: int | None = Field(
        default=None,
        alias="totalResources",
        description="Total resources in the zks instance",
    )
    n_of_nodes: int | None = Field(
        default=None,
        alias="nOfNodes",
        description="Number of nodes in the zks instance",
    )
    deployments: int | None = Field(
        default=None, description="Number of deployments in the zks instance"
    )
    capacity: ClusterCapacity | None = None


class ZksInstanceStatus(BaseModel):
    id: str | None = Field(
        default=None,
        description="System defined universally unique Id of the zks instance",
    )
    project_id: str | None = Field(
        default=None, alias="projectId", description="Foreign key to the project"
    )
    name: str | None = Field(
        default=None,
        description="User defined name of the zks instance, unique across the enterprise. Once zks instance is created, name can’t be changed",
    )
    title: str | None = Field(
        default=None,
        description="User defined title of the zks instance. Title can be changed at any time",
    )
    description: str | None = Field(
        default=None, description="Detailed description of the zks instance"
    )
    tags: dict[str, str] | None = Field(
        default=None,
        description="Tags are name/value pairs that enable you to categorize resources.",
    )
    run_state: RunState | None = Field(
        default="RUN_STATE_UNSPECIFIED", alias="runState"
    )
    provider: str | None = Field(
        default=None, description="Provider of the zks instance"
    )
    kube_version: str | None = Field(
        default=None,
        alias="kubeVersion",
        description="Kubernetes version of the zks instance",
    )
    architecture: str | None = Field(
        default=None, description="Architecture of the zks instance"
    )
    created: AwareDatetime | None = Field(
        default=None, description="Creation time of the zks instance"
    )
    total_resources: int | None = Field(
        default=None,
        alias="totalResources",
        description="Total resources in the zks instance",
    )
    n_of_nodes: int | None = Field(
        default=None,
        alias="nOfNodes",
        description="Number of nodes in the zks instance",
    )
    deployments: int | None = Field(
        default=None, description="Number of deployments in the zks instance"
    )
    capacity: ClusterCapacity | None = None
    zks_cluster_id: str | None = Field(
        default=None, alias="zksClusterId", description="ZKS cluster ID"
    )
    project_name: str | None = Field(
        default=None,
        alias="projectName",
        description="Name of the project to which the zks instance belongs",
    )
    zks_base_url: str | None = Field(
        default=None, alias="zksBaseUrl", description="Base URL of the ZKS instance"
    )
    is_imported: bool | None = Field(
        default=None,
        alias="isImported",
        description="Indicates if the ZKS instance is imported from an external source",
    )
    fleet_workspace_name: str | None = Field(
        default=None,
        alias="fleetWorkspaceName",
        description="Name of the Fleet workspace associated with the ZKS instance",
    )
    total_number_of_nodes: int | None = Field(
        default=None,
        alias="totalNumberOfNodes",
        description="Total number of nodes in the ZKS instance",
    )
    cluster_prefix: str | None = Field(
        default=None,
        alias="clusterPrefix",
        description="Cluster prefix for the ZKS instance",
    )
    admin_state: AdminState | None = Field(
        default="ADMIN_STATE_UNSPECIFIED", alias="adminState"
    )


class ZksInstanceStatusListResp(BaseModel):
    list_: list[ZksInstanceStatus] | None = Field(
        default=None, alias="list", description="Detailed statuses of the zks instances"
    )
    result: ZsrvResponse | None = None
    summaries: ZksInstanceStatusSummaries | None = None
    total_count: int | None = Field(
        default=None,
        alias="totalCount",
        description="Total count of zks instances matching the filter",
    )
    next: Cursor | None = None


class GitRepoCreateRequest(BaseModel):
    metadata: GitRepoMetadata
    data: GitRepoData


class PrivateRepoCreateRequest(BaseModel):
    metadata: PrivateRepoMetadata
    spec: PrivateRepoSpec


class PrivateRepoGetByIdResponse(BaseModel):
    id: str | None = Field(
        default=None, description="Unique identifier of the private repository"
    )
    metadata: PrivateRepoMetadata | None = None
    spec: PrivateRepoSpecInfo | None = None
    status: PrivateRepoStatus | None = None
    repo_identifier: str | None = Field(
        default=None,
        alias="repoIdentifier",
        description="Unique identifier for the private repository",
    )


class PrivateRepoListResponse(BaseModel):
    list_: list[PrivateRepoGetByIdResponse] | None = Field(
        default=None, alias="list", description="List of private repositories"
    )
    total: int | None = Field(
        default=None, description="Total number of private repositories"
    )
