# Generated by scripts/generate.py from openapi/*.swagger.json. Do not edit.
"""ZEDEDA App Profiles Service — generated sync and async clients."""

from __future__ import annotations

import typing as _t
from collections.abc import AsyncIterator, Iterator, Mapping, Sequence

from zedcloud._service import AsyncBaseService, BaseService, FileContent
from zedcloud._generated.models import (
    AppProfile,
    AppProfileConfigSummary,
    AppProfileRead,
    AppProfileVersionListResp,
    AppProfiles,
    AssetGroup,
    AssetGroupList,
    AssetGroupRead,
    ProfileDeployment,
    ProfileDeploymentList,
    ProfileDeploymentResourceDetailedStatusResp,
    UpdateAppProfileBody,
    UpdateAssetGroupBody,
    UpdateProfileDeploymentBody,
    ZsrvResponse,
)


class AppProfilesService(BaseService):
    """ZEDEDA App Profiles Service (sync)."""

    _security = "bearer"

    def query_app_profiles(
        self,
        *,
        summary: bool | None = None,
        filter_name_pattern: str | None = None,
        filter_id: str | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        fields: Sequence[str] | None = None,
        request_id: str | None = None,
    ) -> AppProfiles:
        """Query app profiles

        Query the app profile records.

        Args:
            summary: summary flag
            filter_name_pattern: app profile name pattern
            filter_id: app profile id
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size
            fields: Fields to select: id, name, title, description

        ``GET /v1/appprofiles`` · operationId ``AppProfileService_QueryAppProfiles`` · read-only
        """
        return self._request(
            "GET",
            "/v1/appprofiles",
            query={
                "summary": summary,
                "filter.namePattern": filter_name_pattern,
                "filter.id": filter_id,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "fields": fields,
            },
            response_model=AppProfiles,
            request_id=request_id,
            operation_id="AppProfileService_QueryAppProfiles",
        )

    def iter_app_profiles(
        self,
        *,
        summary: bool | None = None,
        filter_name_pattern: str | None = None,
        filter_id: str | None = None,
        order_by: Sequence[str] | None = None,
        fields: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> Iterator[AppProfileConfigSummary]:
        """Iterate over every result of :meth:`query_app_profiles`, fetching pages lazily.

        Args:
            summary: summary flag
            filter_name_pattern: app profile name pattern
            filter_id: app profile id
            fields: Fields to select: id, name, title, description
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/appprofiles`` · operationId ``AppProfileService_QueryAppProfiles`` · read-only
        """
        return self._paginate(
            self.query_app_profiles,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            summary=summary,
            filter_name_pattern=filter_name_pattern,
            filter_id=filter_id,
            order_by=order_by,
            fields=fields,
        )

    def create_app_profile(
        self,
        body: AppProfile | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create app profile

        Create an app profile record.

        ``POST /v1/appprofiles`` · operationId ``AppProfileService_CreateAppProfile`` · modifies state
        """
        return self._request(
            "POST",
            "/v1/appprofiles",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AppProfileService_CreateAppProfile",
        )

    def get_app_profile(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> AppProfileRead:
        """Get app profile

        Get the configuration (without security details) of an app profile record.

        Args:
            id: Unique Id of the App profile

        ``GET /v1/appprofiles/id/{id}`` · operationId ``AppProfileService_GetAppProfile`` · read-only
        """
        return self._request(
            "GET",
            "/v1/appprofiles/id/{id}",
            path={"id": id},
            response_model=AppProfileRead,
            request_id=request_id,
            operation_id="AppProfileService_GetAppProfile",
        )

    def update_app_profile(
        self,
        id: str,
        body: UpdateAppProfileBody | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update app profile

        Update an app profile record. The usual pattern to update an app profile record is to
        retrieve the record and update with the modified values in a new body to update the app
        profile record. Updating the app profile automatically creates a new version of the
        original app profile.

        Args:
            id: unique id for an App profile

        ``PUT /v1/appprofiles/id/{id}`` · operationId ``AppProfileService_UpdateAppProfile`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/appprofiles/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AppProfileService_UpdateAppProfile",
        )

    def delete_app_profile(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete app profile

        Delete an app profile record.

        Args:
            id: Unique Id of the App profile

        ``DELETE /v1/appprofiles/id/{id}`` · operationId ``AppProfileService_DeleteAppProfile`` · DESTRUCTIVE
        """
        return self._request(
            "DELETE",
            "/v1/appprofiles/id/{id}",
            path={"id": id},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AppProfileService_DeleteAppProfile",
        )

    def query_app_profile_revision_by_id(
        self,
        id: str,
        *,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        name: str | None = None,
        request_id: str | None = None,
    ) -> AppProfileVersionListResp:
        """Query app profile versions by app profile id

        Query the app profile version records using app profile id

        Args:
            id: unique id for an App profile
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size
            name: user defined name for the App profile

        ``GET /v1/appprofiles/id/{id}/version`` · operationId ``AppProfileService_QueryAppProfileRevisionById`` · read-only
        """
        return self._request(
            "GET",
            "/v1/appprofiles/id/{id}/version",
            path={"id": id},
            query={
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "name": name,
            },
            response_model=AppProfileVersionListResp,
            request_id=request_id,
            operation_id="AppProfileService_QueryAppProfileRevisionById",
        )

    def get_app_profile_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> AppProfileRead:
        """Get app profile by name

        Get the configuration (without security details) of an app profile record by name.

        Args:
            name: User defined name of the app profile, unique across the enterprise. Once app
                profile is created, name can’t be changed

        ``GET /v1/appprofiles/name/{name}`` · operationId ``AppProfileService_GetAppProfileByName`` · read-only
        """
        return self._request(
            "GET",
            "/v1/appprofiles/name/{name}",
            path={"name": name},
            response_model=AppProfileRead,
            request_id=request_id,
            operation_id="AppProfileService_GetAppProfileByName",
        )

    def query_app_profile_revision_by_name(
        self,
        name: str,
        *,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        id: str | None = None,
        request_id: str | None = None,
    ) -> AppProfileVersionListResp:
        """Query app profile versions by app profile name

        Query the app profile version records using app profile name

        Args:
            name: user defined name for the App profile
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size
            id: unique id for an App profile

        ``GET /v1/appprofiles/name/{name}/version`` · operationId ``AppProfileService_QueryAppProfileRevisionByName`` · read-only
        """
        return self._request(
            "GET",
            "/v1/appprofiles/name/{name}/version",
            path={"name": name},
            query={
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "id": id,
            },
            response_model=AppProfileVersionListResp,
            request_id=request_id,
            operation_id="AppProfileService_QueryAppProfileRevisionByName",
        )

    def query_asset_groups(
        self,
        *,
        project_name_pattern: str | None = None,
        name_pattern: str | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        summary: bool | None = None,
        request_id: str | None = None,
    ) -> AssetGroupList:
        """Query asset groups

        Query the asset group records.

        Args:
            project_name_pattern: project name pattern
            name_pattern: asset group name pattern
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size
            summary: Only summary of the records required

        ``GET /v1/assetgroups`` · operationId ``AssetGroupService_QueryAssetGroups`` · read-only
        """
        return self._request(
            "GET",
            "/v1/assetgroups",
            query={
                "projectNamePattern": project_name_pattern,
                "namePattern": name_pattern,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "summary": summary,
            },
            response_model=AssetGroupList,
            request_id=request_id,
            operation_id="AssetGroupService_QueryAssetGroups",
        )

    def iter_asset_groups(
        self,
        *,
        project_name_pattern: str | None = None,
        name_pattern: str | None = None,
        order_by: Sequence[str] | None = None,
        summary: bool | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> Iterator[AssetGroup]:
        """Iterate over every result of :meth:`query_asset_groups`, fetching pages lazily.

        Args:
            project_name_pattern: project name pattern
            name_pattern: asset group name pattern
            summary: Only summary of the records required
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/assetgroups`` · operationId ``AssetGroupService_QueryAssetGroups`` · read-only
        """
        return self._paginate(
            self.query_asset_groups,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            project_name_pattern=project_name_pattern,
            name_pattern=name_pattern,
            order_by=order_by,
            summary=summary,
        )

    def create_asset_group(
        self,
        body: AssetGroup | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create asset group

        Create a asset group record. An assetGroup is a subset of entities in a project
        identified by assetIds

        ``POST /v1/assetgroups`` · operationId ``AssetGroupService_CreateAssetGroup`` · modifies state
        """
        return self._request(
            "POST",
            "/v1/assetgroups",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AssetGroupService_CreateAssetGroup",
        )

    def get_asset_group(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> AssetGroupRead:
        """Get asset group

        Get the configuration (without security details) of a asset group record.

        Args:
            id: unique Id of the asset group

        ``GET /v1/assetgroups/id/{id}`` · operationId ``AssetGroupService_GetAssetGroup`` · read-only
        """
        return self._request(
            "GET",
            "/v1/assetgroups/id/{id}",
            path={"id": id},
            response_model=AssetGroupRead,
            request_id=request_id,
            operation_id="AssetGroupService_GetAssetGroup",
        )

    def update_asset_group(
        self,
        id: str,
        body: UpdateAssetGroupBody | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update asset group

        Update a asset group record. The usual pattern to update a asset group record is to
        retrieve the record and update with the modified values in a new body to update the
        asset group record. If the asset group has a profile deployment associated with it, the
        newly added assets will automatically be applied with the corresponding app profile.
        Similarly if the assets are removed from this asset group, corresponding policies will
        be removed from these assets.

        Args:
            id: unique Id of the asset group

        ``PUT /v1/assetgroups/id/{id}`` · operationId ``AssetGroupService_UpdateAssetGroup`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/assetgroups/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AssetGroupService_UpdateAssetGroup",
        )

    def delete_asset_group(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete asset group

        Delete a asset group record.

        Args:
            id: unique Id of the asset group

        ``DELETE /v1/assetgroups/id/{id}`` · operationId ``AssetGroupService_DeleteAssetGroup`` · DESTRUCTIVE
        """
        return self._request(
            "DELETE",
            "/v1/assetgroups/id/{id}",
            path={"id": id},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AssetGroupService_DeleteAssetGroup",
        )

    def get_asset_group_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> AssetGroupRead:
        """Get asset group by name

        Get the configuration (without security details) of a asset group record by name.

        Args:
            name: User defined name of the asset group, unique across the enterprise. Once object
                is created, name can’t be changed

        ``GET /v1/assetgroups/name/{name}`` · operationId ``AssetGroupService_GetAssetGroupByName`` · read-only
        """
        return self._request(
            "GET",
            "/v1/assetgroups/name/{name}",
            path={"name": name},
            response_model=AssetGroupRead,
            request_id=request_id,
            operation_id="AssetGroupService_GetAssetGroupByName",
        )

    def query_profile_deployments(
        self,
        *,
        filter_profile_deployment_id: str | None = None,
        filter_name_pattern: str | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        request_id: str | None = None,
    ) -> ProfileDeploymentList:
        """Query profile deployments

        Query the profile deployment records.

        Args:
            filter_profile_deployment_id: Unique id of the asset, unique across the enterprise
            filter_name_pattern: deployment name pattern
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/profiledeployments`` · operationId ``ProfileDeploymentService_QueryProfileDeployments`` · read-only
        """
        return self._request(
            "GET",
            "/v1/profiledeployments",
            query={
                "filter.profileDeploymentId": filter_profile_deployment_id,
                "filter.namePattern": filter_name_pattern,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
            },
            response_model=ProfileDeploymentList,
            request_id=request_id,
            operation_id="ProfileDeploymentService_QueryProfileDeployments",
        )

    def iter_profile_deployments(
        self,
        *,
        filter_profile_deployment_id: str | None = None,
        filter_name_pattern: str | None = None,
        order_by: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> Iterator[ProfileDeployment]:
        """Iterate over every result of :meth:`query_profile_deployments`, fetching pages lazily.

        Args:
            filter_profile_deployment_id: Unique id of the asset, unique across the enterprise
            filter_name_pattern: deployment name pattern
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/profiledeployments`` · operationId ``ProfileDeploymentService_QueryProfileDeployments`` · read-only
        """
        return self._paginate(
            self.query_profile_deployments,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            filter_profile_deployment_id=filter_profile_deployment_id,
            filter_name_pattern=filter_name_pattern,
            order_by=order_by,
        )

    def create_profile_deployment(
        self,
        body: ProfileDeployment | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create profile deployment

        Create a profile deployment record. When an assetgroup is associated with the app
        profiles via profile deployments, the policies will be applied onto the assets present
        in that group.

        ``POST /v1/profiledeployments`` · operationId ``ProfileDeploymentService_CreateProfileDeployment`` · modifies state
        """
        return self._request(
            "POST",
            "/v1/profiledeployments",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="ProfileDeploymentService_CreateProfileDeployment",
        )

    def get_profile_deployment(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ProfileDeployment:
        """Get profile deployment

        Get the configuration (without security details) of a profile deployment record.

        Args:
            id: unique Id of the deployment

        ``GET /v1/profiledeployments/id/{id}`` · operationId ``ProfileDeploymentService_GetProfileDeployment`` · read-only
        """
        return self._request(
            "GET",
            "/v1/profiledeployments/id/{id}",
            path={"id": id},
            response_model=ProfileDeployment,
            request_id=request_id,
            operation_id="ProfileDeploymentService_GetProfileDeployment",
        )

    def update_profile_deployment(
        self,
        id: str,
        body: UpdateProfileDeploymentBody | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update profile deployment

        Update a profile deployment record. The usual pattern to update a profile deployment
        record is to retrieve the record and update with the modified values in a new body to
        update the profile deployment record.

        Args:
            id: unique Id of the deployment

        ``PUT /v1/profiledeployments/id/{id}`` · operationId ``ProfileDeploymentService_UpdateProfileDeployment`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/profiledeployments/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="ProfileDeploymentService_UpdateProfileDeployment",
        )

    def delete_profile_deployment(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete profile deployment

        Delete a profile deployment record.

        Args:
            id: unique Id of the deployment

        ``DELETE /v1/profiledeployments/id/{id}`` · operationId ``ProfileDeploymentService_DeleteProfileDeployment`` · DESTRUCTIVE
        """
        return self._request(
            "DELETE",
            "/v1/profiledeployments/id/{id}",
            path={"id": id},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="ProfileDeploymentService_DeleteProfileDeployment",
        )

    def query_profile_deployment_resource_status(
        self,
        id: str,
        *,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        request_id: str | None = None,
    ) -> ProfileDeploymentResourceDetailedStatusResp:
        """Query profile deployments resource status

        Query the profile deployment resourcs status.

        Args:
            id: unique Id of the deployment
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/profiledeployments/id/{id}/resourcestatus`` · operationId ``ProfileDeploymentService_QueryProfileDeploymentResourceStatus`` · read-only
        """
        return self._request(
            "GET",
            "/v1/profiledeployments/id/{id}/resourcestatus",
            path={"id": id},
            query={
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
            },
            response_model=ProfileDeploymentResourceDetailedStatusResp,
            request_id=request_id,
            operation_id="ProfileDeploymentService_QueryProfileDeploymentResourceStatus",
        )

    def get_profile_deployment_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> ProfileDeployment:
        """Get profile deployment by name

        Get the configuration (without security details) of a profile deployment record by name.

        Args:
            name: User defined name of the deployment, unique across the enterprise. Once object
                is created, name can’t be changed

        ``GET /v1/profiledeployments/name/{name}`` · operationId ``ProfileDeploymentService_GetProfileDeploymentByName`` · read-only
        """
        return self._request(
            "GET",
            "/v1/profiledeployments/name/{name}",
            path={"name": name},
            response_model=ProfileDeployment,
            request_id=request_id,
            operation_id="ProfileDeploymentService_GetProfileDeploymentByName",
        )


class AsyncAppProfilesService(AsyncBaseService):
    """ZEDEDA App Profiles Service (async)."""

    _security = "bearer"

    async def query_app_profiles(
        self,
        *,
        summary: bool | None = None,
        filter_name_pattern: str | None = None,
        filter_id: str | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        fields: Sequence[str] | None = None,
        request_id: str | None = None,
    ) -> AppProfiles:
        """Query app profiles

        Query the app profile records.

        Args:
            summary: summary flag
            filter_name_pattern: app profile name pattern
            filter_id: app profile id
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size
            fields: Fields to select: id, name, title, description

        ``GET /v1/appprofiles`` · operationId ``AppProfileService_QueryAppProfiles`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/appprofiles",
            query={
                "summary": summary,
                "filter.namePattern": filter_name_pattern,
                "filter.id": filter_id,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "fields": fields,
            },
            response_model=AppProfiles,
            request_id=request_id,
            operation_id="AppProfileService_QueryAppProfiles",
        )

    def iter_app_profiles(
        self,
        *,
        summary: bool | None = None,
        filter_name_pattern: str | None = None,
        filter_id: str | None = None,
        order_by: Sequence[str] | None = None,
        fields: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> AsyncIterator[AppProfileConfigSummary]:
        """Iterate over every result of :meth:`query_app_profiles`, fetching pages lazily.

        Args:
            summary: summary flag
            filter_name_pattern: app profile name pattern
            filter_id: app profile id
            fields: Fields to select: id, name, title, description
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/appprofiles`` · operationId ``AppProfileService_QueryAppProfiles`` · read-only
        """
        return self._paginate(
            self.query_app_profiles,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            summary=summary,
            filter_name_pattern=filter_name_pattern,
            filter_id=filter_id,
            order_by=order_by,
            fields=fields,
        )

    async def create_app_profile(
        self,
        body: AppProfile | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create app profile

        Create an app profile record.

        ``POST /v1/appprofiles`` · operationId ``AppProfileService_CreateAppProfile`` · modifies state
        """
        return await self._request(
            "POST",
            "/v1/appprofiles",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AppProfileService_CreateAppProfile",
        )

    async def get_app_profile(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> AppProfileRead:
        """Get app profile

        Get the configuration (without security details) of an app profile record.

        Args:
            id: Unique Id of the App profile

        ``GET /v1/appprofiles/id/{id}`` · operationId ``AppProfileService_GetAppProfile`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/appprofiles/id/{id}",
            path={"id": id},
            response_model=AppProfileRead,
            request_id=request_id,
            operation_id="AppProfileService_GetAppProfile",
        )

    async def update_app_profile(
        self,
        id: str,
        body: UpdateAppProfileBody | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update app profile

        Update an app profile record. The usual pattern to update an app profile record is to
        retrieve the record and update with the modified values in a new body to update the app
        profile record. Updating the app profile automatically creates a new version of the
        original app profile.

        Args:
            id: unique id for an App profile

        ``PUT /v1/appprofiles/id/{id}`` · operationId ``AppProfileService_UpdateAppProfile`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/appprofiles/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AppProfileService_UpdateAppProfile",
        )

    async def delete_app_profile(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete app profile

        Delete an app profile record.

        Args:
            id: Unique Id of the App profile

        ``DELETE /v1/appprofiles/id/{id}`` · operationId ``AppProfileService_DeleteAppProfile`` · DESTRUCTIVE
        """
        return await self._request(
            "DELETE",
            "/v1/appprofiles/id/{id}",
            path={"id": id},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AppProfileService_DeleteAppProfile",
        )

    async def query_app_profile_revision_by_id(
        self,
        id: str,
        *,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        name: str | None = None,
        request_id: str | None = None,
    ) -> AppProfileVersionListResp:
        """Query app profile versions by app profile id

        Query the app profile version records using app profile id

        Args:
            id: unique id for an App profile
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size
            name: user defined name for the App profile

        ``GET /v1/appprofiles/id/{id}/version`` · operationId ``AppProfileService_QueryAppProfileRevisionById`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/appprofiles/id/{id}/version",
            path={"id": id},
            query={
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "name": name,
            },
            response_model=AppProfileVersionListResp,
            request_id=request_id,
            operation_id="AppProfileService_QueryAppProfileRevisionById",
        )

    async def get_app_profile_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> AppProfileRead:
        """Get app profile by name

        Get the configuration (without security details) of an app profile record by name.

        Args:
            name: User defined name of the app profile, unique across the enterprise. Once app
                profile is created, name can’t be changed

        ``GET /v1/appprofiles/name/{name}`` · operationId ``AppProfileService_GetAppProfileByName`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/appprofiles/name/{name}",
            path={"name": name},
            response_model=AppProfileRead,
            request_id=request_id,
            operation_id="AppProfileService_GetAppProfileByName",
        )

    async def query_app_profile_revision_by_name(
        self,
        name: str,
        *,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        id: str | None = None,
        request_id: str | None = None,
    ) -> AppProfileVersionListResp:
        """Query app profile versions by app profile name

        Query the app profile version records using app profile name

        Args:
            name: user defined name for the App profile
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size
            id: unique id for an App profile

        ``GET /v1/appprofiles/name/{name}/version`` · operationId ``AppProfileService_QueryAppProfileRevisionByName`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/appprofiles/name/{name}/version",
            path={"name": name},
            query={
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "id": id,
            },
            response_model=AppProfileVersionListResp,
            request_id=request_id,
            operation_id="AppProfileService_QueryAppProfileRevisionByName",
        )

    async def query_asset_groups(
        self,
        *,
        project_name_pattern: str | None = None,
        name_pattern: str | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        summary: bool | None = None,
        request_id: str | None = None,
    ) -> AssetGroupList:
        """Query asset groups

        Query the asset group records.

        Args:
            project_name_pattern: project name pattern
            name_pattern: asset group name pattern
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size
            summary: Only summary of the records required

        ``GET /v1/assetgroups`` · operationId ``AssetGroupService_QueryAssetGroups`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/assetgroups",
            query={
                "projectNamePattern": project_name_pattern,
                "namePattern": name_pattern,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "summary": summary,
            },
            response_model=AssetGroupList,
            request_id=request_id,
            operation_id="AssetGroupService_QueryAssetGroups",
        )

    def iter_asset_groups(
        self,
        *,
        project_name_pattern: str | None = None,
        name_pattern: str | None = None,
        order_by: Sequence[str] | None = None,
        summary: bool | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> AsyncIterator[AssetGroup]:
        """Iterate over every result of :meth:`query_asset_groups`, fetching pages lazily.

        Args:
            project_name_pattern: project name pattern
            name_pattern: asset group name pattern
            summary: Only summary of the records required
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/assetgroups`` · operationId ``AssetGroupService_QueryAssetGroups`` · read-only
        """
        return self._paginate(
            self.query_asset_groups,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            project_name_pattern=project_name_pattern,
            name_pattern=name_pattern,
            order_by=order_by,
            summary=summary,
        )

    async def create_asset_group(
        self,
        body: AssetGroup | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create asset group

        Create a asset group record. An assetGroup is a subset of entities in a project
        identified by assetIds

        ``POST /v1/assetgroups`` · operationId ``AssetGroupService_CreateAssetGroup`` · modifies state
        """
        return await self._request(
            "POST",
            "/v1/assetgroups",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AssetGroupService_CreateAssetGroup",
        )

    async def get_asset_group(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> AssetGroupRead:
        """Get asset group

        Get the configuration (without security details) of a asset group record.

        Args:
            id: unique Id of the asset group

        ``GET /v1/assetgroups/id/{id}`` · operationId ``AssetGroupService_GetAssetGroup`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/assetgroups/id/{id}",
            path={"id": id},
            response_model=AssetGroupRead,
            request_id=request_id,
            operation_id="AssetGroupService_GetAssetGroup",
        )

    async def update_asset_group(
        self,
        id: str,
        body: UpdateAssetGroupBody | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update asset group

        Update a asset group record. The usual pattern to update a asset group record is to
        retrieve the record and update with the modified values in a new body to update the
        asset group record. If the asset group has a profile deployment associated with it, the
        newly added assets will automatically be applied with the corresponding app profile.
        Similarly if the assets are removed from this asset group, corresponding policies will
        be removed from these assets.

        Args:
            id: unique Id of the asset group

        ``PUT /v1/assetgroups/id/{id}`` · operationId ``AssetGroupService_UpdateAssetGroup`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/assetgroups/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AssetGroupService_UpdateAssetGroup",
        )

    async def delete_asset_group(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete asset group

        Delete a asset group record.

        Args:
            id: unique Id of the asset group

        ``DELETE /v1/assetgroups/id/{id}`` · operationId ``AssetGroupService_DeleteAssetGroup`` · DESTRUCTIVE
        """
        return await self._request(
            "DELETE",
            "/v1/assetgroups/id/{id}",
            path={"id": id},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="AssetGroupService_DeleteAssetGroup",
        )

    async def get_asset_group_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> AssetGroupRead:
        """Get asset group by name

        Get the configuration (without security details) of a asset group record by name.

        Args:
            name: User defined name of the asset group, unique across the enterprise. Once object
                is created, name can’t be changed

        ``GET /v1/assetgroups/name/{name}`` · operationId ``AssetGroupService_GetAssetGroupByName`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/assetgroups/name/{name}",
            path={"name": name},
            response_model=AssetGroupRead,
            request_id=request_id,
            operation_id="AssetGroupService_GetAssetGroupByName",
        )

    async def query_profile_deployments(
        self,
        *,
        filter_profile_deployment_id: str | None = None,
        filter_name_pattern: str | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        request_id: str | None = None,
    ) -> ProfileDeploymentList:
        """Query profile deployments

        Query the profile deployment records.

        Args:
            filter_profile_deployment_id: Unique id of the asset, unique across the enterprise
            filter_name_pattern: deployment name pattern
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/profiledeployments`` · operationId ``ProfileDeploymentService_QueryProfileDeployments`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/profiledeployments",
            query={
                "filter.profileDeploymentId": filter_profile_deployment_id,
                "filter.namePattern": filter_name_pattern,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
            },
            response_model=ProfileDeploymentList,
            request_id=request_id,
            operation_id="ProfileDeploymentService_QueryProfileDeployments",
        )

    def iter_profile_deployments(
        self,
        *,
        filter_profile_deployment_id: str | None = None,
        filter_name_pattern: str | None = None,
        order_by: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> AsyncIterator[ProfileDeployment]:
        """Iterate over every result of :meth:`query_profile_deployments`, fetching pages lazily.

        Args:
            filter_profile_deployment_id: Unique id of the asset, unique across the enterprise
            filter_name_pattern: deployment name pattern
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/profiledeployments`` · operationId ``ProfileDeploymentService_QueryProfileDeployments`` · read-only
        """
        return self._paginate(
            self.query_profile_deployments,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            filter_profile_deployment_id=filter_profile_deployment_id,
            filter_name_pattern=filter_name_pattern,
            order_by=order_by,
        )

    async def create_profile_deployment(
        self,
        body: ProfileDeployment | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create profile deployment

        Create a profile deployment record. When an assetgroup is associated with the app
        profiles via profile deployments, the policies will be applied onto the assets present
        in that group.

        ``POST /v1/profiledeployments`` · operationId ``ProfileDeploymentService_CreateProfileDeployment`` · modifies state
        """
        return await self._request(
            "POST",
            "/v1/profiledeployments",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="ProfileDeploymentService_CreateProfileDeployment",
        )

    async def get_profile_deployment(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ProfileDeployment:
        """Get profile deployment

        Get the configuration (without security details) of a profile deployment record.

        Args:
            id: unique Id of the deployment

        ``GET /v1/profiledeployments/id/{id}`` · operationId ``ProfileDeploymentService_GetProfileDeployment`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/profiledeployments/id/{id}",
            path={"id": id},
            response_model=ProfileDeployment,
            request_id=request_id,
            operation_id="ProfileDeploymentService_GetProfileDeployment",
        )

    async def update_profile_deployment(
        self,
        id: str,
        body: UpdateProfileDeploymentBody | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update profile deployment

        Update a profile deployment record. The usual pattern to update a profile deployment
        record is to retrieve the record and update with the modified values in a new body to
        update the profile deployment record.

        Args:
            id: unique Id of the deployment

        ``PUT /v1/profiledeployments/id/{id}`` · operationId ``ProfileDeploymentService_UpdateProfileDeployment`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/profiledeployments/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="ProfileDeploymentService_UpdateProfileDeployment",
        )

    async def delete_profile_deployment(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete profile deployment

        Delete a profile deployment record.

        Args:
            id: unique Id of the deployment

        ``DELETE /v1/profiledeployments/id/{id}`` · operationId ``ProfileDeploymentService_DeleteProfileDeployment`` · DESTRUCTIVE
        """
        return await self._request(
            "DELETE",
            "/v1/profiledeployments/id/{id}",
            path={"id": id},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="ProfileDeploymentService_DeleteProfileDeployment",
        )

    async def query_profile_deployment_resource_status(
        self,
        id: str,
        *,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        request_id: str | None = None,
    ) -> ProfileDeploymentResourceDetailedStatusResp:
        """Query profile deployments resource status

        Query the profile deployment resourcs status.

        Args:
            id: unique Id of the deployment
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/profiledeployments/id/{id}/resourcestatus`` · operationId ``ProfileDeploymentService_QueryProfileDeploymentResourceStatus`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/profiledeployments/id/{id}/resourcestatus",
            path={"id": id},
            query={
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
            },
            response_model=ProfileDeploymentResourceDetailedStatusResp,
            request_id=request_id,
            operation_id="ProfileDeploymentService_QueryProfileDeploymentResourceStatus",
        )

    async def get_profile_deployment_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> ProfileDeployment:
        """Get profile deployment by name

        Get the configuration (without security details) of a profile deployment record by name.

        Args:
            name: User defined name of the deployment, unique across the enterprise. Once object
                is created, name can’t be changed

        ``GET /v1/profiledeployments/name/{name}`` · operationId ``ProfileDeploymentService_GetProfileDeploymentByName`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/profiledeployments/name/{name}",
            path={"name": name},
            response_model=ProfileDeployment,
            request_id=request_id,
            operation_id="ProfileDeploymentService_GetProfileDeploymentByName",
        )
