# Generated by scripts/generate_from_openapi.py — namespace "apps"
# Do not edit by hand.

from __future__ import annotations

from typing import Any

from zedcloud.services.base import BaseService
from zedcloud._generated.models.apps import (
    App,
    AppHttpRequest,
    AppInstConfigStatusList,
    AppInstSnapshotsList,
    AppInstStatusListMsg,
    AppInstStatusMsg,
    AppInstance,
    AppInstanceLogsResponse,
    AppInstanceSnapshot,
    AppInstanceSnapshotState,
    AppInstanceUpdateHttpRequest,
    AppInstances,
    AppProjectList,
    AppPublicApps,
    Apps,
    ClassificationResponse,
    EventQueryResponse,
    MetricQueryResponse,
    ObjectTagsList,
    OpaqueAppInstanceStatus,
    PatchEnvelope,
    PatchEnvelopeList,
    PatchReferenceUpdateConfig,
    PatchStatusListMsg,
    TopTalkersResponse,
    ZsrvResponse,
)


class AppsService(BaseService):
    """Auto-generated client for ZEDEDA Edge Application Service."""

    def query_beta_edge_application_bundles(
        self,
        name_pattern: str | None = None,
        origin_type: int | None = None,
        category: str | None = None,
        summary: bool | None = None,
        app_type: str | None = None,
        deployment_type: str | None = None,
        app_category: list[str] | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        title_pattern: str | None = None,
        match_any_tag: bool | None = None,
        request_id: str | None = None,
    ) -> AppPublicApps:
        """Query edge application bundles

        ``GET /beta/apps``
        operationId: ``EdgeApplicationConfiguration_QueryBetaEdgeApplicationBundles``
        """
        path = "/beta/apps"
        params: dict[str, Any] = {}
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if origin_type is not None:
            params["originType"] = origin_type
        if category is not None:
            params["category"] = category
        if summary is not None:
            params["summary"] = summary
        if app_type is not None:
            params["appType"] = app_type
        if deployment_type is not None:
            params["deploymentType"] = deployment_type
        if app_category is not None:
            params["appCategory"] = app_category
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if title_pattern is not None:
            params["titlePattern"] = title_pattern
        if match_any_tag is not None:
            params["matchAnyTag"] = match_any_tag
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppPublicApps)

    def query_edge_application_bundles(
        self,
        name_pattern: str | None = None,
        origin_type: int | None = None,
        category: str | None = None,
        summary: bool | None = None,
        app_type: str | None = None,
        deployment_type: str | None = None,
        app_category: list[str] | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        title_pattern: str | None = None,
        match_any_tag: bool | None = None,
        request_id: str | None = None,
    ) -> Apps:
        """Query edge application bundles

        ``GET /v1/apps``
        operationId: ``EdgeApplicationConfiguration_QueryEdgeApplicationBundles``
        """
        path = "/v1/apps"
        params: dict[str, Any] = {}
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if origin_type is not None:
            params["originType"] = origin_type
        if category is not None:
            params["category"] = category
        if summary is not None:
            params["summary"] = summary
        if app_type is not None:
            params["appType"] = app_type
        if deployment_type is not None:
            params["deploymentType"] = deployment_type
        if app_category is not None:
            params["appCategory"] = app_category
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if title_pattern is not None:
            params["titlePattern"] = title_pattern
        if match_any_tag is not None:
            params["matchAnyTag"] = match_any_tag
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=Apps)

    def create_edge_application_bundle(self, body: App | dict[str, Any], request_id: str | None = None) -> ZsrvResponse:
        """Create edge application bundle

        ``POST /v1/apps``
        operationId: ``EdgeApplicationConfiguration_CreateEdgeApplicationBundle``
        """
        path = "/v1/apps"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("POST", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def query_global_edge_application_bundles(
        self,
        name_pattern: str | None = None,
        origin_type: int | None = None,
        category: str | None = None,
        summary: bool | None = None,
        app_type: str | None = None,
        deployment_type: str | None = None,
        app_category: list[str] | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        title_pattern: str | None = None,
        match_any_tag: bool | None = None,
        request_id: str | None = None,
    ) -> Apps:
        """Query global edge application bundles

        ``GET /v1/apps/global``
        operationId: ``EdgeApplicationConfiguration_QueryGlobalEdgeApplicationBundles``
        """
        path = "/v1/apps/global"
        params: dict[str, Any] = {}
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if origin_type is not None:
            params["originType"] = origin_type
        if category is not None:
            params["category"] = category
        if summary is not None:
            params["summary"] = summary
        if app_type is not None:
            params["appType"] = app_type
        if deployment_type is not None:
            params["deploymentType"] = deployment_type
        if app_category is not None:
            params["appCategory"] = app_category
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if title_pattern is not None:
            params["titlePattern"] = title_pattern
        if match_any_tag is not None:
            params["matchAnyTag"] = match_any_tag
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=Apps)

    def get_global_edge_application_bundle(self, id: str, request_id: str | None = None) -> App:
        """Get global edge application bundle

        ``GET /v1/apps/global/id/{id}``
        operationId: ``EdgeApplicationConfiguration_GetGlobalEdgeApplicationBundle``
        """
        path = f"/v1/apps/global/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=App)

    def get_global_edge_application_bundle_by_name(self, name: str, request_id: str | None = None) -> App:
        """Get global edge application bundle

        ``GET /v1/apps/global/name/{name}``
        operationId: ``EdgeApplicationConfiguration_GetGlobalEdgeApplicationBundleByName``
        """
        path = f"/v1/apps/global/name/{name}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=App)

    def get_edge_application_bundle(self, id: str, request_id: str | None = None) -> App:
        """Get edge application bundle

        ``GET /v1/apps/id/{id}``
        operationId: ``EdgeApplicationConfiguration_GetEdgeApplicationBundle``
        """
        path = f"/v1/apps/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=App)

    def delete_edge_application_bundle(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Delete edge application bundle

        ``DELETE /v1/apps/id/{id}``
        operationId: ``EdgeApplicationConfiguration_DeleteEdgeApplicationBundle``
        """
        path = f"/v1/apps/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("DELETE", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def update_edge_application_bundle(self, id: str, body: AppHttpRequest | dict[str, Any], request_id: str | None = None) -> ZsrvResponse:
        """Update edge application bundle

        ``PUT /v1/apps/id/{id}``
        operationId: ``EdgeApplicationConfiguration_UpdateEdgeApplicationBundle``
        """
        path = f"/v1/apps/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def query_edge_application_bundle_project_list(
        self,
        id: str,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> AppProjectList:
        """Query the project access list of an edge application bundle

        ``GET /v1/apps/id/{id}/projects``
        operationId: ``EdgeApplicationConfiguration_QueryEdgeApplicationBundleProjectList``
        """
        path = f"/v1/apps/id/{id}/projects"
        params: dict[str, Any] = {}
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppProjectList)

    def query_edge_application_instances(
        self,
        project: str | None = None,
        bundle: str | None = None,
        device: str | None = None,
        name_pattern: str | None = None,
        app_type: int | None = None,
        deployment_type: str | None = None,
        project_name_pattern: str | None = None,
        device_name_pattern: str | None = None,
        summary: bool | None = None,
        title_pattern: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        fields: list[str] | None = None,
        request_id: str | None = None,
    ) -> AppInstances:
        """Query edge application instances

        ``GET /v1/apps/instances``
        operationId: ``EdgeApplicationInstanceConfiguration_QueryEdgeApplicationInstances``
        """
        path = "/v1/apps/instances"
        params: dict[str, Any] = {}
        if project is not None:
            params["project"] = project
        if bundle is not None:
            params["bundle"] = bundle
        if device is not None:
            params["device"] = device
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if app_type is not None:
            params["appType"] = app_type
        if deployment_type is not None:
            params["deploymentType"] = deployment_type
        if project_name_pattern is not None:
            params["projectNamePattern"] = project_name_pattern
        if device_name_pattern is not None:
            params["deviceNamePattern"] = device_name_pattern
        if summary is not None:
            params["summary"] = summary
        if title_pattern is not None:
            params["titlePattern"] = title_pattern
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if fields is not None:
            params["fields"] = fields
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstances)

    def create_edge_application_instance(self, body: AppInstance | dict[str, Any], request_id: str | None = None) -> ZsrvResponse:
        """Create edge application instance

        ``POST /v1/apps/instances``
        operationId: ``EdgeApplicationInstanceConfiguration_CreateEdgeApplicationInstance``
        """
        path = "/v1/apps/instances"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("POST", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_app_instance_snapshot(self, app_instance_id: str, name: str, request_id: str | None = None) -> AppInstanceSnapshot:
        """Query Application instance snapshot

        ``GET /v1/apps/instances/id/{appInstanceId}/snapshot/name/{name}``
        operationId: ``EdgeApplicationInstanceStatus_GetAppInstanceSnapshot``
        """
        path = f"/v1/apps/instances/id/{app_instance_id}/snapshot/name/{name}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstanceSnapshot)

    def edge_application_instance_status__delete_app_instance_snapshot(self, app_instance_id: str, name: str, request_id: str | None = None) -> ZsrvResponse:
        """Delete Application instance snapshot

        ``DELETE /v1/apps/instances/id/{appInstanceId}/snapshot/name/{name}``
        operationId: ``EdgeApplicationInstanceStatus_DeleteAppInstanceSnapshot``
        """
        path = f"/v1/apps/instances/id/{app_instance_id}/snapshot/name/{name}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("DELETE", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def get_edge_application_instance(self, id: str, request_id: str | None = None) -> AppInstance:
        """Get edge application instance

        ``GET /v1/apps/instances/id/{id}``
        operationId: ``EdgeApplicationInstanceConfiguration_GetEdgeApplicationInstance``
        """
        path = f"/v1/apps/instances/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstance)

    def delete_edge_application_instance(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Delete edge application instance

        ``DELETE /v1/apps/instances/id/{id}``
        operationId: ``EdgeApplicationInstanceConfiguration_DeleteEdgeApplicationInstance``
        """
        path = f"/v1/apps/instances/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("DELETE", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def update_edge_application_instance(
        self,
        id: str,
        body: AppInstanceUpdateHttpRequest | dict[str, Any],
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update edge application instance

        ``PUT /v1/apps/instances/id/{id}``
        operationId: ``EdgeApplicationInstanceConfiguration_UpdateEdgeApplicationInstance``
        """
        path = f"/v1/apps/instances/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def activate_edge_application_instance(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Activate edge application instance

        ``PUT /v1/apps/instances/id/{id}/activate``
        operationId: ``EdgeApplicationInstanceConfiguration_ActivateEdgeApplicationInstance``
        """
        path = f"/v1/apps/instances/id/{id}/activate"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def connect_to_edge_application_instance(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Connect to edge application instance console

        ``PUT /v1/apps/instances/id/{id}/console/remote``
        operationId: ``EdgeApplicationInstanceConfiguration_ConnectToEdgeApplicationInstance``
        """
        path = f"/v1/apps/instances/id/{id}/console/remote"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def de_activate_edge_application_instance(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Deactivate edge application instance

        ``PUT /v1/apps/instances/id/{id}/deactivate``
        operationId: ``EdgeApplicationInstanceConfiguration_DeActivateEdgeApplicationInstance``
        """
        path = f"/v1/apps/instances/id/{id}/deactivate"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def get_edge_application_instance_traffic_flows(
        self,
        id: str,
        name: str | None = None,
        start_time: str | None = None,
        end_time: str | None = None,
        levels: list[str] | None = None,
        enterprise_id: str | None = None,
        metric: int | None = None,
        direction: int | None = None,
        aclid: int | None = None,
        action: str | None = None,
        proto: int | None = None,
        remoteip: str | None = None,
        remoteport: int | None = None,
        fqdn: str | None = None,
        request_id: str | None = None,
    ) -> ClassificationResponse:
        """Get edge application instance network traffic flow log

        ``GET /v1/apps/instances/id/{id}/flowlog/classification``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceTrafficFlows``
        """
        path = f"/v1/apps/instances/id/{id}/flowlog/classification"
        params: dict[str, Any] = {}
        if name is not None:
            params["name"] = name
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if levels is not None:
            params["levels"] = levels
        if enterprise_id is not None:
            params["enterpriseId"] = enterprise_id
        if metric is not None:
            params["metric"] = metric
        if direction is not None:
            params["direction"] = direction
        if aclid is not None:
            params["aclid"] = aclid
        if action is not None:
            params["action"] = action
        if proto is not None:
            params["proto"] = proto
        if remoteip is not None:
            params["remoteip"] = remoteip
        if remoteport is not None:
            params["remoteport"] = remoteport
        if fqdn is not None:
            params["fqdn"] = fqdn
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=ClassificationResponse)

    def get_edge_application_instance_top_talkers(
        self,
        id: str,
        name: str | None = None,
        start_time: str | None = None,
        end_time: str | None = None,
        metric_type: str | None = None,
        enterprise_id: str | None = None,
        cursor_page_token: str | None = None,
        cursor_order_by: list[str] | None = None,
        cursor_page_num: float | None = None,
        cursor_page_size: float | None = None,
        cursor_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> TopTalkersResponse:
        """Get edge application instance top talkers of the network traffic flows

        ``GET /v1/apps/instances/id/{id}/flowlog/toptalkers``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceTopTalkers``
        """
        path = f"/v1/apps/instances/id/{id}/flowlog/toptalkers"
        params: dict[str, Any] = {}
        if name is not None:
            params["name"] = name
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if metric_type is not None:
            params["metricType"] = metric_type
        if enterprise_id is not None:
            params["enterpriseId"] = enterprise_id
        if cursor_page_token is not None:
            params["Cursor.pageToken"] = cursor_page_token
        if cursor_order_by is not None:
            params["Cursor.orderBy"] = cursor_order_by
        if cursor_page_num is not None:
            params["Cursor.pageNum"] = cursor_page_num
        if cursor_page_size is not None:
            params["Cursor.pageSize"] = cursor_page_size
        if cursor_total_pages is not None:
            params["Cursor.totalPages"] = cursor_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=TopTalkersResponse)

    def get_edge_application_instance_logs(
        self,
        id: str,
        start_time: str | None = None,
        end_time: str | None = None,
        interval: str | None = None,
        cursor_page_token: str | None = None,
        cursor_order_by: list[str] | None = None,
        cursor_page_num: float | None = None,
        cursor_page_size: float | None = None,
        cursor_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> AppInstanceLogsResponse:
        """Get edge application instance log

        ``GET /v1/apps/instances/id/{id}/logs``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceLogs``
        """
        path = f"/v1/apps/instances/id/{id}/logs"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if interval is not None:
            params["interval"] = interval
        if cursor_page_token is not None:
            params["Cursor.pageToken"] = cursor_page_token
        if cursor_order_by is not None:
            params["Cursor.orderBy"] = cursor_order_by
        if cursor_page_num is not None:
            params["Cursor.pageNum"] = cursor_page_num
        if cursor_page_size is not None:
            params["Cursor.pageSize"] = cursor_page_size
        if cursor_total_pages is not None:
            params["Cursor.totalPages"] = cursor_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstanceLogsResponse)

    def get_edge_application_instance_opaque_status_by_id(self, id: str, request_id: str | None = None) -> OpaqueAppInstanceStatus:
        """Get patch envelope opaque status as base64 encoded string

        ``GET /v1/apps/instances/id/{id}/opaque-status``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceOpaqueStatusById``
        """
        path = f"/v1/apps/instances/id/{id}/opaque-status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=OpaqueAppInstanceStatus)

    def refresh_edge_application_instance(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Refresh edge application instance

        ``PUT /v1/apps/instances/id/{id}/refresh``
        operationId: ``EdgeApplicationInstanceConfiguration_RefreshEdgeApplicationInstance``
        """
        path = f"/v1/apps/instances/id/{id}/refresh"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def refresh_purge_edge_application_instance(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Refresh and purge edge application instance

        ``PUT /v1/apps/instances/id/{id}/refresh/purge``
        operationId: ``EdgeApplicationInstanceConfiguration_RefreshPurgeEdgeApplicationInstance``
        """
        path = f"/v1/apps/instances/id/{id}/refresh/purge"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def restart_edge_application_instance(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Restart edge application instance

        ``PUT /v1/apps/instances/id/{id}/restart``
        operationId: ``EdgeApplicationInstanceConfiguration_RestartEdgeApplicationInstance``
        """
        path = f"/v1/apps/instances/id/{id}/restart"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def get_app_instance_snapshots(self, id: str, request_id: str | None = None) -> AppInstSnapshotsList:
        """Query Application instance snapshots

        ``GET /v1/apps/instances/id/{id}/snapshots``
        operationId: ``EdgeApplicationInstanceStatus_GetAppInstanceSnapshots``
        """
        path = f"/v1/apps/instances/id/{id}/snapshots"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstSnapshotsList)

    def get_edge_application_instance_status(self, id: str, request_id: str | None = None) -> AppInstStatusMsg:
        """Get edge application instance status

        ``GET /v1/apps/instances/id/{id}/status``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceStatus``
        """
        path = f"/v1/apps/instances/id/{id}/status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstStatusMsg)

    def get_edge_application_instance_events(
        self,
        objid: str,
        start_time: str | None = None,
        end_time: str | None = None,
        severity: str | None = None,
        resource: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> EventQueryResponse:
        """Get edge application instance events by id

        ``GET /v1/apps/instances/id/{objid}/events``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceEvents``
        """
        path = f"/v1/apps/instances/id/{objid}/events"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if severity is not None:
            params["severity"] = severity
        if resource is not None:
            params["resource"] = resource
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EventQueryResponse)

    def get_edge_application_instance_resource_metrics_by_id(
        self,
        objid: str,
        m_type: str,
        start_time: str | None = None,
        end_time: str | None = None,
        interval: str | None = None,
        request_id: str | None = None,
    ) -> MetricQueryResponse:
        """Get edge application instance resource usage timeline

        ``GET /v1/apps/instances/id/{objid}/timeSeries/{mType}``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceResourceMetricsById``
        """
        path = f"/v1/apps/instances/id/{objid}/timeSeries/{m_type}"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if interval is not None:
            params["interval"] = interval
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=MetricQueryResponse)

    def get_edge_application_instance_by_name(self, name: str, request_id: str | None = None) -> AppInstance:
        """Get edge application instance

        ``GET /v1/apps/instances/name/{name}``
        operationId: ``EdgeApplicationInstanceConfiguration_GetEdgeApplicationInstanceByName``
        """
        path = f"/v1/apps/instances/name/{name}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstance)

    def get_edge_application_instance_traffic_flows2(
        self,
        name: str,
        id: str | None = None,
        start_time: str | None = None,
        end_time: str | None = None,
        levels: list[str] | None = None,
        enterprise_id: str | None = None,
        metric: int | None = None,
        direction: int | None = None,
        aclid: int | None = None,
        action: str | None = None,
        proto: int | None = None,
        remoteip: str | None = None,
        remoteport: int | None = None,
        fqdn: str | None = None,
        request_id: str | None = None,
    ) -> ClassificationResponse:
        """Get edge application instance network traffic flow log

        ``GET /v1/apps/instances/name/{name}/flowlog/classification``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceTrafficFlows2``
        """
        path = f"/v1/apps/instances/name/{name}/flowlog/classification"
        params: dict[str, Any] = {}
        if id is not None:
            params["id"] = id
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if levels is not None:
            params["levels"] = levels
        if enterprise_id is not None:
            params["enterpriseId"] = enterprise_id
        if metric is not None:
            params["metric"] = metric
        if direction is not None:
            params["direction"] = direction
        if aclid is not None:
            params["aclid"] = aclid
        if action is not None:
            params["action"] = action
        if proto is not None:
            params["proto"] = proto
        if remoteip is not None:
            params["remoteip"] = remoteip
        if remoteport is not None:
            params["remoteport"] = remoteport
        if fqdn is not None:
            params["fqdn"] = fqdn
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=ClassificationResponse)

    def get_edge_application_instance_top_talkers2(
        self,
        name: str,
        id: str | None = None,
        start_time: str | None = None,
        end_time: str | None = None,
        metric_type: str | None = None,
        enterprise_id: str | None = None,
        cursor_page_token: str | None = None,
        cursor_order_by: list[str] | None = None,
        cursor_page_num: float | None = None,
        cursor_page_size: float | None = None,
        cursor_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> TopTalkersResponse:
        """Get edge application instance top talkers of the network traffic flows

        ``GET /v1/apps/instances/name/{name}/flowlog/toptalkers``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceTopTalkers2``
        """
        path = f"/v1/apps/instances/name/{name}/flowlog/toptalkers"
        params: dict[str, Any] = {}
        if id is not None:
            params["id"] = id
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if metric_type is not None:
            params["metricType"] = metric_type
        if enterprise_id is not None:
            params["enterpriseId"] = enterprise_id
        if cursor_page_token is not None:
            params["Cursor.pageToken"] = cursor_page_token
        if cursor_order_by is not None:
            params["Cursor.orderBy"] = cursor_order_by
        if cursor_page_num is not None:
            params["Cursor.pageNum"] = cursor_page_num
        if cursor_page_size is not None:
            params["Cursor.pageSize"] = cursor_page_size
        if cursor_total_pages is not None:
            params["Cursor.totalPages"] = cursor_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=TopTalkersResponse)

    def get_edge_application_instance_opaque_status_by_name(self, name: str, request_id: str | None = None) -> OpaqueAppInstanceStatus:
        """Get patch envelope opaque status as base64 encoded string

        ``GET /v1/apps/instances/name/{name}/opaque-status``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceOpaqueStatusByName``
        """
        path = f"/v1/apps/instances/name/{name}/opaque-status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=OpaqueAppInstanceStatus)

    def get_edge_application_instance_status_by_name(self, name: str, request_id: str | None = None) -> AppInstStatusMsg:
        """Get edge application instance status

        ``GET /v1/apps/instances/name/{name}/status``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceStatusByName``
        """
        path = f"/v1/apps/instances/name/{name}/status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstStatusMsg)

    def get_edge_application_instance_events_by_name(
        self,
        objname: str,
        start_time: str | None = None,
        end_time: str | None = None,
        severity: str | None = None,
        resource: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> EventQueryResponse:
        """Get edge application instance events by name

        ``GET /v1/apps/instances/name/{objname}/events``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceEventsByName``
        """
        path = f"/v1/apps/instances/name/{objname}/events"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if severity is not None:
            params["severity"] = severity
        if resource is not None:
            params["resource"] = resource
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EventQueryResponse)

    def get_edge_application_instance_resource_metrics_by_name(
        self,
        objname: str,
        m_type: str,
        start_time: str | None = None,
        end_time: str | None = None,
        interval: str | None = None,
        request_id: str | None = None,
    ) -> MetricQueryResponse:
        """Get edge application instance resource usage timeline

        ``GET /v1/apps/instances/name/{objname}/timeSeries/{mType}``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceResourceMetricsByName``
        """
        path = f"/v1/apps/instances/name/{objname}/timeSeries/{m_type}"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if interval is not None:
            params["interval"] = interval
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=MetricQueryResponse)

    def update_patch_envelope_referenceto_app_instance(self, body: PatchReferenceUpdateConfig | dict[str, Any], request_id: str | None = None) -> ZsrvResponse:
        """Patch envelope reference update

        ``POST /v1/apps/instances/patch-reference-update``
        operationId: ``EdgeApplicationInstanceConfiguration_UpdatePatchEnvelopeReferencetoAppInstance``
        """
        path = "/v1/apps/instances/patch-reference-update"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("POST", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_app_instance_snapshot_by_id(self, id: str, request_id: str | None = None) -> AppInstanceSnapshot:
        """Query Application instance snapshot

        ``GET /v1/apps/instances/snapshot/id/{id}``
        operationId: ``EdgeApplicationInstanceStatus_GetAppInstanceSnapshotByID``
        """
        path = f"/v1/apps/instances/snapshot/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstanceSnapshot)

    def get_app_instance_snapshot_state(self, id: str, request_id: str | None = None) -> AppInstanceSnapshotState:
        """Query Application instance snapshot state

        ``GET /v1/apps/instances/snapshot/id/{id}/state``
        operationId: ``EdgeApplicationInstanceStatus_GetAppInstanceSnapshotState``
        """
        path = f"/v1/apps/instances/snapshot/id/{id}/state"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstanceSnapshotState)

    def query_edge_application_instance_status(
        self,
        summary: bool | None = None,
        app_name: str | None = None,
        run_state: str | None = None,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        type: int | None = None,
        tags: str | None = None,
        project_name_pattern: str | None = None,
        device_name_pattern: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        fields: list[str] | None = None,
        patch_envelope_name_pattern: str | None = None,
        patch_envelope_reference: str | None = None,
        title_pattern: str | None = None,
        edge_node_cluster_id: str | None = None,
        request_id: str | None = None,
    ) -> AppInstStatusListMsg:
        """Query status of edge application instances

        ``GET /v1/apps/instances/status``
        operationId: ``EdgeApplicationInstanceStatus_QueryEdgeApplicationInstanceStatus``
        """
        path = "/v1/apps/instances/status"
        params: dict[str, Any] = {}
        if summary is not None:
            params["summary"] = summary
        if app_name is not None:
            params["appName"] = app_name
        if run_state is not None:
            params["runState"] = run_state
        if device_name is not None:
            params["deviceName"] = device_name
        if project_name is not None:
            params["projectName"] = project_name
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if type is not None:
            params["type"] = type
        if tags is not None:
            params["tags"] = tags
        if project_name_pattern is not None:
            params["projectNamePattern"] = project_name_pattern
        if device_name_pattern is not None:
            params["deviceNamePattern"] = device_name_pattern
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if fields is not None:
            params["fields"] = fields
        if patch_envelope_name_pattern is not None:
            params["patchEnvelopeNamePattern"] = patch_envelope_name_pattern
        if patch_envelope_reference is not None:
            params["patchEnvelopeReference"] = patch_envelope_reference
        if title_pattern is not None:
            params["titlePattern"] = title_pattern
        if edge_node_cluster_id is not None:
            params["edgeNodeClusterID"] = edge_node_cluster_id
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstStatusListMsg)

    def query_edge_application_instance_status_config(
        self,
        summary: bool | None = None,
        app_name: str | None = None,
        run_state: str | None = None,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        type: int | None = None,
        tags: str | None = None,
        project_name_pattern: str | None = None,
        device_name_pattern: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        fields: list[str] | None = None,
        patch_envelope_name_pattern: str | None = None,
        patch_envelope_reference: str | None = None,
        title_pattern: str | None = None,
        edge_node_cluster_id: str | None = None,
        request_id: str | None = None,
    ) -> AppInstConfigStatusList:
        """Query status and config of edge application instances

        ``GET /v1/apps/instances/status-config``
        operationId: ``EdgeApplicationInstanceStatus_QueryEdgeApplicationInstanceStatusConfig``
        """
        path = "/v1/apps/instances/status-config"
        params: dict[str, Any] = {}
        if summary is not None:
            params["summary"] = summary
        if app_name is not None:
            params["appName"] = app_name
        if run_state is not None:
            params["runState"] = run_state
        if device_name is not None:
            params["deviceName"] = device_name
        if project_name is not None:
            params["projectName"] = project_name
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if type is not None:
            params["type"] = type
        if tags is not None:
            params["tags"] = tags
        if project_name_pattern is not None:
            params["projectNamePattern"] = project_name_pattern
        if device_name_pattern is not None:
            params["deviceNamePattern"] = device_name_pattern
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if fields is not None:
            params["fields"] = fields
        if patch_envelope_name_pattern is not None:
            params["patchEnvelopeNamePattern"] = patch_envelope_name_pattern
        if patch_envelope_reference is not None:
            params["patchEnvelopeReference"] = patch_envelope_reference
        if title_pattern is not None:
            params["titlePattern"] = title_pattern
        if edge_node_cluster_id is not None:
            params["edgeNodeClusterID"] = edge_node_cluster_id
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstConfigStatusList)

    def get_application_interface_tags(
        self,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> ObjectTagsList:
        """Query Application instance tags

        ``GET /v1/apps/instances/tags``
        operationId: ``EdgeApplicationInstanceStatus_GetApplicationInterfaceTags``
        """
        path = "/v1/apps/instances/tags"
        params: dict[str, Any] = {}
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=ObjectTagsList)

    def get_edge_application_bundle_by_name(self, name: str, request_id: str | None = None) -> App:
        """Get edge application bundle

        ``GET /v1/apps/name/{name}``
        operationId: ``EdgeApplicationConfiguration_GetEdgeApplicationBundleByName``
        """
        path = f"/v1/apps/name/{name}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=App)

    def get_patch_envelope(
        self,
        project_name_pattern: str | None = None,
        name_pattern: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        summary: bool | None = None,
        request_id: str | None = None,
    ) -> PatchEnvelopeList:
        """Get all the patch envelopes

        ``GET /v1/patch-envelope``
        operationId: ``PatchEnvelopeConfiguration_GetPatchEnvelope``
        """
        path = "/v1/patch-envelope"
        params: dict[str, Any] = {}
        if project_name_pattern is not None:
            params["projectNamePattern"] = project_name_pattern
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if summary is not None:
            params["summary"] = summary
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=PatchEnvelopeList)

    def create_patch_envelope(self, body: PatchEnvelope | dict[str, Any], request_id: str | None = None) -> ZsrvResponse:
        """Create patch envelope

        ``POST /v1/patch-envelope``
        operationId: ``PatchEnvelopeConfiguration_CreatePatchEnvelope``
        """
        path = "/v1/patch-envelope"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("POST", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_patch_envelope_by_id(self, id: str, request_id: str | None = None) -> PatchEnvelope:
        """Get patch envelope by id

        ``GET /v1/patch-envelope/id/{id}``
        operationId: ``PatchEnvelopeConfiguration_GetPatchEnvelopeById``
        """
        path = f"/v1/patch-envelope/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=PatchEnvelope)

    def patch_envelope_configuration__delete_app_instance_snapshot(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Delete patch envelope

        ``DELETE /v1/patch-envelope/id/{id}``
        operationId: ``PatchEnvelopeConfiguration_DeleteAppInstanceSnapshot``
        """
        path = f"/v1/patch-envelope/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("DELETE", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def update_patch_envelope(self, id: str, body: dict[str, Any] | Any, request_id: str | None = None) -> ZsrvResponse:
        """Update patch envelope

        ``PUT /v1/patch-envelope/id/{id}``
        operationId: ``PatchEnvelopeConfiguration_UpdatePatchEnvelope``
        """
        path = f"/v1/patch-envelope/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_patch_envelope_by_name(self, name: str, request_id: str | None = None) -> PatchEnvelope:
        """Get patch envelope by name

        ``GET /v1/patch-envelope/name/{name}``
        operationId: ``PatchEnvelopeConfiguration_GetPatchEnvelopeByName``
        """
        path = f"/v1/patch-envelope/name/{name}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=PatchEnvelope)

    def get_patch_envelope_status(
        self,
        summary: bool | None = None,
        filter_device_name: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        fields: list[str] | None = None,
        request_id: str | None = None,
    ) -> PatchStatusListMsg:
        """Get patch envelope status

        ``GET /v1/patch-envelope/status``
        operationId: ``PatchEnvelopeConfiguration_GetPatchEnvelopeStatus``
        """
        path = "/v1/patch-envelope/status"
        params: dict[str, Any] = {}
        if summary is not None:
            params["summary"] = summary
        if filter_device_name is not None:
            params["filter.deviceName"] = filter_device_name
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if fields is not None:
            params["fields"] = fields
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=PatchStatusListMsg)

    def query_edge_application_instances_v2(
        self,
        project: str | None = None,
        bundle: str | None = None,
        device: str | None = None,
        name_pattern: str | None = None,
        app_type: int | None = None,
        deployment_type: str | None = None,
        project_name_pattern: str | None = None,
        device_name_pattern: str | None = None,
        summary: bool | None = None,
        title_pattern: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        fields: list[str] | None = None,
        request_id: str | None = None,
    ) -> AppInstances:
        """Query edge application instances

        ``GET /v2/apps/instances``
        operationId: ``EdgeApplicationInstanceConfiguration_QueryEdgeApplicationInstancesV2``
        """
        path = "/v2/apps/instances"
        params: dict[str, Any] = {}
        if project is not None:
            params["project"] = project
        if bundle is not None:
            params["bundle"] = bundle
        if device is not None:
            params["device"] = device
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if app_type is not None:
            params["appType"] = app_type
        if deployment_type is not None:
            params["deploymentType"] = deployment_type
        if project_name_pattern is not None:
            params["projectNamePattern"] = project_name_pattern
        if device_name_pattern is not None:
            params["deviceNamePattern"] = device_name_pattern
        if summary is not None:
            params["summary"] = summary
        if title_pattern is not None:
            params["titlePattern"] = title_pattern
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if fields is not None:
            params["fields"] = fields
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstances)

    def create_edge_application_instance_v2(self, body: AppInstance | dict[str, Any], request_id: str | None = None) -> ZsrvResponse:
        """Create edge application instance

        ``POST /v2/apps/instances``
        operationId: ``EdgeApplicationInstanceConfiguration_CreateEdgeApplicationInstanceV2``
        """
        path = "/v2/apps/instances"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("POST", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_edge_application_instance_v2(self, id: str, request_id: str | None = None) -> AppInstance:
        """Get edge application instance

        ``GET /v2/apps/instances/id/{id}``
        operationId: ``EdgeApplicationInstanceConfiguration_GetEdgeApplicationInstanceV2``
        """
        path = f"/v2/apps/instances/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstance)

    def delete_edge_application_instance_v2(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Delete edge application instance

        ``DELETE /v2/apps/instances/id/{id}``
        operationId: ``EdgeApplicationInstanceConfiguration_DeleteEdgeApplicationInstanceV2``
        """
        path = f"/v2/apps/instances/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("DELETE", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def update_edge_application_instance_v2(self, id: str, body: dict[str, Any] | Any, request_id: str | None = None) -> ZsrvResponse:
        """Update edge application instance

        ``PUT /v2/apps/instances/id/{id}``
        operationId: ``EdgeApplicationInstanceConfiguration_UpdateEdgeApplicationInstanceV2``
        """
        path = f"/v2/apps/instances/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def activate_edge_application_instance_v2(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Activate edge application instance

        ``PUT /v2/apps/instances/id/{id}/activate``
        operationId: ``EdgeApplicationInstanceConfiguration_ActivateEdgeApplicationInstanceV2``
        """
        path = f"/v2/apps/instances/id/{id}/activate"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def connect_to_edge_application_instance_v2(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Connect to edge application instance console

        ``PUT /v2/apps/instances/id/{id}/console/remote``
        operationId: ``EdgeApplicationInstanceConfiguration_ConnectToEdgeApplicationInstanceV2``
        """
        path = f"/v2/apps/instances/id/{id}/console/remote"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def de_activate_edge_application_instance_v2(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Deactivate edge application instance

        ``PUT /v2/apps/instances/id/{id}/deactivate``
        operationId: ``EdgeApplicationInstanceConfiguration_DeActivateEdgeApplicationInstanceV2``
        """
        path = f"/v2/apps/instances/id/{id}/deactivate"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def get_edge_application_instance_traffic_flows_v2(
        self,
        id: str,
        name: str | None = None,
        start_time: str | None = None,
        end_time: str | None = None,
        levels: list[str] | None = None,
        enterprise_id: str | None = None,
        metric: int | None = None,
        direction: int | None = None,
        aclid: int | None = None,
        action: str | None = None,
        proto: int | None = None,
        remoteip: str | None = None,
        remoteport: int | None = None,
        fqdn: str | None = None,
        request_id: str | None = None,
    ) -> ClassificationResponse:
        """Get edge application instance network traffic flow log

        ``GET /v2/apps/instances/id/{id}/flowlog/classification``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceTrafficFlowsV2``
        """
        path = f"/v2/apps/instances/id/{id}/flowlog/classification"
        params: dict[str, Any] = {}
        if name is not None:
            params["name"] = name
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if levels is not None:
            params["levels"] = levels
        if enterprise_id is not None:
            params["enterpriseId"] = enterprise_id
        if metric is not None:
            params["metric"] = metric
        if direction is not None:
            params["direction"] = direction
        if aclid is not None:
            params["aclid"] = aclid
        if action is not None:
            params["action"] = action
        if proto is not None:
            params["proto"] = proto
        if remoteip is not None:
            params["remoteip"] = remoteip
        if remoteport is not None:
            params["remoteport"] = remoteport
        if fqdn is not None:
            params["fqdn"] = fqdn
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=ClassificationResponse)

    def get_edge_application_instance_top_talkers_v2(
        self,
        id: str,
        name: str | None = None,
        start_time: str | None = None,
        end_time: str | None = None,
        metric_type: str | None = None,
        enterprise_id: str | None = None,
        cursor_page_token: str | None = None,
        cursor_order_by: list[str] | None = None,
        cursor_page_num: float | None = None,
        cursor_page_size: float | None = None,
        cursor_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> TopTalkersResponse:
        """Get edge application instance top talkers of the network traffic flows

        ``GET /v2/apps/instances/id/{id}/flowlog/toptalkers``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceTopTalkersV2``
        """
        path = f"/v2/apps/instances/id/{id}/flowlog/toptalkers"
        params: dict[str, Any] = {}
        if name is not None:
            params["name"] = name
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if metric_type is not None:
            params["metricType"] = metric_type
        if enterprise_id is not None:
            params["enterpriseId"] = enterprise_id
        if cursor_page_token is not None:
            params["Cursor.pageToken"] = cursor_page_token
        if cursor_order_by is not None:
            params["Cursor.orderBy"] = cursor_order_by
        if cursor_page_num is not None:
            params["Cursor.pageNum"] = cursor_page_num
        if cursor_page_size is not None:
            params["Cursor.pageSize"] = cursor_page_size
        if cursor_total_pages is not None:
            params["Cursor.totalPages"] = cursor_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=TopTalkersResponse)

    def get_edge_application_instance_logs_v2(
        self,
        id: str,
        start_time: str | None = None,
        end_time: str | None = None,
        interval: str | None = None,
        cursor_page_token: str | None = None,
        cursor_order_by: list[str] | None = None,
        cursor_page_num: float | None = None,
        cursor_page_size: float | None = None,
        cursor_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> AppInstanceLogsResponse:
        """Get edge application instance log

        ``GET /v2/apps/instances/id/{id}/logs``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceLogsV2``
        """
        path = f"/v2/apps/instances/id/{id}/logs"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if interval is not None:
            params["interval"] = interval
        if cursor_page_token is not None:
            params["Cursor.pageToken"] = cursor_page_token
        if cursor_order_by is not None:
            params["Cursor.orderBy"] = cursor_order_by
        if cursor_page_num is not None:
            params["Cursor.pageNum"] = cursor_page_num
        if cursor_page_size is not None:
            params["Cursor.pageSize"] = cursor_page_size
        if cursor_total_pages is not None:
            params["Cursor.totalPages"] = cursor_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstanceLogsResponse)

    def get_edge_application_instance_opaque_status_by_id_v2(self, id: str, request_id: str | None = None) -> OpaqueAppInstanceStatus:
        """Get patch envelope opaque status as base64 encoded string

        ``GET /v2/apps/instances/id/{id}/opaque-status``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceOpaqueStatusByIdV2``
        """
        path = f"/v2/apps/instances/id/{id}/opaque-status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=OpaqueAppInstanceStatus)

    def refresh_edge_application_instance_v2(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Refresh edge application instance

        ``PUT /v2/apps/instances/id/{id}/refresh``
        operationId: ``EdgeApplicationInstanceConfiguration_RefreshEdgeApplicationInstanceV2``
        """
        path = f"/v2/apps/instances/id/{id}/refresh"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def refresh_purge_edge_application_instance_v2(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Refresh and purge edge application instance

        ``PUT /v2/apps/instances/id/{id}/refresh/purge``
        operationId: ``EdgeApplicationInstanceConfiguration_RefreshPurgeEdgeApplicationInstanceV2``
        """
        path = f"/v2/apps/instances/id/{id}/refresh/purge"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def restart_edge_application_instance_v2(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Restart edge application instance

        ``PUT /v2/apps/instances/id/{id}/restart``
        operationId: ``EdgeApplicationInstanceConfiguration_RestartEdgeApplicationInstanceV2``
        """
        path = f"/v2/apps/instances/id/{id}/restart"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def get_edge_application_instance_status_v2(self, id: str, request_id: str | None = None) -> AppInstStatusMsg:
        """Get edge application instance status

        ``GET /v2/apps/instances/id/{id}/status``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceStatusV2``
        """
        path = f"/v2/apps/instances/id/{id}/status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstStatusMsg)

    def get_edge_application_instance_events_v2(
        self,
        objid: str,
        start_time: str | None = None,
        end_time: str | None = None,
        severity: str | None = None,
        resource: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> EventQueryResponse:
        """Get edge application instance events by id

        ``GET /v2/apps/instances/id/{objid}/events``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceEventsV2``
        """
        path = f"/v2/apps/instances/id/{objid}/events"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if severity is not None:
            params["severity"] = severity
        if resource is not None:
            params["resource"] = resource
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EventQueryResponse)

    def get_edge_application_instance_resource_metrics_by_id_v2(
        self,
        objid: str,
        m_type: str,
        start_time: str | None = None,
        end_time: str | None = None,
        interval: str | None = None,
        request_id: str | None = None,
    ) -> MetricQueryResponse:
        """Get edge application instance resource usage timeline

        ``GET /v2/apps/instances/id/{objid}/timeSeries/{mType}``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceResourceMetricsByIdV2``
        """
        path = f"/v2/apps/instances/id/{objid}/timeSeries/{m_type}"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if interval is not None:
            params["interval"] = interval
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=MetricQueryResponse)

    def get_edge_application_instance_by_name_v2(self, name: str, request_id: str | None = None) -> AppInstance:
        """Get edge application instance

        ``GET /v2/apps/instances/name/{name}``
        operationId: ``EdgeApplicationInstanceConfiguration_GetEdgeApplicationInstanceByNameV2``
        """
        path = f"/v2/apps/instances/name/{name}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstance)

    def get_edge_application_instance_traffic_flows_v22(
        self,
        name: str,
        id: str | None = None,
        start_time: str | None = None,
        end_time: str | None = None,
        levels: list[str] | None = None,
        enterprise_id: str | None = None,
        metric: int | None = None,
        direction: int | None = None,
        aclid: int | None = None,
        action: str | None = None,
        proto: int | None = None,
        remoteip: str | None = None,
        remoteport: int | None = None,
        fqdn: str | None = None,
        request_id: str | None = None,
    ) -> ClassificationResponse:
        """Get edge application instance network traffic flow log

        ``GET /v2/apps/instances/name/{name}/flowlog/classification``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceTrafficFlowsV22``
        """
        path = f"/v2/apps/instances/name/{name}/flowlog/classification"
        params: dict[str, Any] = {}
        if id is not None:
            params["id"] = id
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if levels is not None:
            params["levels"] = levels
        if enterprise_id is not None:
            params["enterpriseId"] = enterprise_id
        if metric is not None:
            params["metric"] = metric
        if direction is not None:
            params["direction"] = direction
        if aclid is not None:
            params["aclid"] = aclid
        if action is not None:
            params["action"] = action
        if proto is not None:
            params["proto"] = proto
        if remoteip is not None:
            params["remoteip"] = remoteip
        if remoteport is not None:
            params["remoteport"] = remoteport
        if fqdn is not None:
            params["fqdn"] = fqdn
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=ClassificationResponse)

    def get_edge_application_instance_top_talkers_v22(
        self,
        name: str,
        id: str | None = None,
        start_time: str | None = None,
        end_time: str | None = None,
        metric_type: str | None = None,
        enterprise_id: str | None = None,
        cursor_page_token: str | None = None,
        cursor_order_by: list[str] | None = None,
        cursor_page_num: float | None = None,
        cursor_page_size: float | None = None,
        cursor_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> TopTalkersResponse:
        """Get edge application instance top talkers of the network traffic flows

        ``GET /v2/apps/instances/name/{name}/flowlog/toptalkers``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceTopTalkersV22``
        """
        path = f"/v2/apps/instances/name/{name}/flowlog/toptalkers"
        params: dict[str, Any] = {}
        if id is not None:
            params["id"] = id
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if metric_type is not None:
            params["metricType"] = metric_type
        if enterprise_id is not None:
            params["enterpriseId"] = enterprise_id
        if cursor_page_token is not None:
            params["Cursor.pageToken"] = cursor_page_token
        if cursor_order_by is not None:
            params["Cursor.orderBy"] = cursor_order_by
        if cursor_page_num is not None:
            params["Cursor.pageNum"] = cursor_page_num
        if cursor_page_size is not None:
            params["Cursor.pageSize"] = cursor_page_size
        if cursor_total_pages is not None:
            params["Cursor.totalPages"] = cursor_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=TopTalkersResponse)

    def get_edge_application_instance_opaque_status_by_name_v2(self, name: str, request_id: str | None = None) -> OpaqueAppInstanceStatus:
        """Get patch envelope opaque status as base64 encoded string

        ``GET /v2/apps/instances/name/{name}/opaque-status``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceOpaqueStatusByNameV2``
        """
        path = f"/v2/apps/instances/name/{name}/opaque-status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=OpaqueAppInstanceStatus)

    def get_edge_application_instance_status_by_name_v2(self, name: str, request_id: str | None = None) -> AppInstStatusMsg:
        """Get edge application instance status

        ``GET /v2/apps/instances/name/{name}/status``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceStatusByNameV2``
        """
        path = f"/v2/apps/instances/name/{name}/status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstStatusMsg)

    def get_edge_application_instance_events_by_name_v2(
        self,
        objname: str,
        start_time: str | None = None,
        end_time: str | None = None,
        severity: str | None = None,
        resource: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> EventQueryResponse:
        """Get edge application instance events by name

        ``GET /v2/apps/instances/name/{objname}/events``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceEventsByNameV2``
        """
        path = f"/v2/apps/instances/name/{objname}/events"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if severity is not None:
            params["severity"] = severity
        if resource is not None:
            params["resource"] = resource
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EventQueryResponse)

    def get_edge_application_instance_resource_metrics_by_name_v2(
        self,
        objname: str,
        m_type: str,
        start_time: str | None = None,
        end_time: str | None = None,
        interval: str | None = None,
        request_id: str | None = None,
    ) -> MetricQueryResponse:
        """Get edge application instance resource usage timeline

        ``GET /v2/apps/instances/name/{objname}/timeSeries/{mType}``
        operationId: ``EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceResourceMetricsByNameV2``
        """
        path = f"/v2/apps/instances/name/{objname}/timeSeries/{m_type}"
        params: dict[str, Any] = {}
        if start_time is not None:
            params["startTime"] = start_time
        if end_time is not None:
            params["endTime"] = end_time
        if interval is not None:
            params["interval"] = interval
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=MetricQueryResponse)

    def update_patch_envelope_referenceto_app_instance_v2(self, body: PatchReferenceUpdateConfig | dict[str, Any], request_id: str | None = None) -> ZsrvResponse:
        """Patch envelope reference update

        ``POST /v2/apps/instances/patch-reference-update``
        operationId: ``EdgeApplicationInstanceConfiguration_UpdatePatchEnvelopeReferencetoAppInstanceV2``
        """
        path = "/v2/apps/instances/patch-reference-update"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("POST", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def query_edge_application_instance_status_v2(
        self,
        summary: bool | None = None,
        app_name: str | None = None,
        run_state: str | None = None,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        type: int | None = None,
        tags: str | None = None,
        project_name_pattern: str | None = None,
        device_name_pattern: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        fields: list[str] | None = None,
        patch_envelope_name_pattern: str | None = None,
        patch_envelope_reference: str | None = None,
        title_pattern: str | None = None,
        edge_node_cluster_id: str | None = None,
        request_id: str | None = None,
    ) -> AppInstStatusListMsg:
        """Query status of edge application instances

        ``GET /v2/apps/instances/status``
        operationId: ``EdgeApplicationInstanceStatus_QueryEdgeApplicationInstanceStatusV2``
        """
        path = "/v2/apps/instances/status"
        params: dict[str, Any] = {}
        if summary is not None:
            params["summary"] = summary
        if app_name is not None:
            params["appName"] = app_name
        if run_state is not None:
            params["runState"] = run_state
        if device_name is not None:
            params["deviceName"] = device_name
        if project_name is not None:
            params["projectName"] = project_name
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if type is not None:
            params["type"] = type
        if tags is not None:
            params["tags"] = tags
        if project_name_pattern is not None:
            params["projectNamePattern"] = project_name_pattern
        if device_name_pattern is not None:
            params["deviceNamePattern"] = device_name_pattern
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if fields is not None:
            params["fields"] = fields
        if patch_envelope_name_pattern is not None:
            params["patchEnvelopeNamePattern"] = patch_envelope_name_pattern
        if patch_envelope_reference is not None:
            params["patchEnvelopeReference"] = patch_envelope_reference
        if title_pattern is not None:
            params["titlePattern"] = title_pattern
        if edge_node_cluster_id is not None:
            params["edgeNodeClusterID"] = edge_node_cluster_id
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstStatusListMsg)

    def query_edge_application_instance_status_config_v2(
        self,
        summary: bool | None = None,
        app_name: str | None = None,
        run_state: str | None = None,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        type: int | None = None,
        tags: str | None = None,
        project_name_pattern: str | None = None,
        device_name_pattern: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        fields: list[str] | None = None,
        patch_envelope_name_pattern: str | None = None,
        patch_envelope_reference: str | None = None,
        title_pattern: str | None = None,
        edge_node_cluster_id: str | None = None,
        request_id: str | None = None,
    ) -> AppInstConfigStatusList:
        """Query status and config of edge application instances

        ``GET /v2/apps/instances/status-config``
        operationId: ``EdgeApplicationInstanceStatus_QueryEdgeApplicationInstanceStatusConfigV2``
        """
        path = "/v2/apps/instances/status-config"
        params: dict[str, Any] = {}
        if summary is not None:
            params["summary"] = summary
        if app_name is not None:
            params["appName"] = app_name
        if run_state is not None:
            params["runState"] = run_state
        if device_name is not None:
            params["deviceName"] = device_name
        if project_name is not None:
            params["projectName"] = project_name
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if type is not None:
            params["type"] = type
        if tags is not None:
            params["tags"] = tags
        if project_name_pattern is not None:
            params["projectNamePattern"] = project_name_pattern
        if device_name_pattern is not None:
            params["deviceNamePattern"] = device_name_pattern
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if fields is not None:
            params["fields"] = fields
        if patch_envelope_name_pattern is not None:
            params["patchEnvelopeNamePattern"] = patch_envelope_name_pattern
        if patch_envelope_reference is not None:
            params["patchEnvelopeReference"] = patch_envelope_reference
        if title_pattern is not None:
            params["titlePattern"] = title_pattern
        if edge_node_cluster_id is not None:
            params["edgeNodeClusterID"] = edge_node_cluster_id
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=AppInstConfigStatusList)
