# Generated by scripts/generate.py from openapi/*.swagger.json. Do not edit.
"""ZEDEDA Job Service — generated sync and async clients."""

from __future__ import annotations

import typing as _t
from collections.abc import AsyncIterator, Iterator, Mapping, Sequence

from zedcloud._service import AsyncBaseService, BaseService, FileContent
from zedcloud._generated.models import (
    BulkConfig,
    JobConfig,
    JobConfigList,
    UpdateJobBody,
    ZsrvResponse,
)


class JobsService(BaseService):
    """ZEDEDA Job Service (sync)."""

    _security = "bearer"

    def query_jobs(
        self,
        *,
        summary: bool | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        job_status: int | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        request_id: str | None = None,
    ) -> JobConfigList:
        """Query asynchronous job requests

        Query the asynchronous job request records.

        Args:
            summary: Only summary count is required
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size
            job_status: status of the job
            project_name: project name
            name_pattern: name pattern of the job

        ``GET /v1/jobs`` · operationId ``BulkJobOps_QueryJobs`` · read-only
        """
        return self._request(
            "GET",
            "/v1/jobs",
            query={
                "summary": summary,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "jobStatus": job_status,
                "projectName": project_name,
                "namePattern": name_pattern,
            },
            response_model=JobConfigList,
            request_id=request_id,
            operation_id="BulkJobOps_QueryJobs",
        )

    def iter_jobs(
        self,
        *,
        summary: bool | None = None,
        order_by: Sequence[str] | None = None,
        job_status: int | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> Iterator[JobConfig]:
        """Iterate over every result of :meth:`query_jobs`, fetching pages lazily.

        Args:
            summary: Only summary count is required
            job_status: status of the job
            project_name: project name
            name_pattern: name pattern of the job
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/jobs`` · operationId ``BulkJobOps_QueryJobs`` · read-only
        """
        return self._paginate(
            self.query_jobs,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            summary=summary,
            order_by=order_by,
            job_status=job_status,
            project_name=project_name,
            name_pattern=name_pattern,
        )

    def create_job(
        self,
        body: JobConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create asynchronous job request

        Create an asynchronous job request record.

        ``POST /v1/jobs`` · operationId ``BulkJobOps_CreateJob`` · modifies state
        """
        return self._request(
            "POST",
            "/v1/jobs",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_CreateJob",
        )

    def bulk_import_edge_applications(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to import edge application bundles

        Update job request to import edge application bundle(s) from global App Store matching
        selection criteria.

        ``PUT /v1/jobs/apps/bundles/import`` · operationId ``BulkJobOps_BulkImportEdgeApplications`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/jobs/apps/bundles/import",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkImportEdgeApplications",
        )

    def bulk_create_edge_application_instances(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to create edge application instances

        Update job request to create edge application instance(s) on edge node(s) matching
        selection criteria.

        ``PUT /v1/jobs/apps/instances/create`` · operationId ``BulkJobOps_BulkCreateEdgeApplicationInstances`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/jobs/apps/instances/create",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkCreateEdgeApplicationInstances",
        )

    def bulk_refresh_edge_application_instances(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to refresh edge application instances

        Update job request to refresh edge application instances matching selection criteria.
        Update edge application instance(s) to the latest version of the edge application. This
        operation will result in a restart of the edge application instance(s).

        ``PUT /v1/jobs/apps/instances/refresh`` · operationId ``BulkJobOps_BulkRefreshEdgeApplicationInstances`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/jobs/apps/instances/refresh",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkRefreshEdgeApplicationInstances",
        )

    def bulk_refresh_and_purge_edge_application_instances(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to refresh and purge edge application instances

        Update job request to refresh and purge edge application instances matching selection
        criteria. Update edge application instance(s) to the latest version of the edge
        application. This operation will result in loss of data and a restart of the edge
        application instance(s).

        ``PUT /v1/jobs/apps/instances/refresh/purge`` · operationId ``BulkJobOps_BulkRefreshAndPurgeEdgeApplicationInstances`` · DESTRUCTIVE
        """
        return self._request(
            "PUT",
            "/v1/jobs/apps/instances/refresh/purge",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkRefreshAndPurgeEdgeApplicationInstances",
        )

    def bulk_update_edge_node_base_os(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to update EVE image on edge nodes

        Update job request to update EVE image on edge nodes. If edge node is already running
        the latest EVE image no action is taken.

        ``PUT /v1/jobs/devices/baseos/upgrade`` · operationId ``BulkJobOps_BulkUpdateEdgeNodeBaseOS`` · DESTRUCTIVE
        """
        return self._request(
            "PUT",
            "/v1/jobs/devices/baseos/upgrade",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkUpdateEdgeNodeBaseOS",
        )

    def bulk_update_edge_node_base_os_retry(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to retry update EVE image on edge nodes

        Update job request to retry update EVE image on edge nodes. If edge node is already
        running the latest EVE image no action is taken.

        ``PUT /v1/jobs/devices/baseos/upgrade/retry`` · operationId ``BulkJobOps_BulkUpdateEdgeNodeBaseOSRetry`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/jobs/devices/baseos/upgrade/retry",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkUpdateEdgeNodeBaseOSRetry",
        )

    def bulk_update_edge_node_base_os_deployment_tag(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to update Deployment tag on edge nodes in bulk.

        ``PUT /v1/jobs/devices/deployment/tags`` · operationId ``BulkJobOps_BulkUpdateEdgeNodeBaseOSDeploymentTag`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/jobs/devices/deployment/tags",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkUpdateEdgeNodeBaseOSDeploymentTag",
        )

    def bulk_update_edge_node_base_os_project(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to update EVE image project and target on edge nodes

        Update job request to update EVE image project and target on edge nodes. If edge node is
        already running the latest EVE image no action is taken.

        ``PUT /v1/jobs/devices/project/target`` · operationId ``BulkJobOps_BulkUpdateEdgeNodeBaseOSProject`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/jobs/devices/project/target",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkUpdateEdgeNodeBaseOSProject",
        )

    def bulk_update_edge_node_base_os_tag(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to update EVE image tag on edge nodes

        Update job request to update EVE image tag on edge nodes. If edge node is already
        running the latest EVE image no action is taken.

        ``PUT /v1/jobs/devices/tags`` · operationId ``BulkJobOps_BulkUpdateEdgeNodeBaseOSTag`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/jobs/devices/tags",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkUpdateEdgeNodeBaseOSTag",
        )

    def get_job_by_id(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> JobConfig:
        """Get asynchronous job request

        Get the configuration and status of an asynchronous job request record.

        Args:
            id: System defined universally unique Id of the job request

        ``GET /v1/jobs/id/{id}`` · operationId ``BulkJobOps_GetJobById`` · read-only
        """
        return self._request(
            "GET",
            "/v1/jobs/id/{id}",
            path={"id": id},
            response_model=JobConfig,
            request_id=request_id,
            operation_id="BulkJobOps_GetJobById",
        )

    def update_job(
        self,
        id: str,
        body: UpdateJobBody | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update asynchronous job request

        Update an asynchronous job request record. The usual pattern to update an asynchronous
        job request record is to retrieve the record and update with the modified values in a
        new body to update the asynchronous job request record.

        Args:
            id: System defined universally unique Id of the job request

        ``PUT /v1/jobs/id/{id}`` · operationId ``BulkJobOps_UpdateJob`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/jobs/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_UpdateJob",
        )

    def get_job(
        self,
        id: str,
        object_type: str,
        *,
        request_id: str | None = None,
    ) -> JobConfig:
        """Get asynchronous job request

        Get the configuration and status of an asynchronous job request record.

        Args:
            id: System defined universally unique Id of the job request
            object_type: object type for which job has been created One of: OBJECT_TYPE_UNSPECIFIED,
                OBJECT_TYPE_USER, OBJECT_TYPE_EDGE_NODE, OBJECT_TYPE_EDGE_APP,
                OBJECT_TYPE_IMAGE, OBJECT_TYPE_EDGE_APP_INSTANCE, OBJECT_TYPE_PROJECT,
                OBJECT_TYPE_NETWORK, OBJECT_TYPE_DATASTORE, OBJECT_TYPE_SERVICE,
                OBJECT_TYPE_SERVICE_INSTANCE, OBJECT_TYPE_ENTERPRISE, OBJECT_TYPE_ROLE,
                OBJECT_TYPE_CREDENTIAL, OBJECT_TYPE_NETWORK_INSTANCE,
                OBJECT_TYPE_VOLUME_INSTANCE, OBJECT_TYPE_REALM, OBJECT_TYPE_AUTHPROFILE,
                OBJECT_TYPE_POLICY, OBJECT_TYPE_APP_POLICY, OBJECT_TYPE_CLUSTER_INSTANCE,
                OBJECT_TYPE_PLUGIN, OBJECT_TYPE_DOC_POLICY, OBJECT_TYPE_ORCHESTRATOR_CLUSTER,
                OBJECT_TYPE_TAGS, OBJECT_TYPE_EDGE_NODE_INTERFACE, OBJECT_TYPE_DEPLOYMENT,
                OBJECT_TYPE_ENTITLEMENTS, OBJECT_TYPE_DATA_STREAM, OBJECT_TYPE_API_USAGE,
                OBJECT_TYPE_APP_INSTANCE_SNAPSHOT, OBJECT_TYPE_PATCH_ENVELOPE,
                OBJECT_TYPE_RESOURCE_USAGE_TRACK, OBJECT_TYPE_PATCH_ENVELOPE_REFERENCE,
                OBJECT_TYPE_DEV_PASSTHROUGH, OBJECT_TYPE_EDGE_NODE_CLUSTER,
                OBJECT_TYPE_ASSET_GROUP, OBJECT_TYPE_APP_PROFILE,
                OBJECT_TYPE_PROFILE_DEPLOYMENT, OBJECT_TYPE_ZKS_INSTANCE,
                OBJECT_TYPE_CLUSTER_GROUP.

        ``GET /v1/jobs/id/{id}/objectType/{objectType}`` · operationId ``BulkJobOps_GetJob`` · read-only
        """
        return self._request(
            "GET",
            "/v1/jobs/id/{id}/objectType/{objectType}",
            path={"id": id, "objectType": object_type},
            response_model=JobConfig,
            request_id=request_id,
            operation_id="BulkJobOps_GetJob",
        )

    def delete_job(
        self,
        id: str,
        object_type: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete asynchronous job request

        Delete an asynchronous job request record.

        Args:
            id: System defined universally unique Id of the job request
            object_type: object type for which job has been created One of: OBJECT_TYPE_UNSPECIFIED,
                OBJECT_TYPE_USER, OBJECT_TYPE_EDGE_NODE, OBJECT_TYPE_EDGE_APP,
                OBJECT_TYPE_IMAGE, OBJECT_TYPE_EDGE_APP_INSTANCE, OBJECT_TYPE_PROJECT,
                OBJECT_TYPE_NETWORK, OBJECT_TYPE_DATASTORE, OBJECT_TYPE_SERVICE,
                OBJECT_TYPE_SERVICE_INSTANCE, OBJECT_TYPE_ENTERPRISE, OBJECT_TYPE_ROLE,
                OBJECT_TYPE_CREDENTIAL, OBJECT_TYPE_NETWORK_INSTANCE,
                OBJECT_TYPE_VOLUME_INSTANCE, OBJECT_TYPE_REALM, OBJECT_TYPE_AUTHPROFILE,
                OBJECT_TYPE_POLICY, OBJECT_TYPE_APP_POLICY, OBJECT_TYPE_CLUSTER_INSTANCE,
                OBJECT_TYPE_PLUGIN, OBJECT_TYPE_DOC_POLICY, OBJECT_TYPE_ORCHESTRATOR_CLUSTER,
                OBJECT_TYPE_TAGS, OBJECT_TYPE_EDGE_NODE_INTERFACE, OBJECT_TYPE_DEPLOYMENT,
                OBJECT_TYPE_ENTITLEMENTS, OBJECT_TYPE_DATA_STREAM, OBJECT_TYPE_API_USAGE,
                OBJECT_TYPE_APP_INSTANCE_SNAPSHOT, OBJECT_TYPE_PATCH_ENVELOPE,
                OBJECT_TYPE_RESOURCE_USAGE_TRACK, OBJECT_TYPE_PATCH_ENVELOPE_REFERENCE,
                OBJECT_TYPE_DEV_PASSTHROUGH, OBJECT_TYPE_EDGE_NODE_CLUSTER,
                OBJECT_TYPE_ASSET_GROUP, OBJECT_TYPE_APP_PROFILE,
                OBJECT_TYPE_PROFILE_DEPLOYMENT, OBJECT_TYPE_ZKS_INSTANCE,
                OBJECT_TYPE_CLUSTER_GROUP.

        ``DELETE /v1/jobs/id/{id}/objectType/{objectType}`` · operationId ``BulkJobOps_DeleteJob`` · DESTRUCTIVE
        """
        return self._request(
            "DELETE",
            "/v1/jobs/id/{id}/objectType/{objectType}",
            path={"id": id, "objectType": object_type},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_DeleteJob",
        )

    def bulk_import_hardware_models(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to import hardware models

        Update job request to import hardware model(s) from global Model Store matching
        selection criteria.

        ``PUT /v1/jobs/models/import`` · operationId ``BulkJobOps_BulkImportHardwareModels`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/jobs/models/import",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkImportHardwareModels",
        )

    def get_job_by_name(
        self,
        name: str,
        object_type: str,
        *,
        request_id: str | None = None,
    ) -> JobConfig:
        """Get asynchronous job request

        Get the configuration and status of an asynchronous job request record.

        Args:
            name: User defined name of the job request, unique across the enterprise. Once object
                is created, name can’t be changed
            object_type: object type for which job has been created One of: OBJECT_TYPE_UNSPECIFIED,
                OBJECT_TYPE_USER, OBJECT_TYPE_EDGE_NODE, OBJECT_TYPE_EDGE_APP,
                OBJECT_TYPE_IMAGE, OBJECT_TYPE_EDGE_APP_INSTANCE, OBJECT_TYPE_PROJECT,
                OBJECT_TYPE_NETWORK, OBJECT_TYPE_DATASTORE, OBJECT_TYPE_SERVICE,
                OBJECT_TYPE_SERVICE_INSTANCE, OBJECT_TYPE_ENTERPRISE, OBJECT_TYPE_ROLE,
                OBJECT_TYPE_CREDENTIAL, OBJECT_TYPE_NETWORK_INSTANCE,
                OBJECT_TYPE_VOLUME_INSTANCE, OBJECT_TYPE_REALM, OBJECT_TYPE_AUTHPROFILE,
                OBJECT_TYPE_POLICY, OBJECT_TYPE_APP_POLICY, OBJECT_TYPE_CLUSTER_INSTANCE,
                OBJECT_TYPE_PLUGIN, OBJECT_TYPE_DOC_POLICY, OBJECT_TYPE_ORCHESTRATOR_CLUSTER,
                OBJECT_TYPE_TAGS, OBJECT_TYPE_EDGE_NODE_INTERFACE, OBJECT_TYPE_DEPLOYMENT,
                OBJECT_TYPE_ENTITLEMENTS, OBJECT_TYPE_DATA_STREAM, OBJECT_TYPE_API_USAGE,
                OBJECT_TYPE_APP_INSTANCE_SNAPSHOT, OBJECT_TYPE_PATCH_ENVELOPE,
                OBJECT_TYPE_RESOURCE_USAGE_TRACK, OBJECT_TYPE_PATCH_ENVELOPE_REFERENCE,
                OBJECT_TYPE_DEV_PASSTHROUGH, OBJECT_TYPE_EDGE_NODE_CLUSTER,
                OBJECT_TYPE_ASSET_GROUP, OBJECT_TYPE_APP_PROFILE,
                OBJECT_TYPE_PROFILE_DEPLOYMENT, OBJECT_TYPE_ZKS_INSTANCE,
                OBJECT_TYPE_CLUSTER_GROUP.

        ``GET /v1/jobs/name/{name}/objectType/{objectType}`` · operationId ``BulkJobOps_GetJobByName`` · read-only
        """
        return self._request(
            "GET",
            "/v1/jobs/name/{name}/objectType/{objectType}",
            path={"name": name, "objectType": object_type},
            response_model=JobConfig,
            request_id=request_id,
            operation_id="BulkJobOps_GetJobByName",
        )


class AsyncJobsService(AsyncBaseService):
    """ZEDEDA Job Service (async)."""

    _security = "bearer"

    async def query_jobs(
        self,
        *,
        summary: bool | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        job_status: int | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        request_id: str | None = None,
    ) -> JobConfigList:
        """Query asynchronous job requests

        Query the asynchronous job request records.

        Args:
            summary: Only summary count is required
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size
            job_status: status of the job
            project_name: project name
            name_pattern: name pattern of the job

        ``GET /v1/jobs`` · operationId ``BulkJobOps_QueryJobs`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/jobs",
            query={
                "summary": summary,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "jobStatus": job_status,
                "projectName": project_name,
                "namePattern": name_pattern,
            },
            response_model=JobConfigList,
            request_id=request_id,
            operation_id="BulkJobOps_QueryJobs",
        )

    def iter_jobs(
        self,
        *,
        summary: bool | None = None,
        order_by: Sequence[str] | None = None,
        job_status: int | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> AsyncIterator[JobConfig]:
        """Iterate over every result of :meth:`query_jobs`, fetching pages lazily.

        Args:
            summary: Only summary count is required
            job_status: status of the job
            project_name: project name
            name_pattern: name pattern of the job
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/jobs`` · operationId ``BulkJobOps_QueryJobs`` · read-only
        """
        return self._paginate(
            self.query_jobs,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            summary=summary,
            order_by=order_by,
            job_status=job_status,
            project_name=project_name,
            name_pattern=name_pattern,
        )

    async def create_job(
        self,
        body: JobConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create asynchronous job request

        Create an asynchronous job request record.

        ``POST /v1/jobs`` · operationId ``BulkJobOps_CreateJob`` · modifies state
        """
        return await self._request(
            "POST",
            "/v1/jobs",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_CreateJob",
        )

    async def bulk_import_edge_applications(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to import edge application bundles

        Update job request to import edge application bundle(s) from global App Store matching
        selection criteria.

        ``PUT /v1/jobs/apps/bundles/import`` · operationId ``BulkJobOps_BulkImportEdgeApplications`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/jobs/apps/bundles/import",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkImportEdgeApplications",
        )

    async def bulk_create_edge_application_instances(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to create edge application instances

        Update job request to create edge application instance(s) on edge node(s) matching
        selection criteria.

        ``PUT /v1/jobs/apps/instances/create`` · operationId ``BulkJobOps_BulkCreateEdgeApplicationInstances`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/jobs/apps/instances/create",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkCreateEdgeApplicationInstances",
        )

    async def bulk_refresh_edge_application_instances(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to refresh edge application instances

        Update job request to refresh edge application instances matching selection criteria.
        Update edge application instance(s) to the latest version of the edge application. This
        operation will result in a restart of the edge application instance(s).

        ``PUT /v1/jobs/apps/instances/refresh`` · operationId ``BulkJobOps_BulkRefreshEdgeApplicationInstances`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/jobs/apps/instances/refresh",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkRefreshEdgeApplicationInstances",
        )

    async def bulk_refresh_and_purge_edge_application_instances(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to refresh and purge edge application instances

        Update job request to refresh and purge edge application instances matching selection
        criteria. Update edge application instance(s) to the latest version of the edge
        application. This operation will result in loss of data and a restart of the edge
        application instance(s).

        ``PUT /v1/jobs/apps/instances/refresh/purge`` · operationId ``BulkJobOps_BulkRefreshAndPurgeEdgeApplicationInstances`` · DESTRUCTIVE
        """
        return await self._request(
            "PUT",
            "/v1/jobs/apps/instances/refresh/purge",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkRefreshAndPurgeEdgeApplicationInstances",
        )

    async def bulk_update_edge_node_base_os(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to update EVE image on edge nodes

        Update job request to update EVE image on edge nodes. If edge node is already running
        the latest EVE image no action is taken.

        ``PUT /v1/jobs/devices/baseos/upgrade`` · operationId ``BulkJobOps_BulkUpdateEdgeNodeBaseOS`` · DESTRUCTIVE
        """
        return await self._request(
            "PUT",
            "/v1/jobs/devices/baseos/upgrade",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkUpdateEdgeNodeBaseOS",
        )

    async def bulk_update_edge_node_base_os_retry(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to retry update EVE image on edge nodes

        Update job request to retry update EVE image on edge nodes. If edge node is already
        running the latest EVE image no action is taken.

        ``PUT /v1/jobs/devices/baseos/upgrade/retry`` · operationId ``BulkJobOps_BulkUpdateEdgeNodeBaseOSRetry`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/jobs/devices/baseos/upgrade/retry",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkUpdateEdgeNodeBaseOSRetry",
        )

    async def bulk_update_edge_node_base_os_deployment_tag(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to update Deployment tag on edge nodes in bulk.

        ``PUT /v1/jobs/devices/deployment/tags`` · operationId ``BulkJobOps_BulkUpdateEdgeNodeBaseOSDeploymentTag`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/jobs/devices/deployment/tags",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkUpdateEdgeNodeBaseOSDeploymentTag",
        )

    async def bulk_update_edge_node_base_os_project(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to update EVE image project and target on edge nodes

        Update job request to update EVE image project and target on edge nodes. If edge node is
        already running the latest EVE image no action is taken.

        ``PUT /v1/jobs/devices/project/target`` · operationId ``BulkJobOps_BulkUpdateEdgeNodeBaseOSProject`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/jobs/devices/project/target",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkUpdateEdgeNodeBaseOSProject",
        )

    async def bulk_update_edge_node_base_os_tag(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to update EVE image tag on edge nodes

        Update job request to update EVE image tag on edge nodes. If edge node is already
        running the latest EVE image no action is taken.

        ``PUT /v1/jobs/devices/tags`` · operationId ``BulkJobOps_BulkUpdateEdgeNodeBaseOSTag`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/jobs/devices/tags",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkUpdateEdgeNodeBaseOSTag",
        )

    async def get_job_by_id(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> JobConfig:
        """Get asynchronous job request

        Get the configuration and status of an asynchronous job request record.

        Args:
            id: System defined universally unique Id of the job request

        ``GET /v1/jobs/id/{id}`` · operationId ``BulkJobOps_GetJobById`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/jobs/id/{id}",
            path={"id": id},
            response_model=JobConfig,
            request_id=request_id,
            operation_id="BulkJobOps_GetJobById",
        )

    async def update_job(
        self,
        id: str,
        body: UpdateJobBody | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update asynchronous job request

        Update an asynchronous job request record. The usual pattern to update an asynchronous
        job request record is to retrieve the record and update with the modified values in a
        new body to update the asynchronous job request record.

        Args:
            id: System defined universally unique Id of the job request

        ``PUT /v1/jobs/id/{id}`` · operationId ``BulkJobOps_UpdateJob`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/jobs/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_UpdateJob",
        )

    async def get_job(
        self,
        id: str,
        object_type: str,
        *,
        request_id: str | None = None,
    ) -> JobConfig:
        """Get asynchronous job request

        Get the configuration and status of an asynchronous job request record.

        Args:
            id: System defined universally unique Id of the job request
            object_type: object type for which job has been created One of: OBJECT_TYPE_UNSPECIFIED,
                OBJECT_TYPE_USER, OBJECT_TYPE_EDGE_NODE, OBJECT_TYPE_EDGE_APP,
                OBJECT_TYPE_IMAGE, OBJECT_TYPE_EDGE_APP_INSTANCE, OBJECT_TYPE_PROJECT,
                OBJECT_TYPE_NETWORK, OBJECT_TYPE_DATASTORE, OBJECT_TYPE_SERVICE,
                OBJECT_TYPE_SERVICE_INSTANCE, OBJECT_TYPE_ENTERPRISE, OBJECT_TYPE_ROLE,
                OBJECT_TYPE_CREDENTIAL, OBJECT_TYPE_NETWORK_INSTANCE,
                OBJECT_TYPE_VOLUME_INSTANCE, OBJECT_TYPE_REALM, OBJECT_TYPE_AUTHPROFILE,
                OBJECT_TYPE_POLICY, OBJECT_TYPE_APP_POLICY, OBJECT_TYPE_CLUSTER_INSTANCE,
                OBJECT_TYPE_PLUGIN, OBJECT_TYPE_DOC_POLICY, OBJECT_TYPE_ORCHESTRATOR_CLUSTER,
                OBJECT_TYPE_TAGS, OBJECT_TYPE_EDGE_NODE_INTERFACE, OBJECT_TYPE_DEPLOYMENT,
                OBJECT_TYPE_ENTITLEMENTS, OBJECT_TYPE_DATA_STREAM, OBJECT_TYPE_API_USAGE,
                OBJECT_TYPE_APP_INSTANCE_SNAPSHOT, OBJECT_TYPE_PATCH_ENVELOPE,
                OBJECT_TYPE_RESOURCE_USAGE_TRACK, OBJECT_TYPE_PATCH_ENVELOPE_REFERENCE,
                OBJECT_TYPE_DEV_PASSTHROUGH, OBJECT_TYPE_EDGE_NODE_CLUSTER,
                OBJECT_TYPE_ASSET_GROUP, OBJECT_TYPE_APP_PROFILE,
                OBJECT_TYPE_PROFILE_DEPLOYMENT, OBJECT_TYPE_ZKS_INSTANCE,
                OBJECT_TYPE_CLUSTER_GROUP.

        ``GET /v1/jobs/id/{id}/objectType/{objectType}`` · operationId ``BulkJobOps_GetJob`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/jobs/id/{id}/objectType/{objectType}",
            path={"id": id, "objectType": object_type},
            response_model=JobConfig,
            request_id=request_id,
            operation_id="BulkJobOps_GetJob",
        )

    async def delete_job(
        self,
        id: str,
        object_type: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete asynchronous job request

        Delete an asynchronous job request record.

        Args:
            id: System defined universally unique Id of the job request
            object_type: object type for which job has been created One of: OBJECT_TYPE_UNSPECIFIED,
                OBJECT_TYPE_USER, OBJECT_TYPE_EDGE_NODE, OBJECT_TYPE_EDGE_APP,
                OBJECT_TYPE_IMAGE, OBJECT_TYPE_EDGE_APP_INSTANCE, OBJECT_TYPE_PROJECT,
                OBJECT_TYPE_NETWORK, OBJECT_TYPE_DATASTORE, OBJECT_TYPE_SERVICE,
                OBJECT_TYPE_SERVICE_INSTANCE, OBJECT_TYPE_ENTERPRISE, OBJECT_TYPE_ROLE,
                OBJECT_TYPE_CREDENTIAL, OBJECT_TYPE_NETWORK_INSTANCE,
                OBJECT_TYPE_VOLUME_INSTANCE, OBJECT_TYPE_REALM, OBJECT_TYPE_AUTHPROFILE,
                OBJECT_TYPE_POLICY, OBJECT_TYPE_APP_POLICY, OBJECT_TYPE_CLUSTER_INSTANCE,
                OBJECT_TYPE_PLUGIN, OBJECT_TYPE_DOC_POLICY, OBJECT_TYPE_ORCHESTRATOR_CLUSTER,
                OBJECT_TYPE_TAGS, OBJECT_TYPE_EDGE_NODE_INTERFACE, OBJECT_TYPE_DEPLOYMENT,
                OBJECT_TYPE_ENTITLEMENTS, OBJECT_TYPE_DATA_STREAM, OBJECT_TYPE_API_USAGE,
                OBJECT_TYPE_APP_INSTANCE_SNAPSHOT, OBJECT_TYPE_PATCH_ENVELOPE,
                OBJECT_TYPE_RESOURCE_USAGE_TRACK, OBJECT_TYPE_PATCH_ENVELOPE_REFERENCE,
                OBJECT_TYPE_DEV_PASSTHROUGH, OBJECT_TYPE_EDGE_NODE_CLUSTER,
                OBJECT_TYPE_ASSET_GROUP, OBJECT_TYPE_APP_PROFILE,
                OBJECT_TYPE_PROFILE_DEPLOYMENT, OBJECT_TYPE_ZKS_INSTANCE,
                OBJECT_TYPE_CLUSTER_GROUP.

        ``DELETE /v1/jobs/id/{id}/objectType/{objectType}`` · operationId ``BulkJobOps_DeleteJob`` · DESTRUCTIVE
        """
        return await self._request(
            "DELETE",
            "/v1/jobs/id/{id}/objectType/{objectType}",
            path={"id": id, "objectType": object_type},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_DeleteJob",
        )

    async def bulk_import_hardware_models(
        self,
        body: BulkConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update job request to import hardware models

        Update job request to import hardware model(s) from global Model Store matching
        selection criteria.

        ``PUT /v1/jobs/models/import`` · operationId ``BulkJobOps_BulkImportHardwareModels`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/jobs/models/import",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="BulkJobOps_BulkImportHardwareModels",
        )

    async def get_job_by_name(
        self,
        name: str,
        object_type: str,
        *,
        request_id: str | None = None,
    ) -> JobConfig:
        """Get asynchronous job request

        Get the configuration and status of an asynchronous job request record.

        Args:
            name: User defined name of the job request, unique across the enterprise. Once object
                is created, name can’t be changed
            object_type: object type for which job has been created One of: OBJECT_TYPE_UNSPECIFIED,
                OBJECT_TYPE_USER, OBJECT_TYPE_EDGE_NODE, OBJECT_TYPE_EDGE_APP,
                OBJECT_TYPE_IMAGE, OBJECT_TYPE_EDGE_APP_INSTANCE, OBJECT_TYPE_PROJECT,
                OBJECT_TYPE_NETWORK, OBJECT_TYPE_DATASTORE, OBJECT_TYPE_SERVICE,
                OBJECT_TYPE_SERVICE_INSTANCE, OBJECT_TYPE_ENTERPRISE, OBJECT_TYPE_ROLE,
                OBJECT_TYPE_CREDENTIAL, OBJECT_TYPE_NETWORK_INSTANCE,
                OBJECT_TYPE_VOLUME_INSTANCE, OBJECT_TYPE_REALM, OBJECT_TYPE_AUTHPROFILE,
                OBJECT_TYPE_POLICY, OBJECT_TYPE_APP_POLICY, OBJECT_TYPE_CLUSTER_INSTANCE,
                OBJECT_TYPE_PLUGIN, OBJECT_TYPE_DOC_POLICY, OBJECT_TYPE_ORCHESTRATOR_CLUSTER,
                OBJECT_TYPE_TAGS, OBJECT_TYPE_EDGE_NODE_INTERFACE, OBJECT_TYPE_DEPLOYMENT,
                OBJECT_TYPE_ENTITLEMENTS, OBJECT_TYPE_DATA_STREAM, OBJECT_TYPE_API_USAGE,
                OBJECT_TYPE_APP_INSTANCE_SNAPSHOT, OBJECT_TYPE_PATCH_ENVELOPE,
                OBJECT_TYPE_RESOURCE_USAGE_TRACK, OBJECT_TYPE_PATCH_ENVELOPE_REFERENCE,
                OBJECT_TYPE_DEV_PASSTHROUGH, OBJECT_TYPE_EDGE_NODE_CLUSTER,
                OBJECT_TYPE_ASSET_GROUP, OBJECT_TYPE_APP_PROFILE,
                OBJECT_TYPE_PROFILE_DEPLOYMENT, OBJECT_TYPE_ZKS_INSTANCE,
                OBJECT_TYPE_CLUSTER_GROUP.

        ``GET /v1/jobs/name/{name}/objectType/{objectType}`` · operationId ``BulkJobOps_GetJobByName`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/jobs/name/{name}/objectType/{objectType}",
            path={"name": name, "objectType": object_type},
            response_model=JobConfig,
            request_id=request_id,
            operation_id="BulkJobOps_GetJobByName",
        )
