# Generated by scripts/generate.py from openapi/*.swagger.json. Do not edit.
"""ZEDEDA Edge Network Service — generated sync and async clients."""

from __future__ import annotations

import typing as _t
from collections.abc import AsyncIterator, Iterator, Mapping, Sequence

from zedcloud._service import AsyncBaseService, BaseService, FileContent
from zedcloud._generated.models import (
    NetConfig,
    NetConfigForUpdateHttpRequest,
    NetConfigList,
    NetInstConfig,
    NetInstConfigStatus,
    NetInstConfigStatusList,
    NetInstConfigUpdateHttpRequest,
    NetInstList,
    NetInstShortConfig,
    NetInstStatusListMsg,
    NetInstStatusMsg,
    NetInstStatusSummaryMsg,
    NetworkDeviceList,
    ObjectTagsList,
    ZsrvResponse,
)


class NetworksService(BaseService):
    """ZEDEDA Edge Network Service (sync)."""

    _security = "bearer"

    def query_edge_network_instances(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        summary: bool | None = None,
        title_pattern: str | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        fields: Sequence[str] | None = None,
        request_id: str | None = None,
    ) -> NetInstList:
        """Query edge network instances

        Query the edge network instance records.

        Args:
            title_pattern: title pattern
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/netinsts`` · operationId ``EdgeNetworkInstanceConfiguration_QueryEdgeNetworkInstances`` · read-only
        """
        return self._request(
            "GET",
            "/v1/netinsts",
            query={
                "deviceName": device_name,
                "projectName": project_name,
                "namePattern": name_pattern,
                "tags": tags,
                "deviceNamePattern": device_name_pattern,
                "projectNamePattern": project_name_pattern,
                "summary": summary,
                "titlePattern": title_pattern,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "fields": fields,
            },
            response_model=NetInstList,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_QueryEdgeNetworkInstances",
        )

    def iter_edge_network_instances(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        summary: bool | None = None,
        title_pattern: str | None = None,
        order_by: Sequence[str] | None = None,
        fields: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> Iterator[NetInstShortConfig]:
        """Iterate over every result of :meth:`query_edge_network_instances`, fetching pages lazily.

        Args:
            title_pattern: title pattern
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/netinsts`` · operationId ``EdgeNetworkInstanceConfiguration_QueryEdgeNetworkInstances`` · read-only
        """
        return self._paginate(
            self.query_edge_network_instances,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            device_name=device_name,
            project_name=project_name,
            name_pattern=name_pattern,
            tags=tags,
            device_name_pattern=device_name_pattern,
            project_name_pattern=project_name_pattern,
            summary=summary,
            title_pattern=title_pattern,
            order_by=order_by,
            fields=fields,
        )

    def create_edge_network_instance(
        self,
        body: NetInstConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create edge network instance

        Create an edge network instance record.

        ``POST /v1/netinsts`` · operationId ``EdgeNetworkInstanceConfiguration_CreateEdgeNetworkInstance`` · modifies state
        """
        return self._request(
            "POST",
            "/v1/netinsts",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_CreateEdgeNetworkInstance",
        )

    def get_edge_network_instance(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> NetInstConfig:
        """Get edge network instance

        Get the configuration (without security details) of an edge network instance record.

        Args:
            id: System defined universally unique Id of the network instance

        ``GET /v1/netinsts/id/{id}`` · operationId ``EdgeNetworkInstanceConfiguration_GetEdgeNetworkInstance`` · read-only
        """
        return self._request(
            "GET",
            "/v1/netinsts/id/{id}",
            path={"id": id},
            response_model=NetInstConfig,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_GetEdgeNetworkInstance",
        )

    def update_edge_network_instance(
        self,
        id: str,
        body: NetInstConfigUpdateHttpRequest | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update edge network instance

        Update an edge network instance. The usual pattern to update an edge network instance
        record is to retrieve the record and update with the modified values in a new body to
        update the edge network instance record.

        ``PUT /v1/netinsts/id/{id}`` · operationId ``EdgeNetworkInstanceConfiguration_UpdateEdgeNetworkInstance`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/netinsts/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_UpdateEdgeNetworkInstance",
        )

    def delete_edge_network_instance(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete edge network instance

        Delete an edge network instance record.

        Args:
            id: System defined universally unique Id of the network instance

        ``DELETE /v1/netinsts/id/{id}`` · operationId ``EdgeNetworkInstanceConfiguration_DeleteEdgeNetworkInstance`` · DESTRUCTIVE
        """
        return self._request(
            "DELETE",
            "/v1/netinsts/id/{id}",
            path={"id": id},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_DeleteEdgeNetworkInstance",
        )

    def get_edge_network_instance_status(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> NetInstStatusMsg:
        """Get edge network instance status

        Get the status of an edge network instance as reported by the edge node where the edge
        network instance has been deployed.

        ``GET /v1/netinsts/id/{id}/status`` · operationId ``EdgeNetworkInstanceStatus_GetEdgeNetworkInstanceStatus`` · read-only
        """
        return self._request(
            "GET",
            "/v1/netinsts/id/{id}/status",
            path={"id": id},
            response_model=NetInstStatusMsg,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceStatus_GetEdgeNetworkInstanceStatus",
        )

    def get_edge_network_instance_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> NetInstConfig:
        """Get edge network instance

        Get the configuration (without security details) of an edge network instance record.

        Args:
            name: User defined name of the network instance, unique across the enterprise. Once
                object is created, name can’t be changed

        ``GET /v1/netinsts/name/{name}`` · operationId ``EdgeNetworkInstanceConfiguration_GetEdgeNetworkInstanceByName`` · read-only
        """
        return self._request(
            "GET",
            "/v1/netinsts/name/{name}",
            path={"name": name},
            response_model=NetInstConfig,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_GetEdgeNetworkInstanceByName",
        )

    def get_edge_network_instance_status_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> NetInstStatusMsg:
        """Get edge network instance status

        Get the status of an edge network instance as reported by the edge node where the edge
        network instance has been deployed.

        ``GET /v1/netinsts/name/{name}/status`` · operationId ``EdgeNetworkInstanceStatus_GetEdgeNetworkInstanceStatusByName`` · read-only
        """
        return self._request(
            "GET",
            "/v1/netinsts/name/{name}/status",
            path={"name": name},
            response_model=NetInstStatusMsg,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceStatus_GetEdgeNetworkInstanceStatusByName",
        )

    def query_edge_network_instance_status(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        run_state: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        type: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        fields: Sequence[str] | None = None,
        request_id: str | None = None,
    ) -> NetInstStatusListMsg:
        """Query status of edge network instances

        Query the status of edge network instances as reported by the edge nodes where the edge
        network instances have been deployed.

        Args:
            run_state: One of: UNSPECIFIED, ONLINE, HALTED, INIT, REBOOTING, OFFLINE, UNKNOWN,
                UNPROVISIONED, PROVISIONED, SUSPECT, DOWNLOADING, RESTARTING, PURGING, HALTING,
                ERROR, VERIFYING, LOADING, CREATING_VOLUME, BOOTING, MAINTENANCE_MODE,
                START_DELAYED, BASEOS_UPDATING, PREPARING_POWEROFF, POWERING_OFF,
                PREPARED_POWEROFF.
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/netinsts/status`` · operationId ``EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatus`` · read-only
        """
        return self._request(
            "GET",
            "/v1/netinsts/status",
            query={
                "deviceName": device_name,
                "projectName": project_name,
                "namePattern": name_pattern,
                "tags": tags,
                "runState": run_state,
                "deviceNamePattern": device_name_pattern,
                "projectNamePattern": project_name_pattern,
                "type": type,
                "kind": kind,
                "summary": summary,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "fields": fields,
            },
            response_model=NetInstStatusListMsg,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatus",
        )

    def iter_edge_network_instance_status(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        run_state: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        type: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        order_by: Sequence[str] | None = None,
        fields: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> Iterator[NetInstStatusSummaryMsg]:
        """Iterate over every result of :meth:`query_edge_network_instance_status`, fetching pages lazily.

        Args:
            run_state: One of: UNSPECIFIED, ONLINE, HALTED, INIT, REBOOTING, OFFLINE, UNKNOWN,
                UNPROVISIONED, PROVISIONED, SUSPECT, DOWNLOADING, RESTARTING, PURGING, HALTING,
                ERROR, VERIFYING, LOADING, CREATING_VOLUME, BOOTING, MAINTENANCE_MODE,
                START_DELAYED, BASEOS_UPDATING, PREPARING_POWEROFF, POWERING_OFF,
                PREPARED_POWEROFF.
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/netinsts/status`` · operationId ``EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatus`` · read-only
        """
        return self._paginate(
            self.query_edge_network_instance_status,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            device_name=device_name,
            project_name=project_name,
            name_pattern=name_pattern,
            tags=tags,
            run_state=run_state,
            device_name_pattern=device_name_pattern,
            project_name_pattern=project_name_pattern,
            type=type,
            kind=kind,
            summary=summary,
            order_by=order_by,
            fields=fields,
        )

    def query_edge_network_instance_status_config(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        run_state: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        type: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        fields: Sequence[str] | None = None,
        request_id: str | None = None,
    ) -> NetInstConfigStatusList:
        """Query status and config of edge network instances

        Query the status and config of edge network instances as reported by the edge nodes
        where the edge network instances have been deployed.

        Args:
            run_state: One of: UNSPECIFIED, ONLINE, HALTED, INIT, REBOOTING, OFFLINE, UNKNOWN,
                UNPROVISIONED, PROVISIONED, SUSPECT, DOWNLOADING, RESTARTING, PURGING, HALTING,
                ERROR, VERIFYING, LOADING, CREATING_VOLUME, BOOTING, MAINTENANCE_MODE,
                START_DELAYED, BASEOS_UPDATING, PREPARING_POWEROFF, POWERING_OFF,
                PREPARED_POWEROFF.
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/netinsts/status-config`` · operationId ``EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatusConfig`` · read-only
        """
        return self._request(
            "GET",
            "/v1/netinsts/status-config",
            query={
                "deviceName": device_name,
                "projectName": project_name,
                "namePattern": name_pattern,
                "tags": tags,
                "runState": run_state,
                "deviceNamePattern": device_name_pattern,
                "projectNamePattern": project_name_pattern,
                "type": type,
                "kind": kind,
                "summary": summary,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "fields": fields,
            },
            response_model=NetInstConfigStatusList,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatusConfig",
        )

    def iter_edge_network_instance_status_config(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        run_state: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        type: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        order_by: Sequence[str] | None = None,
        fields: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> Iterator[NetInstConfigStatus]:
        """Iterate over every result of :meth:`query_edge_network_instance_status_config`, fetching pages lazily.

        Args:
            run_state: One of: UNSPECIFIED, ONLINE, HALTED, INIT, REBOOTING, OFFLINE, UNKNOWN,
                UNPROVISIONED, PROVISIONED, SUSPECT, DOWNLOADING, RESTARTING, PURGING, HALTING,
                ERROR, VERIFYING, LOADING, CREATING_VOLUME, BOOTING, MAINTENANCE_MODE,
                START_DELAYED, BASEOS_UPDATING, PREPARING_POWEROFF, POWERING_OFF,
                PREPARED_POWEROFF.
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/netinsts/status-config`` · operationId ``EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatusConfig`` · read-only
        """
        return self._paginate(
            self.query_edge_network_instance_status_config,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            device_name=device_name,
            project_name=project_name,
            name_pattern=name_pattern,
            tags=tags,
            run_state=run_state,
            device_name_pattern=device_name_pattern,
            project_name_pattern=project_name_pattern,
            type=type,
            kind=kind,
            summary=summary,
            order_by=order_by,
            fields=fields,
        )

    def get_network_instance_interface_tags(
        self,
        *,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        request_id: str | None = None,
    ) -> ObjectTagsList:
        """Query Network instance tags

        Netork instance tags LIST API is to fetch the interfaces tags attached to app instances.

        Args:
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/netinsts/tags`` · operationId ``EdgeNetworkInstanceStatus_GetNetworkInstanceInterfaceTags`` · read-only
        """
        return self._request(
            "GET",
            "/v1/netinsts/tags",
            query={
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
            },
            response_model=ObjectTagsList,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceStatus_GetNetworkInstanceInterfaceTags",
        )

    def query_edge_networks(
        self,
        *,
        project_name: str | None = None,
        name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        dist: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        default_network: bool | None = None,
        title_pattern: str | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        request_id: str | None = None,
    ) -> NetConfigList:
        """Query edge networks

        Query the edge network records.

        Args:
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/networks`` · operationId ``EdgeNetworkConfiguration_QueryEdgeNetworks`` · read-only
        """
        return self._request(
            "GET",
            "/v1/networks",
            query={
                "projectName": project_name,
                "namePattern": name_pattern,
                "projectNamePattern": project_name_pattern,
                "dist": dist,
                "kind": kind,
                "summary": summary,
                "defaultNetwork": default_network,
                "titlePattern": title_pattern,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
            },
            response_model=NetConfigList,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_QueryEdgeNetworks",
        )

    def iter_edge_networks(
        self,
        *,
        project_name: str | None = None,
        name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        dist: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        default_network: bool | None = None,
        title_pattern: str | None = None,
        order_by: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> Iterator[NetConfig]:
        """Iterate over every result of :meth:`query_edge_networks`, fetching pages lazily.

        Args:
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/networks`` · operationId ``EdgeNetworkConfiguration_QueryEdgeNetworks`` · read-only
        """
        return self._paginate(
            self.query_edge_networks,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            project_name=project_name,
            name_pattern=name_pattern,
            project_name_pattern=project_name_pattern,
            dist=dist,
            kind=kind,
            summary=summary,
            default_network=default_network,
            title_pattern=title_pattern,
            order_by=order_by,
        )

    def create_edge_network(
        self,
        body: NetConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create edge network

        Create an edge network record.

        ``POST /v1/networks`` · operationId ``EdgeNetworkConfiguration_CreateEdgeNetwork`` · modifies state
        """
        return self._request(
            "POST",
            "/v1/networks",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_CreateEdgeNetwork",
        )

    def get_edge_network(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> NetConfig:
        """Get edge network

        Get the configuration (without security details) of an edge network record.

        Args:
            id: System defined universally unique Id of the network

        ``GET /v1/networks/id/{id}`` · operationId ``EdgeNetworkConfiguration_GetEdgeNetwork`` · read-only
        """
        return self._request(
            "GET",
            "/v1/networks/id/{id}",
            path={"id": id},
            response_model=NetConfig,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_GetEdgeNetwork",
        )

    def update_edge_network(
        self,
        id: str,
        body: NetConfigForUpdateHttpRequest | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update edge network

        Update an edge network. The usual pattern to update an edge network record is to
        retrieve the record and update with the modified values in a new body to update the edge
        network record.

        ``PUT /v1/networks/id/{id}`` · operationId ``EdgeNetworkConfiguration_UpdateEdgeNetwork`` · modifies state
        """
        return self._request(
            "PUT",
            "/v1/networks/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_UpdateEdgeNetwork",
        )

    def delete_edge_network(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete edge network

        Delete an edge network record.

        Args:
            id: System defined universally unique Id of the network

        ``DELETE /v1/networks/id/{id}`` · operationId ``EdgeNetworkConfiguration_DeleteEdgeNetwork`` · DESTRUCTIVE
        """
        return self._request(
            "DELETE",
            "/v1/networks/id/{id}",
            path={"id": id},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_DeleteEdgeNetwork",
        )

    def get_edge_network_devices_by_id(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> NetworkDeviceList:
        """Get edge network devices by id

        Get the list of devices associated with the specified network.

        Args:
            id: System defined universally unique Id of the network

        ``GET /v1/networks/id/{id}/devices`` · operationId ``EdgeNetworkConfiguration_GetEdgeNetworkDevicesById`` · read-only
        """
        return self._request(
            "GET",
            "/v1/networks/id/{id}/devices",
            path={"id": id},
            response_model=NetworkDeviceList,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_GetEdgeNetworkDevicesById",
        )

    def get_edge_network_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> NetConfig:
        """Get edge network

        Get the configuration (without security details) of an edge network record.

        Args:
            name: User defined name of the network, unique across the enterprise. Once object is
                created, name can’t be changed

        ``GET /v1/networks/name/{name}`` · operationId ``EdgeNetworkConfiguration_GetEdgeNetworkByName`` · read-only
        """
        return self._request(
            "GET",
            "/v1/networks/name/{name}",
            path={"name": name},
            response_model=NetConfig,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_GetEdgeNetworkByName",
        )


class AsyncNetworksService(AsyncBaseService):
    """ZEDEDA Edge Network Service (async)."""

    _security = "bearer"

    async def query_edge_network_instances(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        summary: bool | None = None,
        title_pattern: str | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        fields: Sequence[str] | None = None,
        request_id: str | None = None,
    ) -> NetInstList:
        """Query edge network instances

        Query the edge network instance records.

        Args:
            title_pattern: title pattern
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/netinsts`` · operationId ``EdgeNetworkInstanceConfiguration_QueryEdgeNetworkInstances`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/netinsts",
            query={
                "deviceName": device_name,
                "projectName": project_name,
                "namePattern": name_pattern,
                "tags": tags,
                "deviceNamePattern": device_name_pattern,
                "projectNamePattern": project_name_pattern,
                "summary": summary,
                "titlePattern": title_pattern,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "fields": fields,
            },
            response_model=NetInstList,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_QueryEdgeNetworkInstances",
        )

    def iter_edge_network_instances(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        summary: bool | None = None,
        title_pattern: str | None = None,
        order_by: Sequence[str] | None = None,
        fields: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> AsyncIterator[NetInstShortConfig]:
        """Iterate over every result of :meth:`query_edge_network_instances`, fetching pages lazily.

        Args:
            title_pattern: title pattern
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/netinsts`` · operationId ``EdgeNetworkInstanceConfiguration_QueryEdgeNetworkInstances`` · read-only
        """
        return self._paginate(
            self.query_edge_network_instances,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            device_name=device_name,
            project_name=project_name,
            name_pattern=name_pattern,
            tags=tags,
            device_name_pattern=device_name_pattern,
            project_name_pattern=project_name_pattern,
            summary=summary,
            title_pattern=title_pattern,
            order_by=order_by,
            fields=fields,
        )

    async def create_edge_network_instance(
        self,
        body: NetInstConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create edge network instance

        Create an edge network instance record.

        ``POST /v1/netinsts`` · operationId ``EdgeNetworkInstanceConfiguration_CreateEdgeNetworkInstance`` · modifies state
        """
        return await self._request(
            "POST",
            "/v1/netinsts",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_CreateEdgeNetworkInstance",
        )

    async def get_edge_network_instance(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> NetInstConfig:
        """Get edge network instance

        Get the configuration (without security details) of an edge network instance record.

        Args:
            id: System defined universally unique Id of the network instance

        ``GET /v1/netinsts/id/{id}`` · operationId ``EdgeNetworkInstanceConfiguration_GetEdgeNetworkInstance`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/netinsts/id/{id}",
            path={"id": id},
            response_model=NetInstConfig,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_GetEdgeNetworkInstance",
        )

    async def update_edge_network_instance(
        self,
        id: str,
        body: NetInstConfigUpdateHttpRequest | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update edge network instance

        Update an edge network instance. The usual pattern to update an edge network instance
        record is to retrieve the record and update with the modified values in a new body to
        update the edge network instance record.

        ``PUT /v1/netinsts/id/{id}`` · operationId ``EdgeNetworkInstanceConfiguration_UpdateEdgeNetworkInstance`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/netinsts/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_UpdateEdgeNetworkInstance",
        )

    async def delete_edge_network_instance(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete edge network instance

        Delete an edge network instance record.

        Args:
            id: System defined universally unique Id of the network instance

        ``DELETE /v1/netinsts/id/{id}`` · operationId ``EdgeNetworkInstanceConfiguration_DeleteEdgeNetworkInstance`` · DESTRUCTIVE
        """
        return await self._request(
            "DELETE",
            "/v1/netinsts/id/{id}",
            path={"id": id},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_DeleteEdgeNetworkInstance",
        )

    async def get_edge_network_instance_status(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> NetInstStatusMsg:
        """Get edge network instance status

        Get the status of an edge network instance as reported by the edge node where the edge
        network instance has been deployed.

        ``GET /v1/netinsts/id/{id}/status`` · operationId ``EdgeNetworkInstanceStatus_GetEdgeNetworkInstanceStatus`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/netinsts/id/{id}/status",
            path={"id": id},
            response_model=NetInstStatusMsg,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceStatus_GetEdgeNetworkInstanceStatus",
        )

    async def get_edge_network_instance_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> NetInstConfig:
        """Get edge network instance

        Get the configuration (without security details) of an edge network instance record.

        Args:
            name: User defined name of the network instance, unique across the enterprise. Once
                object is created, name can’t be changed

        ``GET /v1/netinsts/name/{name}`` · operationId ``EdgeNetworkInstanceConfiguration_GetEdgeNetworkInstanceByName`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/netinsts/name/{name}",
            path={"name": name},
            response_model=NetInstConfig,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceConfiguration_GetEdgeNetworkInstanceByName",
        )

    async def get_edge_network_instance_status_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> NetInstStatusMsg:
        """Get edge network instance status

        Get the status of an edge network instance as reported by the edge node where the edge
        network instance has been deployed.

        ``GET /v1/netinsts/name/{name}/status`` · operationId ``EdgeNetworkInstanceStatus_GetEdgeNetworkInstanceStatusByName`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/netinsts/name/{name}/status",
            path={"name": name},
            response_model=NetInstStatusMsg,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceStatus_GetEdgeNetworkInstanceStatusByName",
        )

    async def query_edge_network_instance_status(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        run_state: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        type: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        fields: Sequence[str] | None = None,
        request_id: str | None = None,
    ) -> NetInstStatusListMsg:
        """Query status of edge network instances

        Query the status of edge network instances as reported by the edge nodes where the edge
        network instances have been deployed.

        Args:
            run_state: One of: UNSPECIFIED, ONLINE, HALTED, INIT, REBOOTING, OFFLINE, UNKNOWN,
                UNPROVISIONED, PROVISIONED, SUSPECT, DOWNLOADING, RESTARTING, PURGING, HALTING,
                ERROR, VERIFYING, LOADING, CREATING_VOLUME, BOOTING, MAINTENANCE_MODE,
                START_DELAYED, BASEOS_UPDATING, PREPARING_POWEROFF, POWERING_OFF,
                PREPARED_POWEROFF.
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/netinsts/status`` · operationId ``EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatus`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/netinsts/status",
            query={
                "deviceName": device_name,
                "projectName": project_name,
                "namePattern": name_pattern,
                "tags": tags,
                "runState": run_state,
                "deviceNamePattern": device_name_pattern,
                "projectNamePattern": project_name_pattern,
                "type": type,
                "kind": kind,
                "summary": summary,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "fields": fields,
            },
            response_model=NetInstStatusListMsg,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatus",
        )

    def iter_edge_network_instance_status(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        run_state: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        type: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        order_by: Sequence[str] | None = None,
        fields: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> AsyncIterator[NetInstStatusSummaryMsg]:
        """Iterate over every result of :meth:`query_edge_network_instance_status`, fetching pages lazily.

        Args:
            run_state: One of: UNSPECIFIED, ONLINE, HALTED, INIT, REBOOTING, OFFLINE, UNKNOWN,
                UNPROVISIONED, PROVISIONED, SUSPECT, DOWNLOADING, RESTARTING, PURGING, HALTING,
                ERROR, VERIFYING, LOADING, CREATING_VOLUME, BOOTING, MAINTENANCE_MODE,
                START_DELAYED, BASEOS_UPDATING, PREPARING_POWEROFF, POWERING_OFF,
                PREPARED_POWEROFF.
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/netinsts/status`` · operationId ``EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatus`` · read-only
        """
        return self._paginate(
            self.query_edge_network_instance_status,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            device_name=device_name,
            project_name=project_name,
            name_pattern=name_pattern,
            tags=tags,
            run_state=run_state,
            device_name_pattern=device_name_pattern,
            project_name_pattern=project_name_pattern,
            type=type,
            kind=kind,
            summary=summary,
            order_by=order_by,
            fields=fields,
        )

    async def query_edge_network_instance_status_config(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        run_state: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        type: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        fields: Sequence[str] | None = None,
        request_id: str | None = None,
    ) -> NetInstConfigStatusList:
        """Query status and config of edge network instances

        Query the status and config of edge network instances as reported by the edge nodes
        where the edge network instances have been deployed.

        Args:
            run_state: One of: UNSPECIFIED, ONLINE, HALTED, INIT, REBOOTING, OFFLINE, UNKNOWN,
                UNPROVISIONED, PROVISIONED, SUSPECT, DOWNLOADING, RESTARTING, PURGING, HALTING,
                ERROR, VERIFYING, LOADING, CREATING_VOLUME, BOOTING, MAINTENANCE_MODE,
                START_DELAYED, BASEOS_UPDATING, PREPARING_POWEROFF, POWERING_OFF,
                PREPARED_POWEROFF.
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/netinsts/status-config`` · operationId ``EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatusConfig`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/netinsts/status-config",
            query={
                "deviceName": device_name,
                "projectName": project_name,
                "namePattern": name_pattern,
                "tags": tags,
                "runState": run_state,
                "deviceNamePattern": device_name_pattern,
                "projectNamePattern": project_name_pattern,
                "type": type,
                "kind": kind,
                "summary": summary,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
                "fields": fields,
            },
            response_model=NetInstConfigStatusList,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatusConfig",
        )

    def iter_edge_network_instance_status_config(
        self,
        *,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        run_state: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        type: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        order_by: Sequence[str] | None = None,
        fields: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> AsyncIterator[NetInstConfigStatus]:
        """Iterate over every result of :meth:`query_edge_network_instance_status_config`, fetching pages lazily.

        Args:
            run_state: One of: UNSPECIFIED, ONLINE, HALTED, INIT, REBOOTING, OFFLINE, UNKNOWN,
                UNPROVISIONED, PROVISIONED, SUSPECT, DOWNLOADING, RESTARTING, PURGING, HALTING,
                ERROR, VERIFYING, LOADING, CREATING_VOLUME, BOOTING, MAINTENANCE_MODE,
                START_DELAYED, BASEOS_UPDATING, PREPARING_POWEROFF, POWERING_OFF,
                PREPARED_POWEROFF.
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/netinsts/status-config`` · operationId ``EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatusConfig`` · read-only
        """
        return self._paginate(
            self.query_edge_network_instance_status_config,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            device_name=device_name,
            project_name=project_name,
            name_pattern=name_pattern,
            tags=tags,
            run_state=run_state,
            device_name_pattern=device_name_pattern,
            project_name_pattern=project_name_pattern,
            type=type,
            kind=kind,
            summary=summary,
            order_by=order_by,
            fields=fields,
        )

    async def get_network_instance_interface_tags(
        self,
        *,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        request_id: str | None = None,
    ) -> ObjectTagsList:
        """Query Network instance tags

        Netork instance tags LIST API is to fetch the interfaces tags attached to app instances.

        Args:
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/netinsts/tags`` · operationId ``EdgeNetworkInstanceStatus_GetNetworkInstanceInterfaceTags`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/netinsts/tags",
            query={
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
            },
            response_model=ObjectTagsList,
            request_id=request_id,
            operation_id="EdgeNetworkInstanceStatus_GetNetworkInstanceInterfaceTags",
        )

    async def query_edge_networks(
        self,
        *,
        project_name: str | None = None,
        name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        dist: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        default_network: bool | None = None,
        title_pattern: str | None = None,
        page_token: str | None = None,
        order_by: Sequence[str] | None = None,
        page_num: int | None = None,
        page_size: int | None = None,
        request_id: str | None = None,
    ) -> NetConfigList:
        """Query edge networks

        Query the edge network records.

        Args:
            page_token: Page Token
            order_by: OrderBy helps in sorting the list response
            page_num: Page Number
            page_size: Defines the page size

        ``GET /v1/networks`` · operationId ``EdgeNetworkConfiguration_QueryEdgeNetworks`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/networks",
            query={
                "projectName": project_name,
                "namePattern": name_pattern,
                "projectNamePattern": project_name_pattern,
                "dist": dist,
                "kind": kind,
                "summary": summary,
                "defaultNetwork": default_network,
                "titlePattern": title_pattern,
                "next.pageToken": page_token,
                "next.orderBy": order_by,
                "next.pageNum": page_num,
                "next.pageSize": page_size,
            },
            response_model=NetConfigList,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_QueryEdgeNetworks",
        )

    def iter_edge_networks(
        self,
        *,
        project_name: str | None = None,
        name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        dist: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        default_network: bool | None = None,
        title_pattern: str | None = None,
        order_by: Sequence[str] | None = None,
        page_size: int = 100,
        max_items: int | None = None,
        request_id: str | None = None,
    ) -> AsyncIterator[NetConfig]:
        """Iterate over every result of :meth:`query_edge_networks`, fetching pages lazily.

        Args:
            page_size: Items requested per page.
            max_items: Stop after yielding this many items.

        ``GET /v1/networks`` · operationId ``EdgeNetworkConfiguration_QueryEdgeNetworks`` · read-only
        """
        return self._paginate(
            self.query_edge_networks,
            page_size=page_size,
            max_items=max_items,
            request_id=request_id,
            project_name=project_name,
            name_pattern=name_pattern,
            project_name_pattern=project_name_pattern,
            dist=dist,
            kind=kind,
            summary=summary,
            default_network=default_network,
            title_pattern=title_pattern,
            order_by=order_by,
        )

    async def create_edge_network(
        self,
        body: NetConfig | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Create edge network

        Create an edge network record.

        ``POST /v1/networks`` · operationId ``EdgeNetworkConfiguration_CreateEdgeNetwork`` · modifies state
        """
        return await self._request(
            "POST",
            "/v1/networks",
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_CreateEdgeNetwork",
        )

    async def get_edge_network(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> NetConfig:
        """Get edge network

        Get the configuration (without security details) of an edge network record.

        Args:
            id: System defined universally unique Id of the network

        ``GET /v1/networks/id/{id}`` · operationId ``EdgeNetworkConfiguration_GetEdgeNetwork`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/networks/id/{id}",
            path={"id": id},
            response_model=NetConfig,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_GetEdgeNetwork",
        )

    async def update_edge_network(
        self,
        id: str,
        body: NetConfigForUpdateHttpRequest | Mapping[str, _t.Any],
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update edge network

        Update an edge network. The usual pattern to update an edge network record is to
        retrieve the record and update with the modified values in a new body to update the edge
        network record.

        ``PUT /v1/networks/id/{id}`` · operationId ``EdgeNetworkConfiguration_UpdateEdgeNetwork`` · modifies state
        """
        return await self._request(
            "PUT",
            "/v1/networks/id/{id}",
            path={"id": id},
            body=body,
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_UpdateEdgeNetwork",
        )

    async def delete_edge_network(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Delete edge network

        Delete an edge network record.

        Args:
            id: System defined universally unique Id of the network

        ``DELETE /v1/networks/id/{id}`` · operationId ``EdgeNetworkConfiguration_DeleteEdgeNetwork`` · DESTRUCTIVE
        """
        return await self._request(
            "DELETE",
            "/v1/networks/id/{id}",
            path={"id": id},
            response_model=ZsrvResponse,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_DeleteEdgeNetwork",
        )

    async def get_edge_network_devices_by_id(
        self,
        id: str,
        *,
        request_id: str | None = None,
    ) -> NetworkDeviceList:
        """Get edge network devices by id

        Get the list of devices associated with the specified network.

        Args:
            id: System defined universally unique Id of the network

        ``GET /v1/networks/id/{id}/devices`` · operationId ``EdgeNetworkConfiguration_GetEdgeNetworkDevicesById`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/networks/id/{id}/devices",
            path={"id": id},
            response_model=NetworkDeviceList,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_GetEdgeNetworkDevicesById",
        )

    async def get_edge_network_by_name(
        self,
        name: str,
        *,
        request_id: str | None = None,
    ) -> NetConfig:
        """Get edge network

        Get the configuration (without security details) of an edge network record.

        Args:
            name: User defined name of the network, unique across the enterprise. Once object is
                created, name can’t be changed

        ``GET /v1/networks/name/{name}`` · operationId ``EdgeNetworkConfiguration_GetEdgeNetworkByName`` · read-only
        """
        return await self._request(
            "GET",
            "/v1/networks/name/{name}",
            path={"name": name},
            response_model=NetConfig,
            request_id=request_id,
            operation_id="EdgeNetworkConfiguration_GetEdgeNetworkByName",
        )
