# Generated by scripts/generate_from_openapi.py — namespace "networks"
# Do not edit by hand.

from __future__ import annotations

from typing import Any

from zedcloud.services.base import BaseService
from zedcloud._generated.models.networks import (
    NetConfig,
    NetConfigForUpdateHttpRequest,
    NetConfigList,
    NetInstConfig,
    NetInstConfigStatusList,
    NetInstConfigUpdateHttpRequest,
    NetInstList,
    NetInstStatusListMsg,
    NetInstStatusMsg,
    NetworkDeviceList,
    ObjectTagsList,
    ZsrvResponse,
)


class NetworksService(BaseService):
    """Auto-generated client for ZEDEDA Edge Network Service."""

    def query_edge_network_instances(
        self,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        summary: bool | None = None,
        title_pattern: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        fields: list[str] | None = None,
        request_id: str | None = None,
    ) -> NetInstList:
        """Query edge network instances

        ``GET /v1/netinsts``
        operationId: ``EdgeNetworkInstanceConfiguration_QueryEdgeNetworkInstances``
        """
        path = "/v1/netinsts"
        params: dict[str, Any] = {}
        if device_name is not None:
            params["deviceName"] = device_name
        if project_name is not None:
            params["projectName"] = project_name
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if tags is not None:
            params["tags"] = tags
        if device_name_pattern is not None:
            params["deviceNamePattern"] = device_name_pattern
        if project_name_pattern is not None:
            params["projectNamePattern"] = project_name_pattern
        if summary is not None:
            params["summary"] = summary
        if title_pattern is not None:
            params["titlePattern"] = title_pattern
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if fields is not None:
            params["fields"] = fields
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=NetInstList)

    def create_edge_network_instance(self, body: NetInstConfig | dict[str, Any], request_id: str | None = None) -> ZsrvResponse:
        """Create edge network instance

        ``POST /v1/netinsts``
        operationId: ``EdgeNetworkInstanceConfiguration_CreateEdgeNetworkInstance``
        """
        path = "/v1/netinsts"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("POST", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_edge_network_instance(self, id: str, request_id: str | None = None) -> NetInstConfig:
        """Get edge network instance

        ``GET /v1/netinsts/id/{id}``
        operationId: ``EdgeNetworkInstanceConfiguration_GetEdgeNetworkInstance``
        """
        path = f"/v1/netinsts/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=NetInstConfig)

    def delete_edge_network_instance(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Delete edge network instance

        ``DELETE /v1/netinsts/id/{id}``
        operationId: ``EdgeNetworkInstanceConfiguration_DeleteEdgeNetworkInstance``
        """
        path = f"/v1/netinsts/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("DELETE", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def update_edge_network_instance(
        self,
        id: str,
        body: NetInstConfigUpdateHttpRequest | dict[str, Any],
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update edge network instance

        ``PUT /v1/netinsts/id/{id}``
        operationId: ``EdgeNetworkInstanceConfiguration_UpdateEdgeNetworkInstance``
        """
        path = f"/v1/netinsts/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_edge_network_instance_status(self, id: str, request_id: str | None = None) -> NetInstStatusMsg:
        """Get edge network instance status

        ``GET /v1/netinsts/id/{id}/status``
        operationId: ``EdgeNetworkInstanceStatus_GetEdgeNetworkInstanceStatus``
        """
        path = f"/v1/netinsts/id/{id}/status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=NetInstStatusMsg)

    def get_edge_network_instance_by_name(self, name: str, request_id: str | None = None) -> NetInstConfig:
        """Get edge network instance

        ``GET /v1/netinsts/name/{name}``
        operationId: ``EdgeNetworkInstanceConfiguration_GetEdgeNetworkInstanceByName``
        """
        path = f"/v1/netinsts/name/{name}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=NetInstConfig)

    def get_edge_network_instance_status_by_name(self, name: str, request_id: str | None = None) -> NetInstStatusMsg:
        """Get edge network instance status

        ``GET /v1/netinsts/name/{name}/status``
        operationId: ``EdgeNetworkInstanceStatus_GetEdgeNetworkInstanceStatusByName``
        """
        path = f"/v1/netinsts/name/{name}/status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=NetInstStatusMsg)

    def query_edge_network_instance_status(
        self,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        run_state: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        type: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        fields: list[str] | None = None,
        request_id: str | None = None,
    ) -> NetInstStatusListMsg:
        """Query status of edge network instances

        ``GET /v1/netinsts/status``
        operationId: ``EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatus``
        """
        path = "/v1/netinsts/status"
        params: dict[str, Any] = {}
        if device_name is not None:
            params["deviceName"] = device_name
        if project_name is not None:
            params["projectName"] = project_name
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if tags is not None:
            params["tags"] = tags
        if run_state is not None:
            params["runState"] = run_state
        if device_name_pattern is not None:
            params["deviceNamePattern"] = device_name_pattern
        if project_name_pattern is not None:
            params["projectNamePattern"] = project_name_pattern
        if type is not None:
            params["type"] = type
        if kind is not None:
            params["kind"] = kind
        if summary is not None:
            params["summary"] = summary
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if fields is not None:
            params["fields"] = fields
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=NetInstStatusListMsg)

    def query_edge_network_instance_status_config(
        self,
        device_name: str | None = None,
        project_name: str | None = None,
        name_pattern: str | None = None,
        tags: str | None = None,
        run_state: str | None = None,
        device_name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        type: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        fields: list[str] | None = None,
        request_id: str | None = None,
    ) -> NetInstConfigStatusList:
        """Query status and config of edge network instances

        ``GET /v1/netinsts/status-config``
        operationId: ``EdgeNetworkInstanceStatus_QueryEdgeNetworkInstanceStatusConfig``
        """
        path = "/v1/netinsts/status-config"
        params: dict[str, Any] = {}
        if device_name is not None:
            params["deviceName"] = device_name
        if project_name is not None:
            params["projectName"] = project_name
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if tags is not None:
            params["tags"] = tags
        if run_state is not None:
            params["runState"] = run_state
        if device_name_pattern is not None:
            params["deviceNamePattern"] = device_name_pattern
        if project_name_pattern is not None:
            params["projectNamePattern"] = project_name_pattern
        if type is not None:
            params["type"] = type
        if kind is not None:
            params["kind"] = kind
        if summary is not None:
            params["summary"] = summary
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        if fields is not None:
            params["fields"] = fields
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=NetInstConfigStatusList)

    def get_network_instance_interface_tags(
        self,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> ObjectTagsList:
        """Query Network instance tags

        ``GET /v1/netinsts/tags``
        operationId: ``EdgeNetworkInstanceStatus_GetNetworkInstanceInterfaceTags``
        """
        path = "/v1/netinsts/tags"
        params: dict[str, Any] = {}
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=ObjectTagsList)

    def query_edge_networks(
        self,
        project_name: str | None = None,
        name_pattern: str | None = None,
        project_name_pattern: str | None = None,
        dist: int | None = None,
        kind: int | None = None,
        summary: bool | None = None,
        default_network: bool | None = None,
        title_pattern: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> NetConfigList:
        """Query edge networks

        ``GET /v1/networks``
        operationId: ``EdgeNetworkConfiguration_QueryEdgeNetworks``
        """
        path = "/v1/networks"
        params: dict[str, Any] = {}
        if project_name is not None:
            params["projectName"] = project_name
        if name_pattern is not None:
            params["namePattern"] = name_pattern
        if project_name_pattern is not None:
            params["projectNamePattern"] = project_name_pattern
        if dist is not None:
            params["dist"] = dist
        if kind is not None:
            params["kind"] = kind
        if summary is not None:
            params["summary"] = summary
        if default_network is not None:
            params["defaultNetwork"] = default_network
        if title_pattern is not None:
            params["titlePattern"] = title_pattern
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=NetConfigList)

    def create_edge_network(self, body: NetConfig | dict[str, Any], request_id: str | None = None) -> ZsrvResponse:
        """Create edge network

        ``POST /v1/networks``
        operationId: ``EdgeNetworkConfiguration_CreateEdgeNetwork``
        """
        path = "/v1/networks"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("POST", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_edge_network(self, id: str, request_id: str | None = None) -> NetConfig:
        """Get edge network

        ``GET /v1/networks/id/{id}``
        operationId: ``EdgeNetworkConfiguration_GetEdgeNetwork``
        """
        path = f"/v1/networks/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=NetConfig)

    def delete_edge_network(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Delete edge network

        ``DELETE /v1/networks/id/{id}``
        operationId: ``EdgeNetworkConfiguration_DeleteEdgeNetwork``
        """
        path = f"/v1/networks/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("DELETE", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def update_edge_network(
        self,
        id: str,
        body: NetConfigForUpdateHttpRequest | dict[str, Any],
        request_id: str | None = None,
    ) -> ZsrvResponse:
        """Update edge network

        ``PUT /v1/networks/id/{id}``
        operationId: ``EdgeNetworkConfiguration_UpdateEdgeNetwork``
        """
        path = f"/v1/networks/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_edge_network_devices_by_id(self, id: str, request_id: str | None = None) -> NetworkDeviceList:
        """Get edge network devices by id

        ``GET /v1/networks/id/{id}/devices``
        operationId: ``EdgeNetworkConfiguration_GetEdgeNetworkDevicesById``
        """
        path = f"/v1/networks/id/{id}/devices"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=NetworkDeviceList)

    def get_edge_network_by_name(self, name: str, request_id: str | None = None) -> NetConfig:
        """Get edge network

        ``GET /v1/networks/name/{name}``
        operationId: ``EdgeNetworkConfiguration_GetEdgeNetworkByName``
        """
        path = f"/v1/networks/name/{name}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=NetConfig)
