# Generated by scripts/generate_from_openapi.py — namespace "node_clusters"
# Do not edit by hand.

from __future__ import annotations

from typing import Any

from zedcloud.services.base import BaseService
from zedcloud._generated.models.node_clusters import (
    BaseOSImage,
    EdgeNodeCluster,
    EdgeNodeClusterConfigSummary,
    EdgeNodeClusterInterfacePorts,
    EdgeNodeClusterProjects,
    EdgeNodeClusterRawInfo,
    EdgeNodeClusterStatus,
    EdgeNodeClusterUpgradeStatusResp,
    EdgeNodeClusters,
    ZsrvResponse,
)


class NodeClustersService(BaseService):
    """Auto-generated client for ZEDEDA Edge-Node Cluster Service."""

    def query_clusters(
        self,
        filter_project_name: str | None = None,
        filter_project_name_pattern: str | None = None,
        filter_name_pattern: str | None = None,
        filter_include_zks: str | None = None,
        filter_title_pattern: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> EdgeNodeClusters:
        """Query Edge-Node Clusters.

        ``GET /v1/cluster``
        operationId: ``EdgeNodeClusterConfiguration_QueryClusters``
        """
        path = "/v1/cluster"
        params: dict[str, Any] = {}
        if filter_project_name is not None:
            params["filter.projectName"] = filter_project_name
        if filter_project_name_pattern is not None:
            params["filter.projectNamePattern"] = filter_project_name_pattern
        if filter_name_pattern is not None:
            params["filter.namePattern"] = filter_name_pattern
        if filter_include_zks is not None:
            params["filter.includeZks"] = filter_include_zks
        if filter_title_pattern is not None:
            params["filter.titlePattern"] = filter_title_pattern
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EdgeNodeClusters)

    def create_cluster(self, body: EdgeNodeCluster | dict[str, Any], request_id: str | None = None) -> ZsrvResponse:
        """Create Edge-Node Cluster.

        ``POST /v1/cluster``
        operationId: ``EdgeNodeClusterConfiguration_CreateCluster``
        """
        path = "/v1/cluster"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("POST", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_available_projects_for_cluster(
        self,
        filter_project_name: str | None = None,
        filter_project_name_pattern: str | None = None,
        filter_name_pattern: str | None = None,
        filter_include_zks: str | None = None,
        filter_title_pattern: str | None = None,
        next_page_token: str | None = None,
        next_order_by: list[str] | None = None,
        next_page_num: float | None = None,
        next_page_size: float | None = None,
        next_total_pages: float | None = None,
        request_id: str | None = None,
    ) -> EdgeNodeClusterProjects:
        """Get Edge-Node Cluster Available Projects.

        ``GET /v1/cluster/available/projects``
        operationId: ``EdgeNodeClusterConfiguration_GetAvailableProjectsForCluster``
        """
        path = "/v1/cluster/available/projects"
        params: dict[str, Any] = {}
        if filter_project_name is not None:
            params["filter.projectName"] = filter_project_name
        if filter_project_name_pattern is not None:
            params["filter.projectNamePattern"] = filter_project_name_pattern
        if filter_name_pattern is not None:
            params["filter.namePattern"] = filter_name_pattern
        if filter_include_zks is not None:
            params["filter.includeZks"] = filter_include_zks
        if filter_title_pattern is not None:
            params["filter.titlePattern"] = filter_title_pattern
        if next_page_token is not None:
            params["next.pageToken"] = next_page_token
        if next_order_by is not None:
            params["next.orderBy"] = next_order_by
        if next_page_num is not None:
            params["next.pageNum"] = next_page_num
        if next_page_size is not None:
            params["next.pageSize"] = next_page_size
        if next_total_pages is not None:
            params["next.totalPages"] = next_total_pages
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EdgeNodeClusterProjects)

    def get_cluster(self, id: str, request_id: str | None = None) -> EdgeNodeClusterConfigSummary:
        """Get Edge-Node Cluster.

        ``GET /v1/cluster/id/{id}``
        operationId: ``EdgeNodeClusterConfiguration_GetCluster``
        """
        path = f"/v1/cluster/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EdgeNodeClusterConfigSummary)

    def delete_cluster(self, id: str, request_id: str | None = None) -> ZsrvResponse:
        """Delete Edge-Node Cluster.

        ``DELETE /v1/cluster/id/{id}``
        operationId: ``EdgeNodeClusterConfiguration_DeleteCluster``
        """
        path = f"/v1/cluster/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("DELETE", path, params=params or None, headers=headers or None, response_model=ZsrvResponse)

    def update_cluster(self, id: str, body: dict[str, Any] | Any, request_id: str | None = None) -> ZsrvResponse:
        """Update Edge-Node Cluster.

        ``PUT /v1/cluster/id/{id}``
        operationId: ``EdgeNodeClusterConfiguration_UpdateCluster``
        """
        path = f"/v1/cluster/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_cluster_ports(self, id: str, request_id: str | None = None) -> EdgeNodeClusterInterfacePorts:
        """Get Edge-Node Cluster Interface Ports.

        ``GET /v1/cluster/id/{id}/ports``
        operationId: ``EdgeNodeClusterConfiguration_GetClusterPorts``
        """
        path = f"/v1/cluster/id/{id}/ports"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EdgeNodeClusterInterfacePorts)

    def get_cluster_raw_status(self, id: str, request_id: str | None = None) -> EdgeNodeClusterRawInfo:
        """Get Edge-Node Cluster raw status.

        ``GET /v1/cluster/id/{id}/raw/status``
        operationId: ``ClusterStatus_GetClusterRawStatus``
        """
        path = f"/v1/cluster/id/{id}/raw/status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EdgeNodeClusterRawInfo)

    def get_cluster_status(self, id: str, request_id: str | None = None) -> EdgeNodeClusterStatus:
        """Get Edge-Node Cluster status.

        ``GET /v1/cluster/id/{id}/status``
        operationId: ``ClusterStatus_GetClusterStatus``
        """
        path = f"/v1/cluster/id/{id}/status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EdgeNodeClusterStatus)

    def upgrade_cluster(self, id: str, body: BaseOSImage | dict[str, Any], request_id: str | None = None) -> ZsrvResponse:
        """Upgrade Edge-Node Cluster.

        ``PUT /v1/cluster/id/{id}/upgrade``
        operationId: ``EdgeNodeClusterConfiguration_UpgradeCluster``
        """
        path = f"/v1/cluster/id/{id}/upgrade"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("PUT", path, params=params or None, headers=headers or None, json_body=body, response_model=ZsrvResponse)

    def get_cluster_upgrade_status(self, id: str, request_id: str | None = None) -> EdgeNodeClusterUpgradeStatusResp:
        """Get Edge-Node Cluster upgrade status.

        ``GET /v1/cluster/id/{id}/upgrade/status``
        operationId: ``ClusterStatus_GetClusterUpgradeStatus``
        """
        path = f"/v1/cluster/id/{id}/upgrade/status"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EdgeNodeClusterUpgradeStatusResp)

    def get_cluster_by_name(self, name: str, request_id: str | None = None) -> EdgeNodeClusterConfigSummary:
        """Get Edge-Node Cluster.

        ``GET /v1/cluster/name/{name}``
        operationId: ``EdgeNodeClusterConfiguration_GetClusterByName``
        """
        path = f"/v1/cluster/name/{name}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EdgeNodeClusterConfigSummary)

    def get_cluster_by_node_id(self, id: str, request_id: str | None = None) -> EdgeNodeClusterConfigSummary:
        """Get Edge-Node Cluster.

        ``GET /v1/cluster/node/id/{id}``
        operationId: ``EdgeNodeClusterConfiguration_GetClusterByNodeId``
        """
        path = f"/v1/cluster/node/id/{id}"
        params: dict[str, Any] = {}
        headers: dict[str, str] = {}
        if request_id is not None:
            headers["X-Request-Id"] = request_id
        return self._request("GET", path, params=params or None, headers=headers or None, response_model=EdgeNodeClusterConfigSummary)
